Repository eksctl-io/eksctl, pull requests merged in 2019-10, with the labels that each got.

#1244 Fix nodegroup delete fail when PDB isn't respected
  pkg/drain/drain.go
  pkg/drain/nodegroup.go
Labels: priority/weave

#1149 Enable management of access to public/private API endpoints
  go.mod
  go.sum
  integration/cluster_api_endpoints_test.go
  integration/runner/runner.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/vpc_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/outputs/api.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/nodegroup_filter_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
  pkg/ctl/utils/utils.go
  pkg/eks/tasks.go
  pkg/eks/update.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_suite_test.go
  pkg/vpc/vpc_test.go
  site/content/introduction/03-features.md
  site/content/usage/06-vpc-networking.md
  site/content/usage/20-schema.md
Labels: area/config-file, area/general-cli, kind/feature

#1431 Rename pkg/ctl/enable/flux.go -> repo.go
  pkg/ctl/enable/repo.go
Labels: area/gitops

#1440 Add GitOps-related types to ClusterConfig
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/nodebootstrap/maxpods.go
  site/content/usage/20-schema.md
Labels: area/gitops

#1457 Print go-bindata version when building
  Makefile
  go.sum
Labels: area/build-and-release, version/0.8.0

#1475 make build: update go.mod to latest dependencies
  go.mod
Labels: area/build-and-release

#1483 Revert "Add GitOps-related types to ClusterConfig"
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  site/content/usage/20-schema.md
Labels: area/gitops
