Repository eksctl-io/eksctl, pull requests merged in 2019-11, with the labels that each got.

#1515 Fix some typos in the VPC documentation on the site
  site/content/usage/06-vpc-networking.md
Labels: version/0.9.0

#1384 Marked 1.11 as deprecated
  docs/proposal-005-upgrades.md
  pkg/apis/eksctl.io/v1alpha5/types.go
  site/content/introduction/01-getting-started.md
Labels: version/0.9.0

#1509 Separate GitOps commands' responsibilities
  integration/creategetdelete_test.go
  integration/flux_utils_test.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/enable/profile.go
  pkg/ctl/enable/repo.go
  pkg/ctl/enable/utils.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/gitops/flux/installer.go
  pkg/gitops/profile/options.go
  pkg/gitops/profile/url.go
  pkg/gitops/profile/url_test.go
  site/content/gitops-quickstart/01-apply-gitops.md
Labels: version/0.9.0

#1540 Add release notes for 0.9.0
  docs/release_notes/0.9.0.md
Labels: version/0.9.0

#1541 Fix validation of git origin in release scripts
  tag-release-candidate.sh
  tag-release.sh
Labels: area/build-and-release, kind/bug, version/0.9.0

#1544 Add draft.md to gather temporary release notes
  docs/release_notes/draft.md
Labels: area/build-and-release, version/0.10.0

#1546 Fix PATH in dockerfile
  Dockerfile
Labels: version/0.10.0

#1563 Add support for c5d.12x/c5d.24x/c5d.metal instances
  pkg/nodebootstrap/maxpods.go
Labels: version/0.10.0

#1583 Fix `update cluster` for EKS clusters below platform version `eks.3`
  docs/release_notes/draft.md
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/cfn/outputs/api.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/update/cluster.go
  pkg/eks/eks.go
  pkg/eks/eks_test.go
  pkg/eks/nodegroup.go
Labels: version/0.10.2

#1613 Increase timeout for public/private endpoint tests
  integration/cluster_api_endpoints_test.go
  integration/createdeletebeforeactive_test.go
Labels: version/0.11.0
