Repository eksctl-io/eksctl, pull requests merged in 2019-08, with the labels that each got.

#1092 Fix documentation for cloudWatch logging
  site/content/usage/12-cloudwatch-cluster-logging.md
Labels: kind/bug

#1106 Fix a number of links in documentation
  site/content/introduction/01-getting-started.md
  site/content/usage/06-vpc-networking.md
  site/content/usage/12-cloudwatch-cluster-logging.md
Labels: kind/docs

#1146 Readded the ability to delete a cluster before it's finished creating
  integration/common_test.go
  integration/createdeletebeforeactive_test.go
  pkg/ctl/cmdutils/cmd.go
  pkg/ctl/delete/cluster.go
Labels: area/deletions

#1171 Improve integration test helpers
  .gometalinter.json
  Makefile
  integration/common_test.go
  integration/createdeletebeforeactive_test.go
  integration/creategetdelete_test.go
  integration/gitopscreateprofile_test.go
  integration/integration_test.go
  integration/matchers/cloudformation.go
  integration/matchers/matchers.go
  integration/matchers/session.go
  integration/runner/runner.go
  integration/runner/runner_suite_test.go
  integration/runner/runner_test.go
  pkg/testutils/matchers/have_cfn_stack_matcher.go
Labels: priority/weave

#1207 Fix support for ap-east-1 region and Ubuntu1804 image family on Kubernetes 1.13
  pkg/ami/static_resolver_ami.go
  pkg/ami/static_resolver_test.go
  pkg/eks/api_test.go
Labels: kind/bug

#1231 Restructure Git-related tests
  pkg/git/git_suite_test.go
  pkg/git/git_test.go
Labels: technical debt
