Repository eksctl-io/eksctl, pull requests merged in 2019-12, with the labels that each got.

#1557 Fixed the wrong Expect() in existing test cases
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: version/0.11.0

#1627 Update docs to add link to AWS EKS Fargate docs
  site/content/usage/16-fargate-support.md
Labels: area/fargate, kind/docs, version/0.11.0

#1628 Fix `eksctl create fargateprofile` when using a config file with multiple Fargate profiles
  docs/release_notes/0.11.0.md
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
Labels: area/fargate, version/0.11.0

#1633 Update fargate docs
  site/content/usage/15-eks-managed-nodes.md
  site/content/usage/16-fargate-support.md
Labels: version/0.11.0

#1629 Add reminder about labels & release note to PR checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/build-and-release, contributor experience

#1637 Fix `delete cluster` on AWS accounts not authorized to use Fargate
  pkg/ctl/delete/cluster.go
  pkg/fargate/client.go
Labels: area/fargate, version/0.11.0

#1644 Increase global timeout of Integration Tests
  Makefile
Labels: version/0.12.0

#1648 Upgrade Go to 1.13
  .build_image_manifest
  .circleci/config.yml
  .github/workflows/commit.yaml
  Dockerfile
  go.mod
  integration/integration_test.go
Labels: version/0.12.0

#1647 Fix CircleCI config for IT
  .circleci/config.yml
Labels: version/0.12.0

#1659 Update maxpods.go
  pkg/nodebootstrap/maxpods.go
Labels: version/0.12.0

#1658 Fix circleci configuration for IT job
  .circleci/config.yml
Labels: version/0.12.0

#1615 Enable loading of private Go modules
  .build_image_manifest
  .circleci/config.yml
  .github/workflows/commit.yaml
  Dockerfile
  Makefile.docker
Labels: version/0.12.0

#1661 Fix propagating errors from AssignSubnets
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/nodegroup.go
Labels: area/aws-vpc, version/0.12.0

#1660 Update PR template with mention of the maintainer GH team
  .github/PULL_REQUEST_TEMPLATE.md
Labels: version/0.12.0

#1664 Refactor: no longer exit on nested cmd but propagate error
  cmd/eksctl/main.go
  docs/release_notes/draft.md
  pkg/ctl/cmdutils/cmd.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/iamidentitymapping.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/delete/cluster.go
  pkg/ctl/delete/fargate.go
  pkg/ctl/delete/iamidentitymapping.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/enable/profile.go
  pkg/ctl/enable/repo.go
  pkg/ctl/generate/profile.go
  pkg/ctl/get/cluster.go
  pkg/ctl/get/fargate.go
  pkg/ctl/get/iamidentitymapping.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/ctl/get/labels.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/set/labels.go
  pkg/ctl/unset/labels.go
  pkg/ctl/update/cluster.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/ctl/utils/associate_iam_oidc_provider.go
  pkg/ctl/utils/describe_stacks.go
  pkg/ctl/utils/install_vpc_controllers.go
  pkg/ctl/utils/nodegroup_health.go
  pkg/ctl/utils/update_aws_node.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
  pkg/ctl/utils/update_cluster_logging.go
  pkg/ctl/utils/update_coredns.go
  pkg/ctl/utils/update_kube_proxy.go
  pkg/ctl/utils/wait_nodes.go
  pkg/ctl/utils/write_kubeconfig.go
Labels: area/general-cli, version/0.12.0

#1666 Update Fargate docs & example manifest to follow naming convention
  docs/release_notes/draft.md
  examples/16-fargate-profile.yaml
  site/content/usage/16-fargate-support.md
Labels: area/config-file, area/fargate, kind/docs, version/0.12.0

#1667 eksctl {get,delete} fargateprofile now reads the cluster name & region from ClusterConfig
  docs/release_notes/draft.md
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/fargate.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/fargate_test.go
  pkg/ctl/delete/fargate.go
  pkg/ctl/delete/fargate_test.go
  pkg/ctl/get/fargate.go
  pkg/ctl/get/fargate_test.go
Labels: area/config-file, area/fargate, area/general-cli, area/testing, kind/feature, version/0.12.0

#1620 Make IAM OIDC provider configuration work with a proxy
  pkg/iam/oidc/api.go
  pkg/iam/oidc/api_test.go
Labels: version/0.12.0

#1674 Update AMIs for all regions
  pkg/ami/static_resolver_ami.go
  pkg/ami/static_resolver_test.go
  pkg/eks/api_test.go
Labels: version/0.12.0

#1677 No longer print usage/help on errors
  cmd/eksctl/main.go
  docs/release_notes/draft.md
Labels: area/general-cli, version/0.12.0

#1554 Upgrade CNI plugin to version 1.5.5
  docs/release_notes/draft.md
  pkg/addons/default/assets.go
  pkg/addons/default/assets/aws-node.yaml
  pkg/addons/default/aws_node_test.go
  pkg/addons/default/generate.go
Labels: version/0.12.0

#1665 Support Managed Nodegroups and Fargate for auto-upgraded clusters
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/compat.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/tasks.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/nodegroup.go
  site/content/usage/15-eks-managed-nodes.md
Labels: area/fargate, area/managed-nodegroup, area/upgrades

#1668 Move aws-sdk-go dep to weaveworks/aws-sdk-go
  go.mod
  go.sum
Labels: version/0.12.0

#1685 Fix build: Remove traces of weaveworks-experiments
  Makefile
  go.sum
Labels: version/0.12.0

#1688 Implement Public Endpoint CIDR restrictions
  .docker/build_image_manifest
  .docker/image_tag
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/utils/set_public_access_cidrs.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
  pkg/ctl/utils/utils.go
  pkg/eks/mocks/EC2API.go
  pkg/eks/mocks/SSMAPI.go
  pkg/eks/tasks.go
  pkg/eks/testdata/singlecluster_deleting.golden
  pkg/eks/update.go
  pkg/printers/testdata/jsontest_2clusters.golden
  pkg/printers/testdata/jsontest_single.golden
  pkg/printers/testdata/yamltest_2clusters.golden
  pkg/printers/testdata/yamltest_single.golden
  site/content/usage/06-vpc-networking.md
  site/content/usage/20-schema.md
Labels: area/config-file, kind/feature, version/0.12.0

#1687 Release notes for 0.12.0
  docs/release_notes/0.12.0.md
  docs/release_notes/draft.md
Labels: version/0.12.0

#1690 Fix circleci release pipeline
  .circleci/config.yml
  Makefile.docker
Labels: version/0.12.0

#1691 Remove repeated test and build steps from release pipelines
  .circleci/config.yml
  Makefile.docker
Labels: version/0.13.0
