Repository eksctl-io/eksctl, pull requests merged in 2020-07, with the labels that each got.

#2387 Skip MapPublicIpOnLaunch check for ManagedNodeGroups with privateNetwork flag
  pkg/vpc/vpc.go
Labels: kind/bug

#2393 Remove potentially offensive language
  cmd/schema/generate.go
Labels: kind/improvement

#2394 Add schema docs for git, fargate and cloudwatch
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/cloudwatch.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: area/docs, kind/docs

#2392 Add github workflow to merge release branch to master
  .github/workflows/release-merge.yaml
Labels: area/build-and-release

#2384 Implement creation of fully-private clusters
  integration/tests/cluster_api/cluster_api_endpoints_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/defaults_test.go
  pkg/apis/eksctl.io/v1alpha5/endpoint_service.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/testdata/custom_vpc_private_endpoint.json
  pkg/cfn/builder/testdata/vpc_private.json
  pkg/cfn/builder/testdata/vpc_private_endpoint.json
  pkg/cfn/builder/testdata/vpc_public.json
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_endpoint.go
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/cfn/outputs/api.go
  pkg/ctl/cmdutils/cluster.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/filter/nodegroup_filter.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/cmdutils/scale.go
  pkg/ctl/cmdutils/scale_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/delete/nodegroup.go
  pkg/eks/nodegroup_service.go
  pkg/nodebootstrap/userdata_bottlerocket_test.go
  pkg/nodebootstrap/userdata_test.go
  pkg/nodebootstrap/userdata_win_test.go
  pkg/utils/kubeconfig/kubeconfig_test.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
  userdocs/src/usage/eks-private-cluster.md
Labels: area/aws-vpc, kind/feature

#2410 Check if JSON schema is up to date
  Makefile
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
Labels: area/build-and-release, kind/bug

#2413 Enforce PR labels for release notes categorization
  .github/release-drafter.yml
  .github/workflows/pr-labels.yaml
Labels: skip-release-notes

#2407 Add support for Kubernetes 1.17
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.17.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/cluster_test.go
  userdocs/src/introduction.md
Labels: kind/feature

#2414 Fix cluster upgrading to default version always
  pkg/ctl/update/cluster.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/cluster_test.go
Labels: kind/bug

#2386 Extract git provider (github) code to library
  .docker/build_image_manifest
  .docker/image_tag
  go.mod
  go.sum
  pkg/ctl/delete/cluster.go
  pkg/gitops/deploykey/deploykey.go
  pkg/gitops/deploykey/github.go
  pkg/gitops/deploykey/github_test.go
  pkg/gitops/flux/installer.go
  pkg/gitops/gitops.go
Labels: area/gitops, skip-release-notes, technical debt

#2416 Fix nil pointer dereference in scale command
  pkg/ctl/cmdutils/scale.go
  pkg/ctl/cmdutils/scale_test.go
Labels: area/nodegroup, kind/bug

#2417 Fix name argument for scale nodegroup
  pkg/ctl/cmdutils/cmd.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/fargate.go
  pkg/ctl/cmdutils/scale.go
  pkg/ctl/cmdutils/scale_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/iamidentitymapping.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/delete/cluster.go
  pkg/ctl/delete/fargate.go
  pkg/ctl/delete/iamidentitymapping.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/enable/profile.go
  pkg/ctl/enable/repo.go
  pkg/ctl/generate/profile.go
  pkg/ctl/get/cluster.go
  pkg/ctl/get/fargate.go
  pkg/ctl/get/iamidentitymapping.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/ctl/get/labels.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/set/labels.go
  pkg/ctl/unset/labels.go
  pkg/ctl/update/cluster.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/ctl/utils/associate_iam_oidc_provider.go
  pkg/ctl/utils/describe_stacks.go
  pkg/ctl/utils/install_vpc_controllers.go
  pkg/ctl/utils/nodegroup_health.go
  pkg/ctl/utils/set_public_access_cidrs.go
  pkg/ctl/utils/update_aws_node.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
  pkg/ctl/utils/update_cluster_logging.go
  pkg/ctl/utils/update_coredns.go
  pkg/ctl/utils/update_kube_proxy.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/ctl/utils/wait_nodes.go
  pkg/ctl/utils/write_kubeconfig.go
Labels: area/nodegroup, kind/bug

#2419 Add release notes for 0.24
  docs/release_notes/0.24.0.md
Labels: skip-release-notes

#2424 docs(gitops-quickstart.md): add missing eksctl
  userdocs/src/gitops-quickstart.md
Labels: kind/docs, skip-release-notes

#2422 Schema docs improvements
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/usage/schema.css
  userdocs/src/usage/schema.js
Labels: area/docs, kind/docs, skip-release-notes

#2406 Update for rebased goformation fork
  go.mod
  go.sum
  pkg/cfn/builder/api.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/fargate.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/outputs.go
  pkg/cfn/builder/partition.go
  pkg/cfn/builder/testdata/vpc_public.json
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_endpoint.go
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/cfn/manager/compat.go
  pkg/cfn/outputs/api.go
  pkg/cfn/template/iam_helpers.go
Labels: skip-release-notes

#2421 Increase timeout for backwards compat test
  integration/tests/backwards_compat/backwards_compatibility_test.go
Labels: area/testing, skip-release-notes

#2429 Fix subnet route table validation for user-supplied VPCs
  pkg/cfn/builder/vpc.go
Labels: kind/bug

#2431 [release-0.24] Fix subnet route table validation for user-supplied VPCs
  pkg/cfn/builder/vpc.go
Labels: skip-release-notes

#2433 Fix empty slices being null with goformation
  go.mod
  go.sum
Labels: kind/bug

#2423 Add skip-release-notes to release to master merges
  .github/workflows/release-merge.yaml
Labels: area/build-and-release, skip-release-notes

#2436 Increase timeout for backwards compatibility test
  integration/tests/backwards_compat/backwards_compatibility_test.go
Labels: kind/bug

#2439 Do not thank @weaveworksbot
  .github/release-drafter.yml
Labels: skip-release-notes

#2440 Don't merge from release if the diff is empty
  .github/workflows/release-merge.yaml
Labels: area/build-and-release, skip-release-notes

#2437 Wait for control plane to report new version after upgrade
  integration/tests/managed/managed_nodegroup_test.go
  pkg/eks/update.go
Labels: area/upgrades, kind/improvement

#2444 Make 1.17 default
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/api_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/introduction.md
Labels: area/general-cli, kind/feature

#2427 Use noreply email as example in gitops docs
  userdocs/src/usage/gitops.md
Labels: skip-release-notes

#2426 Use noreply email as example in gitops-quickstart docs
  userdocs/src/gitops-quickstart.md
Labels: kind/docs, skip-release-notes

#2446 Handle package references and duplicate enums in schema
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/schema/definition/comment.go
  pkg/schema/definition/common.go
  pkg/schema/definition/definition.go
  pkg/schema/definition/enum.go
  pkg/schema/importer/importer.go
  pkg/schema/schema_test.go
  pkg/schema/test/subpkg/subpkg.go
  pkg/schema/test/test.go
Labels: kind/docs, skip-release-notes

#2453 Fix validation of mixed instances with cpuCredits option
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: area/nodegroup, kind/bug, skip-release-notes

#2455 Added eks-fargate-pods.amazonaws.com to policy condition
  userdocs/src/usage/minimum-iam-policies.md
Labels: kind/docs, skip-release-notes

#2451 Don't attach unnecessary policy to cluster IAM role
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
Labels: area/aws-iam, kind/improvement

#2442 more details for app-dev profile
  userdocs/src/gitops-quickstart.md
Labels: skip-release-notes

#2449 Weaveworks Launcher Dependecy Upgrade
  go.mod
  go.sum
  pkg/ctl/create/cluster.go
  pkg/utils/kubectl/kubectl.go
Labels: skip-release-notes

#2456 notify-slack on release
  .circleci/config.yml
Labels: area/build-and-release, skip-release-notes

#2425 Explain flux frequency in Gitops Quickstart
  userdocs/src/gitops-quickstart.md
Labels: kind/docs, skip-release-notes

#2459 Don't replace service account with update-aws-node
  pkg/addons/default/aws_node.go
  pkg/addons/default/aws_node_test.go
Labels: area/aws-iam, kind/improvement

#2458 Add FAQ about reading nodegroup userdata, denoise FAQ questions
  userdocs/src/usage/faq.md
Labels: kind/docs, skip-release-notes

#2450 More config schema docs improvements
  cmd/schema/generate.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  userdocs/src/usage/schema.css
  userdocs/src/usage/schema.js
Labels: kind/docs, skip-release-notes

#2460 Add disableIMDSv1 config option
  examples/05-advanced-nodegroups.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/nodegroup.go
Labels: area/nodegroup, kind/feature

#2464 Restore "auto" version for upgrade cluster
  pkg/ctl/upgrade/cluster.go
  pkg/utils/utils.go
Labels: area/config-file, area/upgrades, kind/bug

#2465 Cleanup ALBs created by AWS ALB Ingress Controller
  pkg/ctl/delete/cluster.go
  pkg/elb/cleanup.go
Labels: kind/improvement

#2463 Various config schema improvements around default values
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/schema/definition/comment.go
  pkg/schema/definition/common.go
  pkg/schema/definition/schematypes.go
  pkg/schema/definition/types.go
  pkg/schema/schema_test.go
  userdocs/src/usage/schema.js
Labels: kind/docs, skip-release-notes

#2469 Improve spot instance schema and docs
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/usage/schema.css
  userdocs/src/usage/spot-instances.md
Labels: kind/docs, skip-release-notes

#2470 Remove jsonschema tags, respect +required
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/schema/definition/comment.go
  pkg/schema/definition/comment_test.go
  pkg/schema/definition/definition.go
  pkg/schema/definition/tags.go
  pkg/schema/schema_test.go
  pkg/schema/test/test.go
Labels: area/build-and-release, kind/docs, skip-release-notes

#2466 Cleanup build and release scripts
  .docker/build_image_manifest
  .docker/image_tag
  Makefile
  Makefile.docker
  build/scripts/build-image-manifest.sh
  build/scripts/do-release-candidate.sh
  build/scripts/do-release.sh
  build/scripts/eksctl-image-builder.sh
  build/scripts/install-build-deps.sh
  build/scripts/tag-release-candidate.sh
  build/scripts/tag-release.sh
  build/scripts/update-codegen.sh
  hack/deploy-many-workloads.sh
  hack/run-integration-tests.sh
  tools/brew/formula.tmpl
  tools/brew/update_formula.go
Labels: area/build-and-release, skip-release-notes

#2471 Improve VPC config schema
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
Labels: kind/docs, skip-release-notes

#2472 Fix onDemandPercentageAboveBaseCapacity minimum
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/docs, skip-release-notes

#2476 Fix link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip-release-notes

#2475 Add release notes for 0.25
  docs/release_notes/0.25.0.md
Labels: skip-release-notes

#2479 Fix release circleci notifications
  .circleci/config.yml
Labels: area/build-and-release, skip-release-notes

#2483 Change documentation for managed nodegroups
  userdocs/src/usage/eks-managed-nodes.md
Labels: kind/docs, skip-release-notes

#2486 Add docs for schema fields for IAM
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
Labels: skip-release-notes

#2474 Fix that private cluster could not have same subnet route table
  pkg/cfn/builder/testdata/custom_vpc_private_endpoint_same_route_table.json
  pkg/cfn/builder/vpc_endpoint.go
  pkg/cfn/builder/vpc_endpoint_test.go
Labels: kind/bug

#2484 Cleanup docker build files
  .circleci/config.yml
  .gitignore
  Makefile.docker
  build/build_image_manifest
  build/docker/build_image_manifest
  build/docker/image_tag
Labels: area/build-and-release, skip-release-notes

#2490 Add support for Milan (eu-south-1) and Cape Town (af-south-1) regions
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/feature

#2493 Fix notify-slack only_for_branches option
  .circleci/config.yml
Labels: area/build-and-release, skip-release-notes

#2491 Add EKS private cluster usage to sidebar
  userdocs/mkdocs.yml
Labels: skip-release-notes

#2495 [release-0.25] Prepare support for Milan (eu-south-1) and Cape Town (af-south-1) regions
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/feature

#2492 Allow service role some actions necessary for ELB
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
Labels: kind/bug

#2497 Add EKS private cluster usage to sidebar
  userdocs/mkdocs.yml
Labels: skip-release-notes

#2498 Update 0.25 release notes
  docs/release_notes/0.25.0.md
Labels: kind/docs, skip-release-notes
