Repository eksctl-io/eksctl, pull requests merged in 2020-10, with the labels that each got.

#2693 Corrects documentation on st1/sc1 EBS volume types (#2692)
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: area/docs, skip-release-notes

#2697 Fix minor wording issues in `drain` usage
  pkg/ctl/drain/nodegroup.go
Labels: area/docs, skip-release-notes

#2699 Fix deprecated flag in windows docs
  userdocs/src/usage/windows-worker-nodes.md
Labels: area/docs, skip-release-notes

#2703 Do OIDC provider and SA creation before nodegroups
  pkg/ctl/create/cluster.go
  pkg/eks/tasks.go
Labels: area/aws-iam, area/managed-nodegroup, kind/bug

#2706 Fix tiny typo in contributing docs
  CONTRIBUTING.md
Labels: kind/docs, skip-release-notes

#2708 Update nodegroup stack w/ version tag before updating release version
  pkg/cfn/manager/api.go
  pkg/managed/service.go
Labels: area/managed-nodegroup, kind/bug

#2709 Trim .git suffix when adding deploy keys
  pkg/gitops/deploykey/deploykey.go
Labels: kind/bug

#2689 (Managed)NodeGroups: Handle existing instanceRoleARN with nested resource path
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
Labels: kind/improvement

#2711 Fix scheme for nodegroup ami
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/docs, skip-release-notes

#2713 Fix kubernetesNetworkConfig with new nodegroups for existing clusters
  go.mod
  go.sum
  pkg/ctl/create/nodegroup.go
  pkg/eks/eks.go
  pkg/eks/mocks/CloudFormationAPI.go
  pkg/eks/mocks/EC2API.go
  pkg/eks/mocks/SSMAPI.go
  pkg/eks/testdata/singlecluster_deleting.golden
  pkg/printers/testdata/jsontest_2clusters.golden
  pkg/printers/testdata/jsontest_single.golden
  pkg/printers/testdata/yamltest_2clusters.golden
  pkg/printers/testdata/yamltest_single.golden
Labels: area/managed-nodegroup, area/nodegroup, kind/bug

#2714 Fix kubernetesNetworkConfig with new nodegroups for existing clusters
  docs/release_notes/0.29.2.md
  go.mod
  go.sum
  pkg/ctl/create/nodegroup.go
  pkg/eks/eks.go
  pkg/eks/mocks/CloudFormationAPI.go
  pkg/eks/mocks/EC2API.go
  pkg/eks/mocks/SSMAPI.go
  pkg/eks/testdata/singlecluster_deleting.golden
  pkg/printers/testdata/jsontest_2clusters.golden
  pkg/printers/testdata/jsontest_single.golden
  pkg/printers/testdata/yamltest_2clusters.golden
  pkg/printers/testdata/yamltest_single.golden
Labels: kind/bug, skip-release-notes

#2715 Update maxpods for p4d.24xlarge
  pkg/nodebootstrap/maxpods.go
Labels: kind/improvement

#2710 Deprecate static AMI resolver
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/eks/api.go
Labels: kind/docs, skip-release-notes

#2723 Add support for Kubernetes 1.18
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.18.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/cluster_test.go
  userdocs/src/introduction.md
Labels: kind/feature

#2729 Add release notes for 0.30.0
  docs/release_notes/0.30.0.md
Labels: kind/docs, skip-release-notes

#2731 return non-zero when a given nodegroup doesn't exist
  pkg/ctl/get/nodegroup.go
Labels: kind/bug

#2725 Support arm/arm64 binaries as part of release
  .gitignore
  .goreleaser.yml
  README.md
Labels: kind/feature

#2732 Handle aws-node 1.7 initContainer properly
  pkg/addons/default/aws_node.go
  pkg/addons/default/aws_node_test.go
  pkg/addons/image.go
Labels: kind/bug

#2726 Add support for powershell completion
  pkg/ctl/completion/completion.go
  pkg/ctl/completion/completion_test.go
  userdocs/src/introduction.md
Labels: kind/feature

#2738 Ask explicitly for config in issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/request-for-help.md
Labels: skip-release-notes

#2742 Fix integration test failure to parse eksctl version
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/managed/service.go
  pkg/version/parse.go
  pkg/version/parse_test.go
Labels: area/testing, skip-release-notes, technical debt

#2744 Add option to not rollback failed stacks
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/manager/api.go
  pkg/ctl/cmdutils/cmdutils.go
  pkg/eks/api.go
  pkg/testutils/mockprovider/mock_provider.go
  userdocs/src/usage/troubleshooting.md
Labels: area/general-cli, kind/improvement

#2748 Add support for force-ugprading managed nodegroups
  pkg/ctl/upgrade/nodegroup.go
  pkg/managed/service.go
Labels: area/nodegroup, kind/feature

#2750 Don't error if explicit aws-node given with withOIDC
  pkg/apis/eksctl.io/v1alpha5/defaults.go
Labels: area/aws-iam, kind/bug

#2751 Don't error if explicit aws-node given with withOIDC
  docs/release_notes/0.30.0.md
  pkg/apis/eksctl.io/v1alpha5/defaults.go
Labels: skip-release-notes

#2718 print formatted output for utils describe-stacks
  pkg/ctl/utils/describe_stacks.go
Labels: kind/feature

#2753 Run fargate integration tests in us-west-2
  integration/tests/fargate/fargate_test.go
Labels: area/testing, skip-release-notes, technical debt

#2754 Add flag to enable Simple System Manager (SSM) for easy SSH access
  .gitignore
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/testdata/launch_template/ssh_enabled.json
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/nodegroup_test.go
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/install-ssm.al2.sh
  pkg/nodebootstrap/userdata_al2.go
  userdocs/src/introduction.md
Labels: area/managed-nodegroup, area/nodegroup, kind/feature

#2760 Enforce control plane readiness before SA creation
  pkg/cfn/manager/create_tasks.go
  pkg/eks/tasks.go
Labels: kind/bug

#2759 Ensure node drain timeout is respected
  pkg/drain/nodegroup.go
Labels: area/nodegroup, kind/bug

#2762 Improving handling of failed nodegroups
  pkg/cfn/manager/nodegroup.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/get/nodegroup.go
Labels: area/nodegroup, kind/improvement

#2767 Try out dependabot
  .github/dependabot.yml
Labels: skip-release-notes

#2769 Fix ALB ingress controller docs link
  userdocs/src/usage/faq.md
Labels: autosquash, kind/docs, skip-release-notes

#2758 Add Ubuntu 20.04 Image Support
  pkg/ami/auto_resolver.go
  pkg/ami/auto_resolver_test.go
  pkg/ami/ssm_resolver.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/api_test.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/nodebootstrap/userdata.go
  pkg/nodebootstrap/userdata_ubuntu.go
  userdocs/src/usage/custom-ami-support.md
Labels: kind/feature

#2771 Add release notes for 0.31.0
  docs/release_notes/0.31.0.md
Labels: kind/docs, skip-release-notes

#2772 Don't thank @aclevername in releases
  .github/release-drafter.yml
Labels: area/build-and-release, skip-release-notes

#2775 Allow creation of iamserviceaccounts on clusters not created through eksctl
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/nodegroup.go
Labels: area/aws-iam, kind/improvement

#2778 Handle create nodegroup and withOIDC for clusters without aws-node SA
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/create/nodegroup.go
  pkg/eks/nodegroup.go
Labels: autosquash, kind/bug

#2781 Update release notes for 0.31.0-rc.1
  docs/release_notes/0.31.0.md
Labels: skip-release-notes

#2784 Enforce control plane readiness before checking core-dns with fargate
  pkg/eks/fargate.go
Labels: skip-release-notes

#2783 Add missing action to autoscaler example policy
  examples/13-iamserviceaccounts.yaml
  userdocs/src/usage/iamserviceaccounts.md
Labels: autosquash, kind/docs, skip-release-notes

#2766 Refactor drain logic
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
  pkg/drain/drain_suite_test.go
  pkg/drain/evictor/evictor.go
  pkg/drain/evictor/pod.go
  pkg/drain/export_test.go
  pkg/drain/fakes/fake_evictor.go
  pkg/drain/nodegroup.go
  pkg/drain/nodegroup_test.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/nodegroup.go
Labels: kind/improvement, technical debt
