Repository eksctl-io/eksctl, pull requests merged in 2020-08, with the labels that each got.

#2494 Add enum to schema for CloudWatch logging and additionalEndpointServices
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/cloudwatch.go
  pkg/apis/eksctl.io/v1alpha5/endpoint_service.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/schema/definition/comment.go
  pkg/schema/definition/enum.go
  pkg/schema/schema_test.go
  pkg/schema/test/test.go
  userdocs/src/usage/schema.js
Labels: kind/docs, skip-release-notes

#2502 Merge release-0.25 to master
  .circleci/config.yml
  docs/release_notes/0.25.0.md
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
Labels: skip-release-notes

#2503 Move hack/* to build/updates
  build/updates/dump-coredns-manifests.sh
  build/updates/dump-default-addons.sh
Labels: area/build-and-release, skip-release-notes

#2504 Increase integration test create timeout to 30m
  integration/tests/params.go
Labels: area/build-and-release, skip-release-notes

#2505 Allow `version: auto` in the config file when creating a cluster
  pkg/ctl/create/cluster.go
  pkg/ctl/upgrade/cluster_test.go
Labels: kind/improvement, technical debt

#2508 Don't write build-image iidfile
  Makefile.docker
Labels: area/build-and-release, skip-release-notes

#2507 Don't create .license-header file
  .gitignore
  Makefile
  build/scripts/update-codegen.sh
Labels: area/build-and-release, skip-release-notes

#2506 Move Dockerfile to /build/docker
  Makefile.docker
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  build/scripts/build-image-manifest.sh
Labels: area/build-and-release, skip-release-notes

#2512 Add release notes for 0.26.0
  docs/release_notes/0.26.0.md
Labels: kind/docs, skip-release-notes

#2511 Build eksctl docker image on release (don't yet push)
  .dockerignore
  Dockerfile
  Makefile.common
  Makefile.docker
  Makefile.docs
  build/scripts/do-release-candidate.sh
  build/scripts/do-release.sh
  build/scripts/eksctl-image-builder.sh
  docs/proposal-006-build-improvements.md
Labels: area/build-and-release, skip-release-notes

#2514 Handle coredns annotations map being nil
  pkg/addons/default/coredns.go
Labels: kind/bug

#2516 Build eksctl docker image nightly
  .circleci/config.yml
Labels: area/build-and-release, skip-release-notes

#2517 Pass image tag to eksctl-image in master build
  .circleci/config.yml
Labels: area/build-and-release, skip-release-notes

#2519 Generate OIDC test TLS keys on the fly
  .requirements
  Dockerfile
  Makefile.docker
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/iam/oidc/api_test.go
  pkg/iam/oidc/testdata/ca-key.pem
  pkg/iam/oidc/testdata/ca.csr
  pkg/iam/oidc/testdata/ca.pem
  pkg/iam/oidc/testdata/test-server-key.pem
  pkg/iam/oidc/testdata/test-server.csr
  pkg/iam/oidc/testdata/test-server.pem
Labels: area/testing, skip-release-notes, technical debt

#2520 Properly pass options to circleci docker-run cmd
  .circleci/config.yml
Labels: area/build-and-release, skip-release-notes

#2522 Fix circleci cmd docker-run trailing newline
  .circleci/config.yml
Labels: area/build-and-release, skip-release-notes

#2526 Fix formatting for private cluster docs
  userdocs/src/usage/eks-private-cluster.md
Labels: kind/docs, skip-release-notes

#2523 Use docker-run job everywhere in circleci
  .circleci/config.yml
Labels: area/build-and-release, skip-release-notes

#2524 Set ENTRYPOINT in Dockerfile
  Dockerfile
  pkg/iam/oidc/api_test.go
Labels: area/build-and-release, skip-release-notes

#2528 Handle delete cluster with failed stack
  pkg/ctl/delete/cluster.go
  pkg/eks/eks.go
  pkg/eks/eks_test.go
Labels: kind/bug

#2530 Remove redundant `nodeGroupName` field
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/vpc.go
Labels: area/nodegroup, kind/improvement

#2525 Push docker images on release
  .circleci/config.yml
  build/scripts/do-release-candidate.sh
  build/scripts/do-release.sh
Labels: area/build-and-release, skip-release-notes

#2535 Add support for ARM
  pkg/addons/default/addons.go
  pkg/addons/default/assets.go
  pkg/addons/default/assets/aws-node.yaml
  pkg/addons/default/assets/coredns-1.15.json
  pkg/addons/default/assets/coredns-1.16.json
  pkg/addons/default/assets/coredns-1.17.json
  pkg/addons/default/aws_node.go
  pkg/addons/default/aws_node_test.go
  pkg/addons/default/coredns.go
  pkg/addons/default/coredns_test.go
  pkg/addons/default/kube_proxy.go
  pkg/addons/default/kube_proxy_test.go
  pkg/addons/image.go
  pkg/ami/api.go
  pkg/ami/auto_resolver.go
  pkg/ami/ssm_resolver.go
  pkg/apis/eksctl.io/v1alpha5/nodegroups.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/ctl/cmdutils/cluster.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/eks/tasks.go
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/10-eksclt.al2.conf
  pkg/nodebootstrap/assets/bootstrap.al2.sh
  pkg/nodebootstrap/assets/bootstrap.ubuntu.sh
  pkg/utils/utils.go
  userdocs/mkdocs.yml
  userdocs/src/usage/arm-support.md
Labels: kind/feature

#2540 Respect --ssh-access flag
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/cluster_test.go
Labels: kind/bug

#2529 Update with number parsing goformation improvement
  go.mod
  go.sum
Labels: skip-release-notes, technical debt

#2544 Add support for Launch Templates, custom AMI and more features for Managed Nodegroups
  examples/15-managed-nodes.yaml
  examples/22-managed-nodes-launch-template.yaml
  go.mod
  go.sum
  pkg/ami/ami_test.go
  pkg/ami/api.go
  pkg/ami/ssm_resolver.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/launch_template_fetcher.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/custom_ami.json
  pkg/cfn/builder/testdata/launch_template/launch_template.json
  pkg/cfn/builder/testdata/launch_template/launch_template_custom_ami.json
  pkg/cfn/builder/testdata/launch_template/ssh_enabled.json
  pkg/cfn/builder/testdata/launch_template/standard.json
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/outputs/api.go
  pkg/ctl/cmdutils/cluster.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/eks/api.go
  pkg/eks/api_test.go
  pkg/eks/nodegroup_service.go
  pkg/managed/service.go
  pkg/utils/kubeconfig/kubeconfig_test.go
  userdocs/src/usage/eks-managed-nodes.md
  userdocs/src/usage/launch-template-support.md
Labels: area/managed-nodegroup, kind/feature

#2552 Update release notes for 0.26
  docs/release_notes/0.26.0.md
Labels: skip-release-notes

#2487 Added ASG SuspendProcesses support
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/nodegroup.go
Labels: kind/feature

#2555 Merge branch release-0.26 into master
  docs/release_notes/0.26.0.md
  examples/15-managed-nodes.yaml
  examples/22-managed-nodes-launch-template.yaml
  go.mod
  go.sum
  pkg/ami/ami_test.go
  pkg/ami/api.go
  pkg/ami/ssm_resolver.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/launch_template_fetcher.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/custom_ami.json
  pkg/cfn/builder/testdata/launch_template/launch_template.json
  pkg/cfn/builder/testdata/launch_template/launch_template_custom_ami.json
  pkg/cfn/builder/testdata/launch_template/ssh_enabled.json
  pkg/cfn/builder/testdata/launch_template/standard.json
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/outputs/api.go
  pkg/ctl/cmdutils/cluster.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/eks/api.go
  pkg/eks/api_test.go
  pkg/eks/nodegroup_service.go
  pkg/managed/service.go
  pkg/utils/kubeconfig/kubeconfig_test.go
  userdocs/mkdocs.yml
  userdocs/src/usage/eks-managed-nodes.md
  userdocs/src/usage/launch-template-support.md
Labels: skip-release-notes

#2549 Add support for mapAccounts to `create iamidentitymapping`
  pkg/ctl/create/iamidentitymapping.go
Labels: area/aws-iam, kind/feature

#2562 Don't add empty ASGSuspendProcesses slice to CFN
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/nodegroup.go
Labels: skip-release-notes

#2561 Use fluxcd/go-git-providers
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/gitops/deploykey/deploykey.go
  pkg/gitops/flux/installer.go
  pkg/gitops/gitops.go
  pkg/gitops/url_test.go
Labels: automerge, skip-release-notes, technical debt

#2572 Fix upgrading nodegroups with old template format
  pkg/cfn/manager/nodegroup.go
  pkg/managed/service.go
Labels: area/managed-nodegroup, autosquash, kind/bug

#2571 Add missing permission required for ELB
  pkg/cfn/builder/iam.go
Labels: kind/bug

#2575 Improve automerge workflow
  .github/workflows/auto-merge.yaml
Labels: skip-release-notes

#2576 Use partition prefix for VPC endpoint services
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/vpc_endpoint.go
Labels: autosquash, kind/bug

#2577 Fix route validation for subnets with an explicit main route table association
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_endpoint_test.go
Labels: kind/bug

#2578 Add workflow to update maxpods
  .github/workflows/update-maxpods.yaml
Labels: area/build-and-release, skip-release-notes

#2581 Fix GetEksctlVersion for git commit versions
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/version/version.go
Labels: area/managed-nodegroup, skip-release-notes

#2582 Add release notes for 0.27.0
  docs/release_notes/0.27.0.md
Labels: skip-release-notes

#2550 Add docker image to eksctl.io and README.md
  README.md
  userdocs/src/introduction.md
Labels: kind/docs, skip-release-notes

#2583 Use more descriptive names for Test functions
  integration/matchers/json_test.go
  integration/runner/runner_suite_test.go
  integration/tests/backwards_compat/backwards_compatibility_test.go
  integration/tests/before_active/createdeletebeforeactive_test.go
  integration/tests/cluster_api/cluster_api_endpoints_test.go
  integration/tests/crud/creategetdelete_test.go
  integration/tests/fargate/fargate_test.go
  integration/tests/inferentia/inferentia_test.go
  integration/tests/managed/managed_nodegroup_test.go
  integration/tests/quickstart_profiles/quickstart_profiles_test.go
  integration/tests/quickstart_profiles_gen/quickstart_profiles_gen_test.go
  pkg/addons/default/default_suite_test.go
  pkg/ami/ami_suite_test.go
  pkg/apis/eksctl.io/v1alpha5/api_suite_test.go
  pkg/authconfigmap/authconfigmap_suite_test.go
  pkg/az/az_suite_test.go
  pkg/cfn/builder/api_suite_test.go
  pkg/cfn/manager/manager_suite_test.go
  pkg/cfn/outputs/api_suite_test.go
  pkg/cfn/template/template_suite_test.go
  pkg/cloudconfig/cloudconfig_suite_test.go
  pkg/ctl/cmdutils/cmdutils_suite_test.go
  pkg/ctl/cmdutils/filter/filter_suite_test.go
  pkg/ctl/completion/completion_suite_test.go
  pkg/ctl/create/create_suite_test.go
  pkg/ctl/delete/delete_suite_test.go
  pkg/ctl/drain/drain_suite_test.go
  pkg/ctl/enable/enable_suite_test.go
  pkg/ctl/generate/generate_suite_test.go
  pkg/ctl/get/get_suite_test.go
  pkg/ctl/scale/scale_suite_test.go
  pkg/ctl/set/set_suite_test.go
  pkg/ctl/unset/unset_suite_test.go
  pkg/ctl/update/update_suite_test.go
  pkg/ctl/upgrade/upgrade_suite_test.go
  pkg/ctl/utils/utils_suite_test.go
  pkg/eks/eks_suite_test.go
  pkg/fargate/coredns/coredns_test.go
  pkg/fargate/suite_test.go
  pkg/git/git_suite_test.go
  pkg/gitops/flux/flux_suite_test.go
  pkg/gitops/gitops_suite_test.go
  pkg/iam/iam_suite_test.go
  pkg/iam/oidc/oidc_suite_test.go
  pkg/kubernetes/kubernetes_suite_test.go
  pkg/nodebootstrap/nodebootstrap_suite_test.go
  pkg/printers/printers_suite_test.go
  pkg/schema/definition/suite_test.go
  pkg/schema/suite_test.go
  pkg/ssh/client/ssh_suite_test.go
  pkg/utils/dir/dir_test.go
  pkg/utils/kubeconfig/kubeconfig_suite_test.go
  pkg/utils/names/names_test.go
  pkg/utils/retry/suite_test.go
  pkg/utils/strings/strings_test.go
  pkg/utils/utils_suite_test.go
  pkg/version/generate/generate_suite_test.go
  pkg/version/version_suite_test.go
  pkg/vpc/vpc_suite_test.go
Labels: area/testing, autosquash, skip-release-notes, technical debt

#2584 Drop deprecated switch in api integration tests
  integration/tests/cluster_api/cluster_api_endpoints_test.go
Labels: area/testing, autosquash, skip-release-notes, technical debt

#2587 Use proper commit range in release-merge workflow check
  .github/workflows/release-merge.yaml
Labels: area/build-and-release, autosquash, skip-release-notes

#2590 Add job to automatically update aws-node
  .github/workflows/update-generated.yaml
  .github/workflows/update-maxpods.yaml
Labels: area/build-and-release, skip-release-notes

#2594 Regenerate bytes with update-aws-node
  Makefile
Labels: area/build-and-release, skip-release-notes

#2601 Simplify targets in Makefile
  Makefile
Labels: area/build-and-release, skip-release-notes
