Repository eksctl-io/eksctl, pull requests merged in 2020-04, with the labels that each got.

#2009 Improve help of update cluster command
  pkg/ctl/update/cluster.go
Labels: area/docs, kind/improvement

#2007 Fix code generation path issues
  Makefile
  tools/update-codegen.sh
Labels: kind/bug

#1770 Add documentation about alternative ways to delete clusters
  site/content/usage/01-creating-and-managing-clusters.md
  site/content/usage/21-troubleshooting.md
Labels: kind/docs, kind/improvement

#2002 New default IP mapping settings for public subnets
  integration/tests/backwards_compat/backwards_compatibility_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/compat.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/ctl/utils/utils.go
  pkg/vpc/vpc.go
  site/content/usage/06-vpc-networking.md
Labels: area/aws-vpc, kind/improvement

#2012 Fix deleting security groups for ELBs still being deleted
  pkg/cfn/manager/api.go
  pkg/elb/cleanup.go
Labels: area/deletions

#2034 Document new priority labels
  CONTRIBUTING.md
Labels: area/docs, kind/improvement

#2036 Add support for AWS EC2 instances of type inf1
  pkg/nodebootstrap/maxpods.go
Labels: area/build-and-release, kind/breaking, version/0.18.0

#2035 Update OWNERS file
  OWNERS
Labels: area/docs, kind/improvement

#1990 Don't alter addons in plan mode
  pkg/kubernetes/client.go
Labels: area/add-ons, area/upgrades, version/0.18.0

#2017 Update Flux and Helm Operator
  go.mod
  go.sum
  integration/matchers/flux.go
Labels: area/gitops, version/0.18.0

#1791 Support private networking for managed nodegroups
  examples/15-managed-nodes.yaml
  integration/tests/managed/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/create_test.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/nodegroup_test.go
  site/content/usage/20-schema.md
Labels: area/nodegroup, kind/feature, version/0.18.0

#2056 Docs: update the hyper link for latest release in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area/docs, kind/docs, kind/improvement

#2062 Add link checking
  .github/workflows/check-links.yaml
  .github/workflows/markdown-link-check-config.json
Labels: area/docs

#2044 Correct error message for create/delete/drain nodegroup
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/create/nodegroup_test.go
  pkg/ctl/delete/delete_suite_test.go
  pkg/ctl/delete/delete_test.go
  pkg/ctl/delete/fargate_test.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/delete/nodegroup_test.go
  pkg/ctl/drain/drain_suite_test.go
  pkg/ctl/drain/drain_test.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/drain/nodegroup_test.go
Labels: area/general-cli, kind/improvement

#2064 Make link checking less noisy
  .github/workflows/check-links.yaml
Labels: area/docs

#2016 Add IAM permission route53:ListTagsForResource for external dns addon
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam_helper.go
Labels: area/aws-iam, kind/improvement

#2000 Fix crash when iam:WithOIDC is not present in the config file
  humans.txt
  pkg/ctl/cmdutils/configfile.go
Labels: kind/bug

#2039 Separate downloaded files from generated ones in Makefile
  Makefile
  pkg/addons/default/aws_node_generate.go
  pkg/addons/default/generate.go
  pkg/nodebootstrap/maxpods_generate.go
  pkg/nodebootstrap/userdata.go
  tools/brew/update_formula.go
Labels: area/build-and-release, kind/improvement

#2078 Switch to `aws eks get-token` as the authenticator for Amazon Linux 2
  pkg/cfn/builder/api_test.go
  pkg/nodebootstrap/userdata.go
  pkg/nodebootstrap/userdata_al2.go
  pkg/nodebootstrap/userdata_ubuntu.go
  pkg/utils/kubeconfig/kubeconfig.go
Labels: area/nodegroup, kind/improvement

#1994 IAM Service Account fixes
  go.mod
  go.sum
  humans.txt
  pkg/ctl/cmdutils/iamserviceaccount_filter.go
  pkg/ctl/create/cluster.go
  pkg/eks/tasks.go
  pkg/kubernetes/namespace.go
Labels: kind/bug, priority/important-soon

#2079 Use only Service Linked Role for EKS clusters
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
  pkg/cfn/template/testdata/cluster-example-1.json
  pkg/cfn/template/testdata/cluster-example-2.json
Labels: kind/improvement

#2094 [release-0.18] Add name argument support for create iamserviceaccount cli
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/create/iamserviceaccount_test.go
Labels: area/general-cli, kind/bug, priority/critical

#2097 Update aws-sdk-go version tagging in Makefile
  Makefile
Labels: area/build-and-release, kind/bug

#2070 Remove humans.txt file
  .github/PULL_REQUEST_TEMPLATE.md
  humans.txt
Labels: kind/docs, kind/improvement

#2102 /intro/ was /introduction/ before - move back
  README.md
  userdocs/mkdocs.yml
  userdocs/requirements.txt
  userdocs/src/README.md
  userdocs/src/gitops-quickstart.md
  userdocs/src/introduction.md
Labels: area/docs, kind/docs

#2055 support metrics collection in scaling config for unmanaged node groups
  examples/05-advanced-nodegroups.yaml
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/nodegroup.go
  userdocs/src/usage/eks-managed-nodes.md
  userdocs/src/usage/managing-nodegroups.md
  userdocs/src/usage/schema.md
Labels: area/nodegroup, kind/feature

#2071 Allow private clusters to be created
  examples/02-custom-vpc-cidr-no-nodes.yaml
  integration/tests/cluster_api/cluster_api_endpoints_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
  userdocs/src/usage/vpc-networking.md
Labels: area/aws-vpc, kind/improvement

#2111 Fix Windows build
  go.mod
  go.sum
Labels: kind/bug

#2110 Validate `secretsEncryption.keyARN` for nil
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/bug
