Repository eksctl-io/eksctl, pull requests merged in 2020-11, with the labels that each got.

#2537 Refactor nodegroup creation
  pkg/actions/create/nodegroup.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/nodegroup_test.go
  pkg/ctl/create/utils.go
Labels: skip-release-notes, technical debt

#2779 Get clusters states if a cluster was eksctl created
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/get/cluster.go
  pkg/eks/eks.go
  pkg/eks/eks_test.go
  pkg/eks/testdata/singlecluster_deleting.golden
Labels: area/general-cli, kind/improvement

#2791 Use role names instead of ARN when creating instance profiles
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
Labels: area/nodegroup, kind/bug

#2796 Increase cluster upgrade timeout to 50 minutes
  docs/release_notes/0.31.0.md
  integration/tests/params.go
  integration/tests/update/update_cluster_test.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/nodegroup.go
Labels: skip-release-notes

#2795 Don't configure an SSH SecurityGroup when SSH.Allow is false
  examples/07-ssh-keys.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/testdata/launch_template/ssh_disabled.json
Labels: area/managed-nodegroup, kind/bug

#2802 Upgrade flux, helm-operator and go-git-providers
  go.mod
  go.sum
Labels: kind/improvement

#2788 Add information on using eksctl via HTTP proxy servers with private clusters
  userdocs/src/usage/eks-private-cluster.md
Labels: autosquash, kind/docs, skip-release-notes

#2702 Support passing additional arguments to flux and helm operator
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/enable/repo_test.go
  pkg/gitops/flux/installer.go
  pkg/gitops/flux/installer_test.go
  userdocs/src/usage/gitops.md
Labels: kind/feature

#2803 Remove deprecated command from integration tests
  integration/tests/managed/managed_nodegroup_test.go
  integration/tests/params.go
Labels: area/testing, skip-release-notes

#2804 Support more than 4 azs
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: area/aws-vpc, kind/feature

#2807 Automatically install nvidia device plugin for GPU instances
  pkg/actions/create/nodegroup.go
  pkg/addons/assets.go
  pkg/addons/assets/nvidia-device-plugin.yaml
  pkg/addons/device_plugin.go
  pkg/addons/neuron_device_plugin.go
  pkg/ctl/cmdutils/create_cluster.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/eks/tasks.go
Labels: kind/feature

#2793 Add more flexible subnet support, specifying subnets for nodegroup
  examples/24-nodegroup-subnets.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/vpc_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/schema/definition/comment.go
  pkg/schema/definition/comment_test.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: area/aws-vpc, kind/feature

#2814 Select all subnets of an availability zone
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: area/aws-vpc, skip-release-notes

#2816 Fix null pointer exception with doImportSubnet
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/vpc_test.go
Labels: kind/bug, skip-release-notes

#2817 Update to newer goformation fork
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/cfn/outputs/api.go
Labels: area/build-and-release, skip-release-notes

#2819 Update goformation to fix CFN error
  go.mod
  go.sum
  pkg/cfn/outputs/api.go
Labels: area/build-and-release, kind/bug, skip-release-notes

#2823 Don't check exact helm-operator version in integration test
  integration/matchers/flux.go
Labels: area/testing, autosquash, skip-release-notes, technical debt

#2813 Upgrade spf13/cobra to v1.1.1 to fix zsh completion issue
  go.mod
  go.sum
  pkg/ctl/completion/completion_test.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/create_test.go
  pkg/ctl/create/fargate_test.go
  pkg/ctl/create/iamserviceaccount_test.go
  pkg/ctl/delete/delete_test.go
  pkg/ctl/delete/fargate_test.go
  pkg/ctl/delete/iamserviceaccount_test.go
  pkg/ctl/delete/nodegroup_test.go
  pkg/ctl/drain/drain_test.go
  pkg/ctl/drain/nodegroup_test.go
  pkg/ctl/enable/enable_test.go
  pkg/ctl/generate/generate_test.go
  pkg/ctl/get/cluster_test.go
  pkg/ctl/get/fargate_test.go
  pkg/ctl/get/get_test.go
  pkg/ctl/get/iamidentitymapping_test.go
  pkg/ctl/get/iamserviceaccount_test.go
  pkg/ctl/get/labels_test.go
  pkg/ctl/get/nodegroup_test.go
  pkg/ctl/scale/nodegroup_test.go
  pkg/ctl/scale/scale_test.go
  pkg/ctl/set/set_test.go
  pkg/ctl/unset/unset_test.go
  pkg/ctl/update/update_test.go
  pkg/ctl/upgrade/upgrade_test.go
  pkg/ctl/utils/utils_test.go
Labels: autosquash, kind/bug

#2825 Don't check exact flux version in integration test
  integration/matchers/flux.go
Labels: area/testing, skip-release-notes, technical debt

#2826 Mention all necessary subnet tags in VPC docs
  userdocs/src/usage/vpc-networking.md
Labels: kind/docs, skip-release-notes

#2833 Do not thank dependabot, fix regex
  .github/release-drafter.yml
Labels: skip-release-notes

#2832 Add release notes for 0.32
  docs/release_notes/0.32.0.md
Labels: skip-release-notes

#2843 Respect volume size for Bottlerocket nodegroups
  pkg/ami/ami_test.go
  pkg/ami/api.go
Labels: area/nodegroup, kind/bug

#2844 Update goreleaser and go-bindata
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/addons/assets.go
  pkg/addons/default/assets.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/nodebootstrap/assets.go
Labels: skip-release-notes

#2852 Skip upgrading nodegroup if SSM release version is older
  pkg/managed/managed_suite_test.go
  pkg/managed/release_version_test.go
  pkg/managed/service.go
Labels: kind/bug

#2856 Added support for the 't4g' instances.
  pkg/nodebootstrap/reserved_data.go
  pkg/utils/utils.go
  userdocs/src/usage/arm-support.md
Labels: kind/feature

#2857 Make EKS 1.18 the default
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/api_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/introduction.md
Labels: kind/feature

#2859 Update release notes for 0.32
  docs/release_notes/0.32.0.md
Labels: kind/docs, skip-release-notes

#2870 Update json-patch to v5
  go.mod
  go.sum
  pkg/kubernetes/client.go
Labels: autosquash, skip-release-notes

#2871 Do not fail Fargate profile creation if it already exists
  .github/workflows/update-generated.yaml
  .requirements
  Dockerfile
  Makefile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/ctl/create/fargate.go
  pkg/drain/fakes/fake_evictor.go
  pkg/drain/nodegroup.go
  pkg/eks/fakes/fargate_client.go
  pkg/eks/fargate.go
  pkg/eks/fargate_test.go
  pkg/eks/tasks.go
  tools.go
Labels: area/fargate, kind/improvement

#2873 Print empty JSON array when `get clusters -o json` returns nothing
  pkg/eks/eks.go
  pkg/eks/eks_test.go
Labels: autosquash, kind/improvement
