Repository eksctl-io/eksctl, pull requests merged in 2020-09, with the labels that each got.

#2606 Recognize ARM instance types for Bottlerocket parameters
  pkg/ami/ssm_resolver.go
Labels: kind/bug

#2597 Fix the policy "AmazonEC2FullAccess" on minimum-iam-policies.md
  userdocs/src/usage/minimum-iam-policies.md
Labels: autosquash, kind/docs, skip-release-notes

#2605 Use eksctl-build and cache in update workflow
  .github/workflows/update-generated.yaml
  Makefile.docker
Labels: area/build-and-release, autosquash, skip-release-notes

#2608 Remove default values from Bottlerocket example config
  examples/20-bottlerocket.yaml
  pkg/apis/eksctl.io/v1alpha5/defaults.go
Labels: autosquash, kind/improvement, skip-release-notes

#2616 Support for managed VPC controller
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
Labels: kind/improvement

#2613 Add support for Windows 2004 Server AMI
  pkg/ami/auto_resolver.go
  pkg/ami/ssm_resolver.go
  pkg/ami/static_resolver_ami.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  userdocs/src/usage/custom-ami-support.md
Labels: area/nodegroup, kind/feature

#2611 Add documentation about the bootstrapping in AL2
  docs/current-001-node_bootstrap.md
Labels: area/docs, kind/docs, skip-release-notes

#2620 Improve slack notifications
  .circleci/config.yml
Labels: area/build-and-release, skip-release-notes

#2615 Add life-cycle labels to nodes
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/bootstrap.al2.sh
  pkg/nodebootstrap/assets/bootstrap.ubuntu.sh
Labels: area/nodegroup, autosquash, kind/improvement

#2612 Create aws-node SA if WithOIDC
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/eks/tasks.go
Labels: area/aws-iam, area/managed-nodegroup, area/nodegroup, autosquash, kind/feature

#2619 Fix make update-ami command
  pkg/ami/api.go
  pkg/ami/static_resolver_ami.go
  pkg/ami/static_resolver_ami_generate.go
Labels: area/build-and-release, automerge, skip-release-notes

#2624 Fix lifecycle node labels not set
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/bootstrap.al2.sh
  pkg/nodebootstrap/assets/bootstrap.ubuntu.sh
  userdocs/src/usage/spot-instances.md
Labels: area/nodegroup, kind/bug, skip-release-notes

#2626 Add integration tests for updating addons
  integration/tests/update/update_cluster_test.go
Labels: area/testing, skip-release-notes, technical debt

#2630 Small fix to the VPC docs
  userdocs/src/usage/vpc-networking.md
Labels: autosquash, kind/docs, skip-release-notes

#2634 Add option to block IMDS from pods
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/nodegroup.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
Labels: kind/feature

#2637 Add security page to docs
  userdocs/mkdocs.yml
  userdocs/src/usage/security.md
Labels: kind/docs, skip-release-notes

#2638 Add release notes for 0.28.0
  docs/release_notes/0.28.0.md
Labels: kind/docs, skip-release-notes

#2645 Improve docs for using existing VPCs
  userdocs/src/usage/vpc-networking.md
Labels: kind/docs, skip-release-notes

#2636 Improve flags help for create cluster command
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
Labels: kind/docs, skip-release-notes

#2646 Add design guidelines
  docs/guidelines/design-conventions.md
Labels: kind/docs, skip-release-notes

#2643 Add CLI options for WithOIDC and DisablePodIMDS
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/api_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
Labels: autosquash, kind/improvement, skip-release-notes

#2644 Wait for new server version in integration test
  integration/tests/managed/managed_nodegroup_test.go
Labels: autosquash, skip-release-notes

#2632 Add an annotations field to the eksctl config file
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
Labels: kind/improvement

#2649 Validate disable IMDS options with managed ng and launch template
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
Labels: autosquash, skip-release-notes

#2651 Add WithOIDC and DisablePodIMDS CLI opts, add disable IMDS validation
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/api_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
Labels: automerge, skip-release-notes

#2648 Add placement group support for nodegroups
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/testdata/launch_template/placement.json
Labels: kind/feature

#2647 Improve docs on IAM policies
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/docs, skip-release-notes

#2640 Add example for kubeflow spot instance cluster config
  examples/23-kubeflow-spot-instance.yaml
  pkg/ctl/cmdutils/configfile_test.go
Labels: kind/docs, skip-release-notes

#2656 Use Eventually in upgrade integration tests
  integration/tests/update/update_cluster_test.go
Labels: area/testing, skip-release-notes, technical debt

#2652 Go 1.15 upgrade
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
Labels: kind/improvement

#2560 fix the wrong message printed about how to enable logging for the cluster...
  pkg/eks/tasks.go
  userdocs/src/usage/fargate-support.md
Labels: area/general-cli, kind/docs, skip-release-notes

#2658 Use generated nodegroup template types
  go.mod
  go.sum
  pkg/cfn/builder/managed_nodegroup.go
  pkg/managed/service.go
Labels: skip-release-notes

#2546 Add support for setting Service CIDR range
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/cluster.go
  pkg/ctl/create/cluster.go
Labels: kind/feature

#2662 Respect partition when referring to CNI SA policy
  pkg/eks/tasks.go
Labels: area/aws-iam, kind/bug, skip-release-notes

#2663 Respect partition when referring to CNI SA policy
  docs/release_notes/0.28.0.md
  pkg/eks/tasks.go
Labels: area/aws-iam, kind/bug, skip-release-notes

#2664 Update release notes for 0.28.1
  docs/release_notes/0.28.0.md
  docs/release_notes/0.28.1.md
Labels: skip-release-notes

#2667 Don't require addons when checking for updates
  pkg/addons/default/aws_node.go
  pkg/addons/default/coredns.go
  pkg/addons/default/kube_proxy.go
Labels: area/managed-nodegroup, area/nodegroup, kind/bug

#2671 Fix `delete iamserviceaccount` and withOIDC
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/ctl/cmdutils/configfile.go
  pkg/eks/tasks.go
Labels: area/aws-iam, kind/bug

#2660 Respect the pod termination grace period when draining a nodegroup
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/delete/nodegroup_test.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/drain/nodegroup_test.go
  pkg/drain/drain.go
  pkg/drain/nodegroup.go
Labels: kind/improvement

#2672 Update aws-node to 1.7
  integration/tests/update/update_cluster_test.go
  pkg/addons/default/assets.go
  pkg/addons/default/assets/aws-node.yaml
  pkg/addons/default/assets_test.go
  pkg/addons/default/aws_node.go
  pkg/addons/default/aws_node_generate.go
  pkg/addons/default/aws_node_test.go
Labels: kind/improvement

#2674 Be less strict with aws-node version checking
  pkg/addons/default/addons.go
  pkg/addons/default/aws_node.go
  pkg/addons/default/aws_node_test.go
  pkg/addons/default/testdata/sample-1.16-eksbuild.1.json
  pkg/addons/default/testdata/sample-1.16-v1.7.3.json
  pkg/ctl/create/nodegroup.go
Labels: skip-release-notes

#2676 Add release notes for 0.29.0
  docs/release_notes/0.29.0.md
Labels: skip-release-notes

#2677 Add missing notes in 0.29.0 release notes
  docs/release_notes/0.29.0.md
Labels: skip-release-notes

#2683 Set cluster DNS in bootstrap if ClusterIP range specified
  pkg/nodebootstrap/userdata.go
Labels: area/managed-nodegroup, area/nodegroup, kind/bug

#2681 Fix release-merge workflow issues
  .github/workflows/release-merge.yaml
Labels: area/build-and-release, skip-release-notes
