Repository eksctl-io/eksctl, pull requests merged in 2020-03, with the labels that each got.

#1875 Fix null pointer dereference in cluster access validation
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/test_data/cluster-with-vpc-private-access.yaml
  pkg/ctl/cmdutils/test_data/cluster-with-vpc.yaml
  pkg/ctl/cmdutils/test_data/cluster-without-vpc-private-access.yaml
  pkg/ctl/cmdutils/test_data/cluster-without-vpc.yaml
Labels: version/0.15.0

#1855 Fix null pointer dereference in cluster access validation
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/test_data/cluster-with-vpc-private-access.yaml
  pkg/ctl/cmdutils/test_data/cluster-with-vpc.yaml
  pkg/ctl/cmdutils/test_data/cluster-without-vpc-private-access.yaml
  pkg/ctl/cmdutils/test_data/cluster-without-vpc.yaml
Labels: kind/bug

#1877 [IRSA] Set default audience based on AWS partition
  pkg/addons/default/aws_node.go
  pkg/cfn/builder/iam_test.go
  pkg/eks/eks.go
  pkg/iam/oidc/api.go
  pkg/iam/oidc/api_test.go
Labels: kind/improvement

#1719 Fix (plan) output when updating k8s addons
  pkg/addons/default/aws_node.go
  pkg/addons/default/aws_node_test.go
  pkg/addons/default/coredns.go
  pkg/addons/default/coredns_test.go
  pkg/addons/default/helpers.go
  pkg/addons/image.go
Labels: kind/bug

#1897 Add support for KMS encryption provider
  examples/19-kms-cluster.yaml
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/cluster.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/create/cluster.go
  pkg/eks/eks_test.go
  pkg/eks/nodegroup.go
  pkg/utils/kubectl/kubectl.go
  site/content/usage/20-schema.md
Labels: kind/feature

#1900 Run integration tests with tini as PID1 and make as a child process for better signals handling
  .circleci/config.yml
Labels: area/testing, version/0.15.0

#1916 Add support for kubernetes 1.15 in release 0.15.0-rc.2
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.15.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/update/cluster.go
  pkg/eks/eks.go
  pkg/eks/eks_test.go
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/10-eksclt.al2.conf
  pkg/nodebootstrap/assets/bootstrap.ubuntu.sh
  site/content/introduction/01-getting-started.md
Labels: kind/feature

#1923 Fix Fargate validation for EKS version 1.15 and above
  pkg/eks/eks.go
  pkg/eks/eks_test.go
  pkg/fargate/versions.go
Labels: area/fargate, kind/bug

#1931 Make integration test assertions on nodegroups more robust
  integration/matchers/json.go
  integration/matchers/json_test.go
  integration/tests/crud/creategetdelete_test.go
Labels: area/testing, version/0.16.0

#1909 Support tags for Fargate profiles
  examples/16-fargate-profile.yaml
  integration/tests/fargate/fargate_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/fargate.go
  pkg/ctl/create/fargate_test.go
  pkg/fargate/client.go
  pkg/fargate/client_test.go
  pkg/fargate/options.go
  pkg/fargate/print.go
  pkg/fargate/print_test.go
  site/content/usage/20-schema.md
Labels: area/fargate, version/0.16.0

#1939 Restore inadvertently deleted files
  snap/snapcraft.yaml
  tag-release-candidate.sh
  tag-release.sh
  tools.go
Labels: area/build-and-release

#1957 Fix root device mapping selection from AMI
  pkg/ami/ami_test.go
  pkg/ami/api.go
  pkg/eks/api_test.go
Labels: kind/bug

#1968 Fix url in gitops docs
  site/content/gitops-quickstart/01-apply-gitops.md
Labels: kind/bug

#1956 Improve kubernetes 1.10 deprecation message
  pkg/ctl/create/cluster.go
  pkg/ctl/create/utils.go
Labels: kind/bug

#1971 Add North California region us-west-1
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/feature

#1970 Add North California region us-west-1
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/feature

#1978 Make ITs more robust to long cluster names
  integration/tests/crud/creategetdelete_test.go
Labels: area/testing, kind/bug, version/0.17.0

#1986 Set kubeReserved defaults according to instance type
  Makefile
  pkg/cfn/builder/api_test.go
  pkg/nodebootstrap/reserved.go
  pkg/nodebootstrap/reserved_data.go
  pkg/nodebootstrap/reserved_generate.go
  pkg/nodebootstrap/reserved_test.go
  pkg/nodebootstrap/userdata.go
  pkg/nodebootstrap/userdata_test.go
  site/content/usage/11-customizing-the-kubelet.md
Labels: area/config-file, area/nodegroup, kind/improvement, priority/weave

#1997 Make kubernetes 1.15 the default version
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/api_test.go
  pkg/ctl/cmdutils/nodegroup_filter_test.go
  site/content/introduction/01-getting-started.md
Labels: kind/improvement
