Repository eksctl-io/eksctl, pull requests merged in 2020-06, with the labels that each got.

#2272 [release-0.21] Make sure kubeconfig directory exists before locking
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
Labels: area/general-cli, kind/bug, version/0.21.0

#2271 Make sure kubeconfig directory exists before locking
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
Labels: area/general-cli, kind/bug

#2267 Document minimum IAM policies
  userdocs/mkdocs.yml
  userdocs/src/usage/minimum-iam-policies.md
Labels: area/docs, kind/improvement

#2264 Refactor interface for creating kubeconfig
  pkg/eks/client.go
  pkg/nodebootstrap/userdata.go
  pkg/utils/kubeconfig/kubeconfig.go
Labels: technical debt

#2281 Fix click on config schema row
  userdocs/src/usage/schema.css
  userdocs/src/usage/schema.js
Labels: area/docs, version/0.22.0

#2289 Use aws-node v1.6.2
  pkg/addons/default/assets.go
  pkg/addons/default/assets/aws-node.yaml
  pkg/addons/default/aws_node_test.go
Labels: area/add-ons

#2288 [release-0.21] Use aws-node v1.6.2
  pkg/addons/default/assets.go
  pkg/addons/default/assets/aws-node.yaml
  pkg/addons/default/aws_node_test.go
Labels: area/add-ons, version/0.21.0

#2274 Unattended Flux installation for GitHub repos (automatic add of deploy key)
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/delete/cluster.go
  pkg/ctl/enable/repo.go
  pkg/gitops/deploykey/deploykey.go
  pkg/gitops/deploykey/github.go
  pkg/gitops/deploykey/github_test.go
  pkg/gitops/flux/installer.go
  pkg/gitops/flux/installer_test.go
Labels: kind/feature

#2286 Improve config documentation generation
  cmd/schema/generate.go
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/generate.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/schema/definition/comment.go
  pkg/schema/definition/comment_test.go
  pkg/schema/definition/definition.go
  pkg/schema/definition/schematypes.go
  pkg/schema/definition/suite_test.go
  pkg/schema/definition/tags.go
  pkg/schema/definition/types.go
  pkg/schema/importer/importer.go
  pkg/schema/schema.go
  pkg/schema/schema_test.go
  pkg/schema/suite_test.go
  pkg/schema/test/subpkg/subpkg.go
  pkg/schema/test/test.go
  pkg/utils/ipnet/ipnet.go
  userdocs/src/usage/schema.css
  userdocs/src/usage/schema.js
Labels: area/docs, version/0.22.0

#2295 Remove unused parameter
  pkg/nodebootstrap/userdata.go
  pkg/nodebootstrap/userdata_al2.go
  pkg/nodebootstrap/userdata_ubuntu.go
Labels: technical debt

#2301 Update gitops documentation
  pkg/ctl/cmdutils/gitops.go
  userdocs/src/usage/gitops.md
Labels: area/docs, kind/docs

#2298 Add more unit tests for `enable repo` command
  pkg/ctl/enable/repo_test.go
Labels: area/testing, kind/improvement, technical debt

#2303 Rename `update cluster` to `upgrade cluster`
  pkg/ctl/update/cluster.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/cluster_test.go
  pkg/ctl/upgrade/upgrade.go
  userdocs/src/usage/cluster-upgrade.md
  userdocs/src/usage/eks-managed-nodes.md
Labels: area/general-cli, area/upgrades, kind/improvement, version/0.22.0

#2306 Don't use generic helper functions from kops
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/utils/file/file.go
  pkg/utils/slice/slice.go
  pkg/vpc/vpc.go
Labels: technical debt

#2313 Refactor usage of utils functions
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/utils/slice/slice.go
  pkg/vpc/vpc.go
Labels: technical debt

#2312 Update iam minimum policies documentation
  userdocs/src/usage/minimum-iam-policies.md
Labels: area/docs, kind/docs, version/0.22.0

#2304 Do Fargate setup before nodegroup creation
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
  pkg/eks/fargate.go
  pkg/eks/tasks.go
Labels: area/fargate, kind/improvement, version/0.22.0

#2308 Allow StackCollection.DeleteStackByName() to succeed
  pkg/cfn/manager/api.go
Labels: priority/weave

#2310 Add support for App Mesh Preview Environment
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam_helper.go
  pkg/ctl/cmdutils/nodegroup_filter_test.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/eks/mocks/CloudFormationAPI.go
  pkg/eks/mocks/CloudTrailAPI.go
  pkg/eks/mocks/EC2API.go
  pkg/eks/mocks/EKSAPI.go
  pkg/eks/mocks/ELBAPI.go
  pkg/eks/mocks/ELBV2API.go
  pkg/eks/mocks/IAMAPI.go
  pkg/eks/mocks/SSMAPI.go
  pkg/eks/mocks/STSAPI.go
  userdocs/src/usage/iam-policies.md
Labels: area/aws-iam, version/0.22.0

#2294 Add KUBECONFIG_USE_SYSTEM_CA env variable to use the system CA instead of the EKS one
  pkg/eks/client.go
  pkg/eks/mocks/CloudFormationAPI.go
  pkg/eks/mocks/CloudTrailAPI.go
  pkg/eks/mocks/EC2API.go
  pkg/eks/mocks/EKSAPI.go
  pkg/eks/mocks/ELBAPI.go
  pkg/eks/mocks/ELBV2API.go
  pkg/eks/mocks/IAMAPI.go
  pkg/eks/mocks/SSMAPI.go
  pkg/eks/mocks/STSAPI.go
  pkg/nodebootstrap/userdata.go
  pkg/utils/kubeconfig/kubeconfig.go
  userdocs/src/usage/faq.md
Labels: kind/feature, version/0.22.0

#2317 Increase default volume size to 100G
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/nodegroup_filter_test.go
Labels: area/managed-nodegroup, area/nodegroup, version/0.22.0

#2314 Intro improvements, volumeSize references, default volume size 80G.
  userdocs/src/introduction.md
  userdocs/src/usage/creating-and-managing-clusters.md
  userdocs/src/usage/managing-nodegroups.md
Labels: kind/docs, version/0.22.0

#2318 Add support for configfile and --version in upgrade cluster command
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/utils.go
  pkg/ctl/update/cluster.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/cluster_test.go
  pkg/utils/utils.go
  userdocs/src/usage/cluster-upgrade.md
Labels: area/general-cli, area/upgrades, kind/improvement, version/0.22.0

#2326 Remove useless OWNERS file
  OWNERS
Labels: technical debt

#2324 Fetch git tags in integration script with https
  integration/scripts/download-previous-release.sh
Labels: area/testing

#2339 Windows 1909 support
  pkg/ami/auto_resolver.go
  pkg/ami/ssm_resolver.go
  pkg/ami/static_resolver_ami.go
  pkg/ami/static_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/eks/api_test.go
  pkg/nodebootstrap/userdata.go
  userdocs/src/usage/custom-ami-support.md
Labels: kind/improvement, version/0.23.0

#2259 Mark EKS 1.13 as deprecated
  docs/proposal-005-upgrades.md
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.13.json
  pkg/addons/default/coredns_test.go
  pkg/addons/default/testdata/sample-1.13.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/eks/eks.go
  userdocs/src/introduction.md
Labels: version/0.23.0

#2342 [release-0.22] Improve nodegroup, general config docs
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/utils/ipnet/ipnet.go
Labels: area/docs, kind/docs, version/0.22.0

#2346 [release-0.22] Config schema doc improvements
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: area/docs, kind/docs, version/0.22.0

#2353 Fix nodebootstrap asset generation
  Makefile
Labels: area/build-and-release, kind/bug

#2344 Mark `utils wait-nodes` as deprecated and hidden
  pkg/ctl/cmdutils/group.go
  pkg/ctl/utils/wait_nodes.go
Labels: area/general-cli, technical debt, version/0.23.0

#2355 Use compute-type of existing coredns on update
  pkg/addons/default/coredns.go
Labels: area/add-ons, kind/bug

#2356 Fix VPC networking docs on inbound traffic
  userdocs/src/usage/vpc-networking.md
Labels: area/docs, kind/docs

#2343 Remove nodegroups from authconfigmap after deletion, not before
  pkg/ctl/delete/nodegroup.go
Labels: area/nodegroup, kind/improvement, version/0.23.0

#2347 Config schema doc improvements
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/utils/ipnet/ipnet.go
Labels: area/docs, kind/docs, version/0.23.0

#2325 Remove pending on inferentia integration tests
  integration/tests/inferentia/inferentia_test.go
Labels: area/testing

#2359 Move to latest version of github-release, delete dead code
  .docker/build_image_manifest
  .docker/image_tag
  .requirements
  Makefile
  Makefile.docker
  go.mod
  go.sum
  tools.go
Labels: area/build-and-release, technical debt

#2365 Sort commands/subcommands by name in help
  cmd/eksctl/main.go
Labels: area/docs, area/general-cli

#2354 Use IMDSv2
  docs/current-001-node_bootstrap.md
  go.mod
  go.sum
  pkg/cfn/builder/api.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/fargate.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/outputs.go
  pkg/cfn/builder/partition.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/compat.go
  pkg/cfn/outputs/api.go
  pkg/cfn/template/iam_helpers.go
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/bootstrap.al2.sh
  pkg/nodebootstrap/assets/bootstrap.ubuntu.sh
Labels: area/nodegroup, kind/improvement

#2362 Update tags when calling StackCollection.UpdateStack()
  pkg/cfn/manager/api.go
  pkg/cfn/manager/api_test.go
Labels: priority/weave

#2319 Dark mode for homepage
  userdocs/mkdocs.yml
  userdocs/requirements.txt
  userdocs/src/extra.css
  userdocs/src/img/eksctl.png
  userdocs/src/img/empty.svg
  userdocs/src/img/gophers.png
  userdocs/src/img/moon-dark.svg
  userdocs/src/img/octocat-light.svg
  userdocs/src/img/sun-dark.svg
  userdocs/src/img/weaveworks-light.svg
  userdocs/src/index.md
  userdocs/src/usage/schema.css
  userdocs/theme/partials/header.html
Labels: kind/docs

#2380 Fix multi process kubeconfig access support
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
Labels: area/general-cli, kind/bug

#2381 [release-0.23] Fix multi process kubeconfig access support
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
Labels: area/general-cli, kind/bug, version/0.23.0

#2357 Fix nodegroup filter bug (#2276)
  pkg/apis/eksctl.io/v1alpha5/nodegroups.go
  pkg/ctl/cmdutils/cluster.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/filter/filter.go
  pkg/ctl/cmdutils/filter/filter_suite_test.go
  pkg/ctl/cmdutils/filter/filter_test.go
  pkg/ctl/cmdutils/filter/iamserviceaccount_filter.go
  pkg/ctl/cmdutils/filter/iamserviceaccount_filter_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/cmdutils/nodegroup_filter.go
  pkg/ctl/cmdutils/scale.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/get/iamserviceaccount.go
  userdocs/src/usage/iamserviceaccounts.md
  userdocs/src/usage/managing-nodegroups.md
Labels: kind/bug, priority/important-soon

#2348 Add support for enums to config schema documentation
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/schema/definition/comment.go
  pkg/schema/definition/comment_test.go
  pkg/schema/definition/definition.go
  pkg/schema/definition/enum.go
  pkg/schema/importer/importer.go
  pkg/schema/schema.go
  pkg/schema/schema_test.go
  pkg/schema/test/test.go
Labels: area/docs, kind/docs, version/0.23.0

#2385 To fix a couple of un-used parameters
  pkg/ami/auto_resolver_test.go
  pkg/cfn/manager/delete_tasks.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/delete/nodegroup.go
  pkg/eks/nodegroup.go
  pkg/iam/iam.go
  pkg/nodebootstrap/userdata.go
  pkg/nodebootstrap/userdata_al2.go
  pkg/nodebootstrap/userdata_ubuntu.go
Labels: kind/improvement
