Repository eksctl-io/eksctl, pull requests merged in 2020-12, with the labels that each got.

#2887 Add support for addons
  examples/25-addons.yaml
  go.mod
  go.sum
  integration/runner/runner.go
  integration/tests/addons/addons_test.go
  integration/tests/params.go
  pkg/actions/addon/addon.go
  pkg/actions/addon/addon_suite_test.go
  pkg/actions/addon/addon_test.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/actions/addon/delete.go
  pkg/actions/addon/delete_test.go
  pkg/actions/addon/describe_versions.go
  pkg/actions/addon/describe_versions_test.go
  pkg/actions/addon/fakes/fake_stack_manager.go
  pkg/actions/addon/get.go
  pkg/actions/addon/get_test.go
  pkg/actions/addon/tasks.go
  pkg/actions/addon/testdata/aws-node.json
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/addons/assets.go
  pkg/addons/default/assets.go
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/addon_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_test.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/iam.go
  pkg/ctl/cmdutils/addon.go
  pkg/ctl/create/addon.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/create.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/delete/addon.go
  pkg/ctl/delete/delete.go
  pkg/ctl/get/addon.go
  pkg/ctl/get/get.go
  pkg/ctl/update/addon.go
  pkg/ctl/update/update.go
  pkg/ctl/upgrade/upgrade.go
  pkg/ctl/utils/describe_addon_versions.go
  pkg/ctl/utils/utils.go
  pkg/eks/mocks/EC2API.go
  pkg/eks/mocks/EKSAPI.go
  pkg/iam/oidc/api.go
  pkg/iam/oidc/api_test.go
  pkg/nodebootstrap/assets.go
  userdocs/mkdocs.yml
  userdocs/src/usage/addons.md
Labels: kind/feature

#2890 migrate to latest github.com/aws/aws-sdk-go version
  go.mod
  go.sum
  pkg/eks/mocks/EKSAPI.go
Labels: kind/improvement

#2885 Update CONTRIBUTING.md and Makefile
  CONTRIBUTING.md
  Makefile
Labels: area/docs, skip-release-notes

#2884 Ensure gitops repo branches are deleted after integration test
  integration/tests/quickstart_profiles/quickstart_profiles_test.go
Labels: area/testing, skip-release-notes

#2892 Do not rebuild eksctl-build when creating releases
  Makefile.docker
Labels: skip-release-notes

#2897 Revert "Ensure gitops repo branches are deleted after runs"
  integration/tests/quickstart_profiles/quickstart_profiles_test.go
Labels: skip-release-notes

#2898 Add missing punctuation
  userdocs/src/usage/addons.md
Labels: skip-release-notes

#2886 Show status of fargate profile in get command.
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/fargate/client.go
  pkg/fargate/client_test.go
  pkg/fargate/print.go
  pkg/fargate/print_test.go
Labels: area/fargate, kind/improvement

#2913 Support enabling access for EMR containers
  Makefile
  pkg/addons/device_plugin.go
  pkg/addons/vpc_controller.go
  pkg/assetutil/assetutil.go
  pkg/authconfigmap/assets.go
  pkg/authconfigmap/assets/emr-containers-rbac.yaml
  pkg/authconfigmap/authconfigmap.go
  pkg/authconfigmap/service_access.go
  pkg/ctl/create/iamidentitymapping.go
  userdocs/src/usage/emr-access.md
Labels: kind/feature

#2917 Only use aws-node service account on cluster creation
  pkg/actions/addon/create.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/eks/nodegroup.go
  pkg/eks/tasks.go
Labels: area/aws-iam, kind/bug

#2912 Reliably get path to aws/aws-sdk-go in Makefile
  Makefile
Labels: area/build-and-release, skip-release-notes

#2918 Add instructions for customisable subnet options to VPC docs
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/vpc_test.go
  userdocs/src/usage/vpc-networking.md
Labels: area/docs, skip-release-notes

#2922 Update GPU docs
  userdocs/src/usage/gpu-support.md
Labels: area/docs, skip-release-notes

#2661 Deprecate static AMI resolver
  Makefile
  README.md
  pkg/ami/resolver.go
  pkg/ami/static_resolver.go
  pkg/ami/static_resolver_ami.go
  pkg/ami/static_resolver_ami_generate.go
  pkg/ami/static_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/eks/api.go
  pkg/eks/api_test.go
  userdocs/src/index.md
  userdocs/src/usage/custom-ami-support.md
  userdocs/src/usage/gpu-support.md
Labels: kind/improvement, technical debt

#2815 Support upgrading non eksctl clusters
  pkg/actions/cluster/cluster.go
  pkg/actions/cluster/cluster_suite_test.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/upgrade.go
  pkg/actions/cluster/upgrade_test.go
  pkg/cfn/manager/api.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/cluster_test.go
  pkg/eks/api.go
  pkg/eks/cache.go
  pkg/eks/eks.go
  pkg/eks/update.go
  pkg/testutils/cluster.go
  pkg/testutils/mockprovider/mock_provider.go
Labels: area/upgrades, kind/feature

#2927 Do not set a default value for nodeGroup.ami
  pkg/ctl/cmdutils/nodegroup_flags.go
Labels: kind/bug

#2914 Update ALB policy, now AWS load balancer controller policy
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/statement.go
  pkg/cfn/template/iam_helpers.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  userdocs/src/community.md
  userdocs/src/gitops-quickstart.md
  userdocs/src/usage/faq.md
  userdocs/src/usage/iamserviceaccounts.md
Labels: area/nodegroup, kind/docs, kind/improvement

#2928 treat remote VPC as source of truth
  pkg/vpc/vpc.go
Labels: kind/bug

#2929 Revert "treat remote VPC as source of truth"
  pkg/vpc/vpc.go
Labels: skip-release-notes

#2933 fix panic in VPC loading
  pkg/apis/eksctl.io/v1alpha5/vpc.go
Labels: kind/bug

#2940 Add specific private subnet documentation
  examples/24-nodegroup-subnets.yaml
  userdocs/src/usage/vpc-networking.md
Labels: area/docs, skip-release-notes

#2907 Bump k8s dependencies
  .github/workflows/update-generated.yaml
  Dockerfile
  Makefile.docker
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  integration/tests/crud/creategetdelete_test.go
  integration/tests/inferentia/inferentia_test.go
  integration/tests/update/update_cluster_test.go
  pkg/actions/addon/create.go
  pkg/addons/default/aws_node.go
  pkg/addons/default/aws_node_test.go
  pkg/addons/default/coredns.go
  pkg/addons/default/coredns_test.go
  pkg/addons/default/helpers_test.go
  pkg/addons/default/kube_proxy.go
  pkg/addons/default/kube_proxy_test.go
  pkg/addons/device_plugin.go
  pkg/addons/vpc_controller.go
  pkg/authconfigmap/authconfigmap.go
  pkg/authconfigmap/authconfigmap_test.go
  pkg/drain/cordon.go
  pkg/drain/evictor/evictor.go
  pkg/drain/evictor/pod.go
  pkg/drain/nodegroup.go
  pkg/drain/nodegroup_test.go
  pkg/eks/nodegroup.go
  pkg/eks/tasks.go
  pkg/elb/cleanup.go
  pkg/fargate/coredns/coredns.go
  pkg/fargate/coredns/coredns_test.go
  pkg/gitops/flux/installer.go
  pkg/gitops/flux/wait.go
  pkg/kubernetes/client.go
  pkg/kubernetes/client_test.go
  pkg/kubernetes/namespace.go
  pkg/kubernetes/serviceaccount.go
  pkg/kubernetes/serviceaccount_test.go
  pkg/testutils/client.go
  pkg/utils/kubeconfig/testdata/empty_cluster.golden
Labels: kind/improvement

#2924 Don't run bootstrap scripts twice and before preBootstrap
  pkg/cfn/builder/api_test.go
  pkg/cloudconfig/cloudconfig.go
  pkg/cloudconfig/cloudconfig_test.go
Labels: autosquash, kind/bug

#2932 Bump `eks/pause` infra container image
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.18.json
  pkg/addons/default/kube_proxy.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/10-eksclt.al2.conf
  pkg/nodebootstrap/assets/bootstrap.ubuntu.sh
Labels: kind/improvement

#2941 Deprecate v1.14
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.14.json
  pkg/addons/default/aws_node_test.go
  pkg/addons/default/coredns_test.go
  pkg/addons/default/kube_proxy_test.go
  pkg/addons/default/testdata/sample-1.14.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/introduction.md
  userdocs/src/usage/eks-managed-nodes.md
  userdocs/src/usage/windows-worker-nodes.md
Labels: area/docs, area/nodegroup, kind/improvement

#2947 Delete UpdateAddonsTask
  pkg/addons/default/addons.go
  pkg/eks/tasks.go
  userdocs/src/usage/arm-support.md
Labels: kind/docs, skip-release-notes

#2949 Add oneOf support to schema generation
  pkg/schema/definition/comment.go
  pkg/schema/definition/definition.go
  pkg/schema/definition/types.go
  pkg/schema/schema_test.go
  pkg/schema/test/test.go
Labels: area/build-and-release, autosquash, skip-release-notes

#2951 Use eksbuild.1 coredns image
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.18.json
Labels: autosquash, skip-release-notes

#2948 add sub condition to vpc-cni addon policy
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_test.go
Labels: area/add-ons, kind/improvement

#2820 Add AutoscalingGroupName to nodegroupsummary
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/ctl/get/nodegroup.go
Labels: kind/improvement

#2911 get/delete/drain support for non-eksctl created managed nodegroups
  pkg/actions/create/nodegroup.go
  pkg/actions/nodegroup/delete.go
  pkg/actions/nodegroup/drain.go
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/cmdutils/nodegroup.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/get/nodegroup.go
  pkg/drain/nodegroup.go
Labels: area/managed-nodegroup, kind/feature

#2952 encrypt bottlerocket os volume
  pkg/ami/api.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/nodegroup.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
Labels: kind/bug

#2959 ignore all twitter links when checking links
  .github/workflows/check-links.yaml
Labels: kind/bug, skip-release-notes

#2962 Have kubelet use systemd cgroup driver on al2 and ubuntu
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/docker-daemon.json
  pkg/nodebootstrap/assets/kubelet.yaml
  pkg/nodebootstrap/userdata.go
  pkg/nodebootstrap/userdata_al2.go
  pkg/nodebootstrap/userdata_ubuntu.go
Labels: kind/improvement

#2978 Do not thank claudia in release notes
  .github/release-drafter.yml
Labels: skip-release-notes

#2863 Add option to specify IAM role name
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_test.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/create/iamserviceaccount_test.go
  userdocs/src/usage/iamserviceaccounts.md
Labels: area/aws-iam, kind/improvement

#2991 Treat p4d as a GPU instance
  pkg/utils/utils.go
Labels: kind/improvement

#3003 Fix bootstrap command in the examples
  examples/15-managed-nodes.yaml
Labels: kind/improvement
