Repository eksctl-io/eksctl, pull requests merged in 2020-02, with the labels that each got.

#1799 Use release-drafter to automate the creation of release notes
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
  CONTRIBUTING.md
Labels: kind/improvement

#1803 Update gitops docs
  pkg/ctl/enable/profile.go
  site/content/gitops-quickstart/01-apply-gitops.md
  site/content/usage/experimental/01-gitops.md
Labels: kind/docs

#1804 Add example of using labels for forcing pods to run on desired node groups
  examples/18-node-to-pod-label-matching.yaml
  pkg/ctl/cmdutils/configfile_test.go
Labels: kind/improvement, version/0.14.0

#1792 Add integration tests for Fargate
  integration/fargate_test.go
  integration/integration_test.go
  integration/runner/runner.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: area/fargate, area/managed-nodegroup, area/testing, kind/improvement, version/0.14.0

#1809 Deprecate latest_release tag
  CONTRIBUTING.md
  README.md
  site/content/introduction/02-installation.md
Labels: area/build-and-release, kind/improvement, technical debt, version/0.14.0

#1810 Update pull-request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/build-and-release, kind/improvement, version/0.14.0

#1798 Add makefile command to manually publish a release
  .docker/build_image_manifest
  .docker/image_tag
  .goreleaser-local.yaml
  .goreleaser.yml
  Makefile
  Makefile.common
  go.mod
  go.sum
  tools/brew/formula.tmpl
  tools/brew/update_formula.go
Labels: area/build-and-release, kind/improvement, version/0.14.0

#1814 Default to SSM Parameter for AMI resolution
  pkg/ami/api.go
  pkg/ami/resolver.go
  pkg/ami/ssm_resolver.go
  pkg/ami/static_resolver.go
  pkg/ami/static_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/ctl/cmdutils/nodegroup_filter_test.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/eks/api.go
  pkg/eks/api_test.go
Labels: area/nodegroup

#1825 Improve error message for Fargate support
  pkg/ctl/delete/cluster.go
Labels: area/fargate

#1828 Temporarily disable scheduled integration tests
  .circleci/config.yml
Labels: area/testing

#1821 Fix bug in update-cluster-endpoint #1820
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
Labels: kind/bug, version/0.14.0

#1836 Fix missing tags in nodegroup after scaling (#1834)
  pkg/cfn/manager/api.go
Labels: kind/bug, version/0.14.0

#1833 Add release notes for 0.14.0
  docs/release_notes/0.14.0-draft.md
  docs/release_notes/0.14.0.md
Labels: version/0.14.0

#1837 Increase IT timeout to 4.5h
  Makefile
Labels: kind/improvement

#1848 Use regional STS endpoints for aws-iam-authenticator and AWS SDK
  pkg/cfn/builder/api_test.go
  pkg/eks/api.go
  pkg/utils/kubeconfig/kubeconfig.go
Labels: area/aws-iam

#1854 Fix null pointer dereference in cluster access validation
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/test_data/cluster-with-vpc-private-access.yaml
  pkg/ctl/cmdutils/test_data/cluster-with-vpc.yaml
  pkg/ctl/cmdutils/test_data/cluster-without-vpc-private-access.yaml
  pkg/ctl/cmdutils/test_data/cluster-without-vpc.yaml
Labels: kind/bug

#1851 Increase timeout of operations for managed nodegroup tests to 20m
  integration/managed_nodegroup_test.go
Labels: kind/improvement

#1858 Fix urls to download latest eksctl binaries
  README.md
  site/content/introduction/02-installation.md
Labels: kind/bug

#1857 Remove integration tests timeout
  Makefile
Labels: kind/improvement

#1860 Add support for China regions
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/fargate.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/partition.go
  pkg/cfn/template/iam_helpers.go
  pkg/ctl/cmdutils/nodegroup_filter_test.go
  pkg/eks/eks.go
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/10-eksclt.al2.conf
  pkg/nodebootstrap/assets/bootstrap.al2.sh
  pkg/nodebootstrap/assets/bootstrap.ubuntu.sh
Labels: area/aws-iam, kind/feature

#1720 Ningxia region
  pkg/ami/auto_resolver.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: version/0.14.0

#1741 Add region of Beijing cn-north-1
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: version/0.14.0

#1867 Refactor setting container image for addons, support addons for China regions
  pkg/addons/assets.go
  pkg/addons/assets/vpc-admission-webhook-dep.yaml
  pkg/addons/assets/vpc-resource-controller-dep.yaml
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.11.json
  pkg/addons/default/assets/coredns-1.12.json
  pkg/addons/default/assets/coredns-1.13.json
  pkg/addons/default/assets/coredns-1.14.json
  pkg/addons/default/aws_node.go
  pkg/addons/default/coredns.go
  pkg/addons/default/coredns_test.go
  pkg/addons/default/testdata/sample-1.11.json
  pkg/addons/default/testdata/sample-1.12.json
  pkg/addons/default/testdata/sample-1.13.json
  pkg/addons/image.go
  pkg/addons/vpc_controller.go
Labels: kind/feature, technical debt
