Repository eksctl-io/eksctl, pull requests merged in 2020-05, with the labels that each got.

#2116 Support Amazon EKS Kubernetes version 1.16
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.16.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/update/cluster.go
  userdocs/src/introduction.md
Labels: kind/feature

#2033 Publish RCs to the homebrew tap
  .goreleaser.brew.yml
  do-release-candidate.sh
  tag-release-candidate.sh
Labels: area/build-and-release, kind/improvement

#2120 Private-only clusters with an eksctl-created VPC are not supported
  integration/tests/cluster_api/cluster_api_endpoints_test.go
Labels: kind/bug

#2072 Enable slack notifications for broken master builds
  .circleci/config.yml
Labels: area/build-and-release, kind/improvement

#2133 Fix helm-operator pod name for Flux
  integration/matchers/flux.go
  pkg/gitops/flux/wait.go
Labels: kind/bug, priority/critical

#2069 Log warning in cluster update command when in plan mode
  pkg/cfn/manager/cluster.go
Labels: kind/bug

#2130 Fix tag-release-candidate.sh script. Push release branch
  tag-release-candidate.sh
Labels: kind/bug

#2117 Fix nameLabelValue when waiting for helm-operator
  integration/matchers/flux.go
  pkg/gitops/flux/wait.go
Labels: kind/bug, priority/critical

#2138 Move Gitops guides below the Usage section in the site
  userdocs/mkdocs.yml
Labels: area/docs, kind/docs

#2129 Do some nodegroup-independent tasks in parallel with nodegroup creation
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/create/cluster.go
  pkg/eks/tasks.go
Labels: area/general-cli, kind/bug, version/0.20.0

#2142 Remove old test for Cluster API endpoint only private access
  integration/tests/cluster_api/cluster_api_endpoints_test.go
Labels: kind/improvement

#2149 Fix broken AllocationId syntax in VPC cloudformation
  pkg/cfn/builder/vpc.go
Labels: area/aws-vpc, kind/bug

#2057 Add new GPU instance type inf1
  pkg/utils/utils.go
Labels: area/nodegroup, kind/feature

#2134 Show message about device plugin for inf1 instances
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/utils.go
  pkg/utils/utils.go
Labels: kind/improvement

#2156 Tag new clusters with Metadata.Tags
  pkg/eks/tasks.go
  pkg/eks/update.go
  pkg/eks/update_test.go
Labels: kind/feature, version/0.20.0

#2144 Fix upgrading managed nodegroups
  integration/tests/managed/managed_nodegroup_test.go
  integration/tests/params.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/managed/service.go
Labels: kind/bug

#2180 Make sure integration tests wait for deletion
  integration/tests/params.go
Labels: area/testing

#2157 Update CONTRIBUTING.md with user docs step
  .github/workflows/check-links.yaml
  CONTRIBUTING.md
  Makefile
Labels: area/docs, kind/docs

#2165 Add name argument for delete iamserviceaccount
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/delete/iamserviceaccount_test.go
Labels: area/general-cli, kind/improvement

#2185 Slightly improve grammar in info message
  pkg/ctl/cmdutils/filter.go
Labels: area/general-cli

#2183 Fix Fargate on Kubernetes 1.16
  pkg/ctl/create/fargate.go
  pkg/fargate/coredns/coredns.go
  pkg/fargate/coredns/coredns_test.go
  pkg/fargate/coredns/deployment.go
Labels: kind/bug

#2190 Add support for GovCloud regions
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/partition.go
  pkg/eks/eks.go
Labels: kind/feature

#2188 Change the time we run the IT to 2am SF time
  .circleci/config.yml
Labels: area/testing

#2184 Add DependsOn to AWSEC2Route to fix flaky cluster creation
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/vpc.go
Labels: area/testing, kind/bug

#2193 Some small config schema improvements
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/iam.go
  pkg/ctl/cmdutils/iamserviceaccount_filter.go
  userdocs/src/usage/schema.md
Labels: area/docs, version/0.21.0

#2204 [release-0.20] Make 1.16 as default (copy of #2199)
  docs/release_notes/0.20.0.md
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/api_test.go
  pkg/ctl/cmdutils/nodegroup_filter_test.go
  userdocs/src/introduction.md
Labels: kind/feature, version/0.20.0

#2196 Improve config file schema docs
  Makefile
  cmd/schema/generate.go
  go.mod
  go.sum
  userdocs/mkdocs.yml
  userdocs/src/usage/schema.css
  userdocs/src/usage/schema.js
  userdocs/src/usage/schema.json
  userdocs/src/usage/schema.md
Labels: area/config-file, area/docs, kind/improvement

#2206 Improve schema docs for IPs
  cmd/schema/generate.go
  userdocs/src/usage/schema.json
Labels: area/docs, kind/docs

#2208 Increase cluster update timeout to 45 minutes
  pkg/ctl/update/cluster.go
Labels: area/testing

#2203 Recover relevant CSS pre-mkdocs
  userdocs/mkdocs.yml
  userdocs/src/extra.css
  userdocs/src/img/gophers.png
  userdocs/src/index.md
  userdocs/theme/assets/_custom.scss
Labels: area/docs, version/0.21.0

#2192 Add support for setting up Gitops during cluster creation
  cmd/eksctl/main.go
  examples/21-eks-quickstart-app-dev.yaml
  go.mod
  go.sum
  integration/tests/params.go
  integration/tests/quickstart_profiles/quickstart_profiles_test.go
  integration/tests/quickstart_profiles_gen/quickstart_profiles_gen_test.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/cmdutils/utils.go
  pkg/ctl/create/cluster.go
  pkg/ctl/ctltest/utils.go
  pkg/ctl/enable/enable.go
  pkg/ctl/enable/profile.go
  pkg/ctl/enable/profile_test.go
  pkg/ctl/enable/repo.go
  pkg/ctl/enable/repo_test.go
  pkg/ctl/generate/generate.go
  pkg/ctl/generate/profile.go
  pkg/ctl/generate/profile_test.go
  pkg/eks/tasks.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/gitops/apply.go
  pkg/gitops/flux/installer.go
  pkg/gitops/flux/installer_test.go
  pkg/gitops/gitops.go
  pkg/gitops/gitops_test.go
  pkg/gitops/profile.go
  pkg/gitops/profile/options.go
  pkg/gitops/url.go
  pkg/gitops/url_test.go
  userdocs/mkdocs.yml
  userdocs/src/gitops-quickstart.md
  userdocs/src/usage/gitops.md
  userdocs/src/usage/schema.json
Labels: area/gitops, kind/feature, version/0.20.0

#2162 Install neuron plugin for inf1 instances
  integration/matchers/kubernetes.go
  integration/tests/inferentia/inferentia_test.go
  pkg/addons/assets.go
  pkg/addons/assets/neuron-device-plugin.yaml
  pkg/addons/neuron_device_plugin.go
  pkg/apis/eksctl.io/v1alpha5/nodegroups.go
  pkg/ctl/cmdutils/create_cluster.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/utils.go
  pkg/eks/tasks.go
  pkg/utils/utils.go
Labels: area/add-ons, area/nodegroup, kind/feature, version/0.20.0

#2213 [release-0.20] Add IAM permissions required by AWS ALB Ingress to use WAFv2 and Shield
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam_helper.go
Labels: kind/feature

#2179 Add unit test data for 1.14, 1.15 and 1.16
  .docker/build_image_manifest
  .docker/image_tag
  go.mod
  go.sum
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.11.json
  pkg/addons/default/assets/coredns-1.12.json
  pkg/addons/default/aws_node_test.go
  pkg/addons/default/coredns_test.go
  pkg/addons/default/helpers_test.go
  pkg/addons/default/kube_proxy_test.go
  pkg/addons/default/testdata/sample-1.14.json
  pkg/addons/default/testdata/sample-1.15.json
  pkg/addons/default/testdata/sample-1.16.json
  pkg/ami/static_resolver_ami.go
  pkg/ctl/update/cluster.go
  pkg/eks/client_test.go
  pkg/kubernetes/client.go
  pkg/kubernetes/client_test.go
  pkg/kubernetes/scheme.go
Labels: area/testing, kind/bug, version/0.21.0

#2214 Show required fields in config docs, document schema command
  userdocs/src/usage/schema.css
  userdocs/src/usage/schema.js
  userdocs/src/usage/schema.md
Labels: area/docs, version/0.21.0

#2168 Use legacy ng tags to find ng type
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
Labels: kind/bug

#2218 Fix casing of field in error message
  pkg/apis/eksctl.io/v1alpha5/validation.go
Labels: kind/improvement

#2219 Don't overwrite timeout in update cluster command
  pkg/ctl/update/cluster.go
Labels: area/testing

#2222 Fix kubernetes client serializer
  pkg/kubernetes/client.go
Labels: kind/bug

#2227 Disallow setting node-role.kubernetes.io label
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/bug

#2231 Fix timeouts in gitops operations on Fargate
  pkg/ctl/create/cluster.go
  pkg/ctl/enable/repo.go
  pkg/gitops/flux/installer.go
  pkg/gitops/flux/wait.go
  pkg/gitops/gitops.go
Labels: kind/bug, version/0.20.0

#2232 [release-0.20] Fix timeouts in gitops operations on Fargate
  pkg/ctl/create/cluster.go
  pkg/ctl/enable/repo.go
  pkg/gitops/flux/installer.go
  pkg/gitops/flux/wait.go
  pkg/gitops/gitops.go
Labels: kind/bug, version/0.20.0

#2234 Wait for cluster upgrade in integration test
  integration/tests/managed/managed_nodegroup_test.go
Labels: area/testing

#2235 Set inferentia tests to pending while support is flaky
  integration/tests/inferentia/inferentia_test.go
Labels: area/testing

#2239 Increase golangci-lint timeout, use go.sum for circleci cache
  .circleci/config.yml
  .golangci.yml
  Makefile
Labels: area/testing

#1796 Ability of changing the node instance name
  examples/18-override-nodes-name.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/nodegroup_flags.go
Labels: kind/feature, version/0.21.0

#2238 Use apps/v1 for Deployment for all K8s versions
  pkg/ctl/create/fargate.go
  pkg/fargate/coredns/coredns.go
  pkg/fargate/coredns/coredns_test.go
  pkg/fargate/coredns/deployment.go
Labels: kind/improvement

#2247 docs: replace remaining quote blocks with styled notations
  userdocs/src/index.md
  userdocs/src/usage/vpc-networking.md
Labels: area/docs

#2248 Don't run extra cluster tasks and nodegroup creation in parallel
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/tasks_test.go
Labels: kind/bug, version/0.21.0

#2241 Support URLs as template data when creating stack
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/compat.go
  pkg/cfn/manager/nodegroup.go
Labels: priority/weave

#2242 Update goreleaser
  .docker/build_image_manifest
  .docker/image_tag
  .goreleaser.brew.yml
  Makefile
  go.mod
  go.sum
Labels: area/build-and-release

#2253 Fix update-cluster-endpoints panic when using a cluster config with missing VPC section
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/ctl/cmdutils/configfile.go
Labels: area/config-file, priority/weave, version/0.21.0

#2254 Fix unknown revisions, update old versions in go.mod
  go.mod
Labels: area/build-and-release, version/0.21.0

#2246 Fix bug in supporting non-default branches for gitops repos
  pkg/git/git.go
  pkg/git/git_test.go
Labels: area/gitops, kind/bug, version/0.21.0

#2252 Try to delete nodegroup for any nodegroup state
  pkg/eks/nodegroup.go
Labels: area/deletions, area/nodegroup, kind/bug, version/0.21.0
