Repository eksctl-io/eksctl, pull requests merged in 2020-01, with the labels that each got.

#1700 Fix aws-sdk versions
  Makefile
  go.mod
Labels: version/0.13.0

#1443 Migrate to golangci-lint
  .docker/build_image_manifest
  .docker/image_tag
  .golangci.yml
  .gometalinter.json
  .requirements
  Makefile
  cmd/schema/generate.go
  go.mod
  go.sum
  install-build-deps.sh
  pkg/addons/vpc_controller.go
  pkg/authconfigmap/authconfigmap.go
  pkg/authconfigmap/authconfigmap_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/vpc.go
  pkg/ctl/enable/repo.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/eks/mocks/CloudFormationAPI.go
  pkg/eks/mocks/CloudTrailAPI.go
  pkg/eks/mocks/EC2API.go
  pkg/eks/mocks/EKSAPI.go
  pkg/eks/mocks/ELBAPI.go
  pkg/eks/mocks/ELBV2API.go
  pkg/eks/mocks/IAMAPI.go
  pkg/eks/mocks/SSMAPI.go
  pkg/eks/mocks/STSAPI.go
  pkg/eks/tasks.go
  pkg/gitops/flux/installer.go
  pkg/gitops/flux/wait.go
  tools.go
Labels: version/0.13.0

#1731 Fix test failed due to IPv6
  pkg/iam/oidc/api_test.go
Labels: area/testing, version/0.13.0

#1733 Add release notes for 0.13.0 (+clean-up)
  docs/release_notes/0.12.0.md
  docs/release_notes/0.13.0.md
  docs/release_notes/0.14.0-draft.md
Labels: area/build-and-release, kind/docs, version/0.13.0

#1693 Support public/private API endpoints settings from file
  docs/release_notes/0.14.0-draft.md
  pkg/ctl/utils/update_cluster_endpoint_access.go
  site/content/usage/06-vpc-networking.md
Labels: version/0.14.0

#1477 Bugfix/subnets duplicate
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: version/0.14.0

#1726 Implement new versioning
  .circleci/config.yml
  .goreleaser.yml
  CONTRIBUTING.md
  Makefile
  Makefile.common
  cmd/eksctl/version.go
  docs/release_notes/0.14.0-draft.md
  goreleaser-local.yaml
  pkg/version/generate/generate_suite_test.go
  pkg/version/generate/release_generate.go
  pkg/version/generate/release_generate_test.go
  pkg/version/norelease.go
  pkg/version/release.go
  pkg/version/release_generate.go
  pkg/version/version.go
  pkg/version/version_suite_test.go
  pkg/version/version_test.go
  tag-release-candidate.sh
  tag-release.sh
Labels: area/build-and-release, area/general-cli, version/0.14.0

#1727 Manual circleci step to build binaries for all distros
  .circleci/config.yml
Labels: version/0.14.0

#1738 Make builds reproducible with trimpath
  .goreleaser-local.yaml
  .goreleaser.yml
  Makefile
Labels: version/0.14.0

#1746 Added the ability to override the kube config cluster server.
  docs/release_notes/0.14.0-draft.md
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
  site/content/usage/06-vpc-networking.md
Labels: version/0.14.0

#1753 Fix running backwards compatibility tests in the built container image
  integration/scripts/download-previous-release.sh
Labels: area/testing

#1638 Permissions Boundary
  examples/17-permissions-boundary.yaml
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/fargate.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/iam_test.go
  pkg/cfn/template/iam.go
  pkg/ctl/cmdutils/configfile_test.go
  site/content/usage/17-permissions-boundary.md
  site/content/usage/20-schema.md
Labels: version/0.14.0

#1749 Create Fargate role only if there is --fargate
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/cluster.go
Labels: area/fargate, version/0.14.0

#1739 Notify us on slack when IT fail
  .circleci/config.yml
Labels: version/0.14.0

#1764 Fix missing format string in log line
  pkg/utils/kubeconfig/kubeconfig.go
Labels: version/0.14.0

#1766 Fix IT failures
  integration/managed_nodegroup_test.go
  integration/scripts/download-previous-release.sh
Labels: version/0.14.0

#1758 Correct few static code check
  integration/runner/runner.go
  pkg/addons/vpc_controller.go
  pkg/ami/auto_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/authconfigmap/authconfigmap.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/cfn/outputs/api.go
  pkg/ctl/cmdutils/cmdutils.go
  pkg/ctl/create/fargate_test.go
  pkg/ctl/delete/fargate_test.go
  pkg/ctl/get/fargate_test.go
  pkg/drain/nodegroup.go
  pkg/eks/api_test.go
  pkg/fargate/client_test.go
  pkg/fargate/coredns/coredns_test.go
  pkg/fargate/options.go
  pkg/fargate/print_test.go
  pkg/gitops/flux/wait.go
  pkg/kubernetes/client_test.go
  pkg/printers/json_test.go
  pkg/printers/table_test.go
  pkg/printers/yaml_test.go
  pkg/testutils/client.go
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
  pkg/utils/kubectl.go
  pkg/utils/names/names_test.go
Labels: technical debt, version/0.14.0
