Repository eksctl-io/eksctl, pull requests merged in 2021-03, with the labels that each got.

#3376 Merge release 0.39 to main
  docs/release_notes/0.39.0.md
  go.mod
  go.sum
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/identity_provider.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/cluster.go
  pkg/ctl/cmdutils/kms.go
  pkg/ctl/utils/enable_secrets_encryption.go
  pkg/ctl/utils/utils.go
  pkg/eks/api.go
  pkg/eks/eks_test.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/EKSAPI.go
  pkg/eks/mocks/IAMAPI.go
  pkg/eks/mocks/mocks.go
  pkg/eks/nodegroup.go
  pkg/eks/update.go
  pkg/kubernetes/kms.go
  pkg/testutils/mockprovider/mock_provider.go
  userdocs/mkdocs.yml
  userdocs/src/usage/kms-encryption.md
Labels: skip-release-notes

#3323 Create nodegroups/managed-nodegroups on unowned clusters
  Makefile
  integration/tests/params.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/fargate/create.go
  pkg/actions/fargate/unowned.go
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/delete.go
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/outputs.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/compat.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/error.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/eks/compatibility.go
  pkg/eks/eks.go
  pkg/vpc/fakes/fake_vpc_importer.go
  pkg/vpc/importer.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/feature

#3377 Fix download script for backwards-compatibility test
  integration/scripts/download-previous-release.sh
Labels: area/testing, kind/bug, skip-release-notes

#3379 Revert "Create nodegroups/managed-nodegroups on unowned clusters"
  Makefile
  integration/tests/params.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/fargate/create.go
  pkg/actions/fargate/unowned.go
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/delete.go
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/outputs.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/compat.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/error.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/eks/compatibility.go
  pkg/eks/eks.go
  pkg/vpc/fakes/fake_vpc_importer.go
  pkg/vpc/importer.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: skip-release-notes

#3384 Add release notes for 0.40.0
  docs/release_notes/0.40.0.md
Labels: skip-release-notes

#3388 Create nodegroups/managed-nodegroups on unowned clusters
  Makefile
  integration/tests/params.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/fargate/create.go
  pkg/actions/fargate/unowned.go
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/delete.go
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/outputs.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/compat.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/error.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/eks/compatibility.go
  pkg/eks/eks.go
  pkg/vpc/fakes/fake_vpc_importer.go
  pkg/vpc/importer.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/feature

#3335 create IRSA with existing role
  examples/13-iamserviceaccounts.yaml
  pkg/actions/irsa/delete.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/iam.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/create/iamserviceaccount_test.go
  pkg/ctl/delete/iamserviceaccount.go
  userdocs/src/usage/iamserviceaccounts.md
Labels: area/aws-iam, kind/feature

#3394 Fix 3393: fully-private clusters are not supported in region ""
  pkg/cfn/builder/cluster.go
Labels: kind/bug

#3395 Cherry pick some things from main to 40
  Makefile
  docs/release_notes/0.40.0.md
  integration/tests/params.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/fargate/create.go
  pkg/actions/fargate/unowned.go
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/delete.go
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/outputs.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/compat.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/error.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/eks/compatibility.go
  pkg/eks/eks.go
  pkg/vpc/fakes/fake_vpc_importer.go
  pkg/vpc/importer.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: skip-release-notes

#3398 Set systemd cgroupdriver when HasMixedInstances (fix 3391)
  pkg/nodebootstrap/userdata_al2.go
Labels: kind/bug

#3399 Set systemd cgroupdriver when HasMixedInstances
  docs/release_notes/0.40.0.md
  pkg/nodebootstrap/userdata_al2.go
Labels: skip-release-notes

#3402 Merge release 0.40.0 to main
  docs/release_notes/0.40.0.md
Labels: skip-release-notes

#3401 Fix the draft 7 schema URL
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/schema/schema.go
Labels: kind/improvement

#3415 Update to Go 1.16
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#3418 Fix iamidentitymapping verb in help message
  pkg/ctl/cmdutils/iam_flags.go
  pkg/ctl/create/iamidentitymapping.go
  pkg/ctl/delete/iamidentitymapping.go
  pkg/ctl/get/iamidentitymapping.go
Labels: kind/improvement

#3378 add missing arm64 node selector during update kube-proxy
  go.mod
  go.sum
  pkg/addons/default/kube_proxy.go
  pkg/addons/default/kube_proxy_test.go
  pkg/ctl/utils/update_kube_proxy.go
Labels: kind/improvement

#3383 add support for enabling capacity rebalancing when using Spot instances
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/nodegroup.go
Labels: kind/feature

#3412 Disallow invalid AMI values
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/eks/api.go
Labels: area/nodegroup, kind/bug

#3425 Wait longer before retrying throttled CloudFormation requests
  pkg/eks/logging_retryer.go
  pkg/utils/waiters/waiters.go
Labels: kind/improvement

#3321 Create and delete fargate role stack as needed during create/delete fargate profile
  go.sum
  pkg/actions/addon/get_test.go
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/fargate/create.go
  pkg/actions/fargate/create_test.go
  pkg/actions/fargate/export_test.go
  pkg/actions/fargate/fargate.go
  pkg/actions/fargate/fargate_suite_test.go
  pkg/actions/fargate/tasks.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/manager/cluster.go
  pkg/ctl/create/fargate.go
  pkg/ctl/delete/fargate.go
  pkg/ctl/get/fargate.go
  pkg/eks/tasks.go
  pkg/fargate/delete.go
  pkg/fargate/fargate.go
  pkg/fargate/fargate_test.go
Labels: area/fargate, kind/improvement

#3428 pend GPU node tests
  integration/tests/crud/creategetdelete_test.go
  integration/tests/inferentia/inferentia_test.go
Labels: skip-release-notes

#3421 Minimize number of CFN calls for `create cluster`
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/waiter/stack.go
  pkg/cfn/waiter/waiter.go
  pkg/eks/eks.go
  pkg/utils/waiters/waiters.go
Labels: kind/improvement

#3427 Support tags for Addons service accounts
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  userdocs/src/usage/addons.md
Labels: kind/feature

#3429 Add release notes for 0.41.0
  docs/release_notes/0.41.0.md
Labels: skip-release-notes

#3027 Add default security group rules to custom SGs
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/defaults_test.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/vpc.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/create/cluster.go
  userdocs/src/usage/vpc-networking.md
Labels: kind/feature

#3437 Refactor nodegroup CLI options
  pkg/actions/nodegroup/create.go
  pkg/ctl/cmdutils/create_cluster.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/nodegroup_test.go
Labels: area/nodegroup, kind/improvement, technical debt

#3438 force addons creation during cluster creation
  go.sum
  pkg/actions/addon/tasks.go
  pkg/ctl/create/cluster.go
Labels: area/add-ons, kind/bug

#3447 Fix: nil pointer dereference when VPC is empty
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
Labels: kind/bug

#3450 Disallow setting internal fields
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: area/config-file, kind/bug

#3454 bump integration test upgrade timeouts
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: skip-release-notes

#3456 Add release notes for 0.42
  docs/release_notes/0.42.0.md
Labels: skip-release-notes

#3455 Deprecate WindowsServer1909CoreContainer AMI Family and improve error messages
  pkg/ami/auto_resolver.go
  pkg/ami/ssm_resolver.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/ctl/create/nodegroup.go
Labels: kind/improvement

#3460 Delete Mike
  .github/release-drafter.yml
  COMMUNITY.md
Labels: skip-release-notes

#3462 We have a make help command yo
  Makefile
  Makefile.docker
  Makefile.docs
Labels: skip-release-notes

#3463 add managed-by label to eksctl created service accounts
  pkg/cfn/manager/create_tasks.go
Labels: area/apply, kind/improvement

#3466 Update EFA device plugin to 0.3.3
  pkg/addons/assets.go
  pkg/addons/assets/efa-device-plugin.yaml
Labels: kind/improvement

#3471 Add docs for non eksctl-created clusters
  userdocs/mkdocs.yml
  userdocs/src/index.md
  userdocs/src/usage/faq.md
  userdocs/src/usage/unowned-clusters.md
Labels: skip-release-notes

#3473 Fix service principal for cluster and Fargate profile role
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/fargate.go
  pkg/cfn/builder/iam.go
Labels: area/aws-iam, kind/bug

#3467 Attach EFA SG to network interfaces
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/vpc.go
Labels: kind/bug

#3478 Fixed missing Bottlerocket in custom AMI document
  userdocs/src/usage/custom-ami-support.md
Labels: kind/docs

#3481 Add release notes for 0.43
  docs/release_notes/0.43.0.md
Labels: skip-release-notes

#3485 Error when no VPC config provided for nodegroups created on unowned cluster
  pkg/actions/nodegroup/create.go
  userdocs/src/usage/unowned-clusters.md
Labels: skip-release-notes

#3491 Run integration tests earlier
  .github/workflows/integration-tests.yaml
Labels: skip-release-notes

#3494 increase delete unowned cluster timeout
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: skip-release-notes

#3451 Add support for dry-run
  integration/main.go
  integration/runner/runner.go
  integration/tests/dry_run/dry_run_test.go
  pkg/actions/nodegroup/create.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/create_cluster.go
  pkg/ctl/cmdutils/dry_run.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/eks/api.go
  pkg/vpc/vpc.go
Labels: kind/feature

#3495 update dependencies
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: dependencies, skip-release-notes

#3476 Add support for EC2 instance selector
  go.mod
  go.sum
  integration/tests/dry_run/dry_run_test.go
  pkg/actions/nodegroup/create.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/instance_selector_test.go
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/eks/nodegroup_service.go
Labels: kind/feature

#3498 Add documentation for Instance Selector
  examples/28-instance-selector.yaml
  userdocs/src/usage/instance-selector.md
Labels: area/docs, skip-release-notes

#3500 Add release notes for 0.44
  docs/release_notes/0.44.md
Labels: skip-release-notes

#3502 Reorganise docs nav menu
  userdocs/mkdocs.yml
  userdocs/src/usage/addon-upgrade.md
  userdocs/src/usage/cluster-upgrade.md
  userdocs/src/usage/fargate-support.md
  userdocs/src/usage/nodegroup-upgrade.md
Labels: skip-release-notes

#3503 bump fargate timeout
  integration/tests/fargate/fargate_test.go
Labels: skip-release-notes

#3504 Fix dry run integration tests
  integration/tests/dry_run/dry_run_test.go
Labels: skip-release-notes

#3492 Use built-in AMI bootstrapping scripts for unmanaged nodes
  docs/current-001-node_bootstrap.md
  go.mod
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/export_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cloudconfig/cloudconfig.go
  pkg/eks/nodegroup.go
  pkg/nodebootstrap/README.md
  pkg/nodebootstrap/al2.go
  pkg/nodebootstrap/al2_test.go
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/10-eksclt.al2.conf
  pkg/nodebootstrap/assets/bootstrap.al2.sh
  pkg/nodebootstrap/assets/bootstrap.helper.sh
  pkg/nodebootstrap/assets/bootstrap.ubuntu.sh
  pkg/nodebootstrap/assets/docker-daemon.json
  pkg/nodebootstrap/assets/kubelet.yaml
  pkg/nodebootstrap/bottlerocket.go
  pkg/nodebootstrap/bottlerocket_test.go
  pkg/nodebootstrap/fakes/fake_bootstrapper.go
  pkg/nodebootstrap/managed.go
  pkg/nodebootstrap/maxpods.go
  pkg/nodebootstrap/maxpods_generate.go
  pkg/nodebootstrap/nodebootstrap_suite_test.go
  pkg/nodebootstrap/reserved.go
  pkg/nodebootstrap/reserved_data.go
  pkg/nodebootstrap/reserved_generate.go
  pkg/nodebootstrap/reserved_test.go
  pkg/nodebootstrap/ubuntu.go
  pkg/nodebootstrap/ubuntu_test.go
  pkg/nodebootstrap/userdata.go
  pkg/nodebootstrap/userdata_al2.go
  pkg/nodebootstrap/userdata_test.go
  pkg/nodebootstrap/userdata_ubuntu.go
  pkg/nodebootstrap/userdata_win.go
  pkg/nodebootstrap/userdata_win_test.go
  pkg/nodebootstrap/windows.go
  pkg/nodebootstrap/windows_test.go
Labels: kind/improvement
