Repository eksctl-io/eksctl, pull requests merged in 2021-02, with the labels that each got.

#3168 Set/Unset/Get labels on unowned nodegroups
  Makefile
  go.mod
  go.sum
  integration/tests/params.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/addon/fakes/fake_stack_manager.go
  pkg/actions/label/export_test.go
  pkg/actions/label/fakes/fake_managed_service.go
  pkg/actions/label/get.go
  pkg/actions/label/label.go
  pkg/actions/label/label_suite_test.go
  pkg/actions/label/labels_test.go
  pkg/actions/label/set.go
  pkg/actions/label/unset.go
  pkg/cfn/manager/api.go
  pkg/ctl/get/labels.go
  pkg/ctl/get/labels_test.go
  pkg/ctl/set/labels.go
  pkg/ctl/set/set_test.go
  pkg/ctl/unset/labels.go
  pkg/ctl/unset/unset_test.go
Labels: kind/improvement

#3181 Added fetch-depth to release workflows, small tag-* cleanup
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  build/scripts/tag-common.sh
  build/scripts/tag-release-candidate.sh
  build/scripts/tag-release.sh
Labels: area/build-and-release, autosquash, skip-release-notes

#3135 Refactor iamserviceaccounts
  pkg/actions/irsa/create.go
  pkg/actions/irsa/delete.go
  pkg/actions/irsa/fakes/fake_stack_manager.go
  pkg/actions/irsa/get.go
  pkg/actions/irsa/get_test.go
  pkg/actions/irsa/irsa.go
  pkg/actions/irsa/irsa_suite_test.go
  pkg/actions/irsa/tasks.go
  pkg/actions/irsa/update.go
  pkg/actions/irsa/update_test.go
  pkg/addons/irsa_helper.go
  pkg/addons/vpc_controller.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/iam.go
  pkg/cfn/manager/tasks.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/ctl/update/iamserviceaccount.go
  pkg/eks/tasks.go
Labels: autosquash, kind/bug, technical debt

#3163 Add check for integration tests to release-candidate workflow
  .github/workflows/release-candidate.yaml
Labels: area/build-and-release, autosquash, skip-release-notes

#3170 Support parsing YAML Cloudformation templates
  pkg/cfn/manager/nodegroup_test.go
  pkg/cfn/manager/template.go
  pkg/cfn/manager/template_test.go
Labels: area/general-cli, autosquash, kind/bug

#3187 add fargateprofiles as alias for fargateprofile
  pkg/ctl/get/fargate.go
Labels: skip-release-notes

#3136 Add proposal requirements and template
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  .requirements
  CONTRIBUTING.md
  Dockerfile
  Makefile.docker
  build/docker/build_image_manifest
  build/docker/image_tag
  docs/proposal-000-template.md
  go.mod
  go.sum
  tools.go
Labels: area/docs, skip-release-notes

#3189 Wait longer after setting labels to get them
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: skip-release-notes

#3194 master -> main
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/request-for-help.md
  .github/workflows/check-links.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/update-generated.yaml
  CONTRIBUTING.md
  README.md
  build/scripts/tag-common.sh
  build/scripts/tag-release.sh
Labels: autosquash, skip-release-notes

#3197 remove MinInstancesInService and MaxBatchSize fields
  go.mod
  go.sum
  pkg/cfn/builder/nodegroup.go
Labels: skip-release-notes

#3192 Use printers.TableType constant
  pkg/ctl/get/addon.go
  pkg/ctl/get/cluster.go
  pkg/ctl/get/fargate.go
  pkg/ctl/get/iamidentitymapping.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/ctl/get/nodegroup.go
Labels: autosquash, kind/improvement, skip-release-notes, technical debt

#3200 Update counterfeiter, ginkgo, mockery and github-release
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#3066 Flux v2 support
  Makefile
  examples/12-gitops-toolkit.yaml
  pkg/actions/flux/enable.go
  pkg/actions/flux/enable_test.go
  pkg/actions/flux/export_test.go
  pkg/actions/flux/fakes/fake_flux_client.go
  pkg/actions/flux/flux_suite_test.go
  pkg/actions/repo/enable.go
  pkg/actions/repo/enable_test.go
  pkg/actions/repo/repo_suite_test.go
  pkg/actions/repo/wait.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/create/cluster.go
  pkg/ctl/enable/enable.go
  pkg/ctl/enable/flux.go
  pkg/ctl/enable/flux_test.go
  pkg/ctl/enable/profile.go
  pkg/ctl/enable/profile_test.go
  pkg/ctl/enable/repo.go
  pkg/ctl/enable/repo_test.go
  pkg/ctl/generate/profile.go
  pkg/executor/executor.go
  pkg/executor/fakes/fake_executor.go
  pkg/flux/export_test.go
  pkg/flux/flux.go
  pkg/flux/flux_suite_test.go
  pkg/flux/flux_test.go
  pkg/git/executor/executor.go
  pkg/git/executor/fake_executor.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/gitops/flux/flux_suite_test.go
  pkg/gitops/flux/installer_test.go
  pkg/gitops/flux/wait.go
  pkg/gitops/gitops.go
  pkg/gitops/profile_test.go
  userdocs/src/usage/gitops.md
Labels: kind/feature

#3202 Remove dupe circleci job
  .circleci/config.yml
Labels: skip-release-notes

#3205 Support position name in get iamserviceaccount
  pkg/actions/irsa/get.go
  pkg/actions/irsa/get_test.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/get/iamserviceaccount.go
Labels: kind/bug

#3204 Add documentation how treated tags field of nodegroup
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: autosquash, kind/improvement, skip-release-notes

#3037 Add first draft proposal for apply
  docs/proposal-007-apply.md
Labels: autosquash, skip-release-notes

#3118 Clean up docs workflow
  .github/workflows/check-links.yaml
Labels: skip-release-notes

#3212 Fix bootstrap commands in the examples
  examples/15-managed-nodes.yaml
  examples/22-managed-nodes-launch-template.yaml
  userdocs/src/usage/eks-managed-nodes.md
Labels: kind/docs, skip-release-notes

#3210 ignore ResourceNotFoundException error during cluster deletion
  pkg/actions/cluster/cluster.go
  pkg/eks/eks.go
Labels: area/deletions, kind/improvement

#3186 Detect and log unsupported region error for fully-private clusters
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/vpc_endpoint.go
  pkg/ctl/create/cluster.go
  userdocs/src/usage/eks-private-cluster.md
Labels: kind/improvement

#3206 Add deprecation notice to enable repo command
  go.mod
  go.sum
  pkg/actions/repo/enable.go
  pkg/actions/repo/enable_test.go
  pkg/actions/repo/repo_suite_test.go
  pkg/actions/repo/wait.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/create/cluster.go
  pkg/ctl/enable/enable.go
  pkg/ctl/enable/profile.go
  pkg/ctl/enable/profile_test.go
  pkg/ctl/enable/repo.go
  pkg/ctl/enable/repo_test.go
  pkg/git/git.go
  pkg/git/git_suite_test.go
  pkg/git/git_test.go
  pkg/gitops/deploykey/deploykey.go
  pkg/gitops/fileprocessor/fileprocessor.go
  pkg/gitops/fileprocessor/gotemplates.go
  pkg/gitops/gitops.go
Labels: kind/improvement

#3211 Add integration test for flux v2
  .circleci/config.yml
  .github/workflows/integration-tests.yaml
  integration/matchers/flux.go
  integration/tests/gitops/flux_test.go
  integration/tests/params.go
  integration/tests/quickstart_profiles/quickstart_profiles_test.go
  integration/utilities/git/git.go
  pkg/flux/flux.go
Labels: autosquash, skip-release-notes

#3221 Fix install-build-deps target
  Makefile
Labels: area/build-and-release, autosquash, kind/bug, skip-release-notes

#3223 Restructure unowned_cluster integration tests to improve output
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: area/testing, skip-release-notes

#3225 Clearly point to CoC
  README.md
Labels: autosquash, skip-release-notes

#3218 Fix suspend ASG processes for nodegroups
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/manager/nodegroup.go
  pkg/eks/api.go
  pkg/eks/mocks/AutoScalingAPI.go
  pkg/eks/mocks/mocks.go
  pkg/eks/nodegroup.go
  pkg/eks/tasks.go
  pkg/testutils/mockprovider/mock_provider.go
  pkg/utils/tasks/tasks.go
Labels: autosquash, kind/bug

#3227 Remove unnecessary CheckAuth calls
  integration/tests/crud/creategetdelete_test.go
  integration/tests/inferentia/inferentia_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  integration/tests/update/update_cluster_test.go
  pkg/actions/fargate/create.go
  pkg/actions/nodegroup/create.go
  pkg/ctl/cmdutils/cmd.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/utils.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/iamidentitymapping.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/delete/cluster.go
  pkg/ctl/delete/fargate.go
  pkg/ctl/delete/iamidentitymapping.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/get/cluster.go
  pkg/ctl/get/fargate.go
  pkg/ctl/get/iamidentitymapping.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/ctl/get/labels.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/set/labels.go
  pkg/ctl/unset/labels.go
  pkg/ctl/update/iamserviceaccount.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/ctl/utils/associate_iam_oidc_provider.go
  pkg/ctl/utils/describe_stacks.go
  pkg/ctl/utils/install_vpc_controllers.go
  pkg/ctl/utils/nodegroup_health.go
  pkg/ctl/utils/set_public_access_cidrs.go
  pkg/ctl/utils/update_aws_node.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
  pkg/ctl/utils/update_cluster_logging.go
  pkg/ctl/utils/update_coredns.go
  pkg/ctl/utils/update_kube_proxy.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/ctl/utils/wait_nodes.go
  pkg/ctl/utils/write_kubeconfig.go
  pkg/eks/api.go
  pkg/eks/eks.go
Labels: autosquash, skip-release-notes, technical debt

#3216 use common stackManager interface and fakes across packages
  pkg/actions/addon/addon.go
  pkg/actions/addon/create_test.go
  pkg/actions/addon/delete_test.go
  pkg/actions/addon/fakes/fake_stack_manager.go
  pkg/actions/addon/update_test.go
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/unowned.go
  pkg/actions/fargate/unowned.go
  pkg/actions/irsa/fakes/fake_stack_manager.go
  pkg/actions/irsa/get_test.go
  pkg/actions/irsa/irsa.go
  pkg/actions/irsa/tasks.go
  pkg/actions/irsa/update_test.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/addons/irsa_helper.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/ctl/cmdutils/nodegroup.go
  pkg/eks/api.go
  pkg/eks/compatibility.go
  pkg/eks/nodegroup.go
  pkg/managed/service.go
Labels: autosquash, skip-release-notes, technical debt

#3226 Update site with 2021 roadmap
  CONTRIBUTING.md
  userdocs/src/community.md
  userdocs/src/usage/iamserviceaccounts.md
Labels: autosquash, kind/docs, skip-release-notes

#3222 Fix integration tests
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  integration/matchers/flux.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: autosquash, skip-release-notes

#3239 New team slack channel name
  .circleci/config.yml
Labels: autosquash, skip-release-notes

#3234 make kind/docs a valid label
  .github/workflows/pr-labels.yaml
Labels: skip-release-notes

#3240 Update to kops v1.19.0 and k8s patch version
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: area/build-and-release, autosquash, skip-release-notes

#3241 Add v prefix to eksctl tags
  .circleci/config.yml
  build/scripts/do-release-candidate.sh
  build/scripts/do-release.sh
  build/scripts/tag-release-candidate.sh
  build/scripts/tag-release.sh
Labels: area/build-and-release, autosquash, skip-release-notes

#3242 Only create cluster once in unowned cluster test suite
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: autosquash, skip-release-notes

#3228 Fix creating private cluster in some regions
  pkg/cfn/builder/vpc_endpoint.go
  pkg/cfn/builder/vpc_endpoint_test.go
Labels: kind/bug

#3244 Remove auto merge workflow
  .github/workflows/auto-merge.yaml
Labels: skip-release-notes

#3231 Tidy site
  userdocs/mkdocs.yml
  userdocs/src/community.md
  userdocs/src/examples/reusing-iam-and-vpc.md
  userdocs/src/gitops-quickstart.md
  userdocs/src/usage/emr-access.md
  userdocs/src/usage/gitops.md
Labels: skip-release-notes

#3122 added RoleOnly option for iamserviceaccounts
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/manager/create_tasks.go
  pkg/ctl/cmdutils/filter/iamserviceaccount_filter.go
  pkg/ctl/cmdutils/filter/iamserviceaccount_filter_test.go
  pkg/ctl/create/iamserviceaccount.go
  userdocs/src/usage/iamserviceaccounts.md
Labels: kind/feature

#3250 Temporarily pend gitops integration tests
  integration/tests/gitops/flux_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: skip-release-notes

#3251 always enable timestamps
  cmd/eksctl/main.go
  go.mod
  go.sum
  pkg/ctl/cmdutils/gitops.go
Labels: area/general-cli, kind/improvement

#3257 Bump label timeout again for the last time I promise
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: skip-release-notes

#3254 Support sourceSecurityGroupIds for unmanaged nodegroups
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/testdata/launch_template/ssh_enabled.json
  pkg/cfn/builder/vpc.go
Labels: area/nodegroup, kind/feature

#3258 Make some validation functions private in api package
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/ctl/create/cluster.go
Labels: skip-release-notes, technical debt

#3259 Fix inferentia integration tests
  integration/tests/inferentia/inferentia_test.go
Labels: area/testing, skip-release-notes

#3232 Support secondary CIDR blocks for VPCs
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: area/aws-vpc, kind/bug

#3256 Add option to pass kubeconfig path to Flux 2 installer
  .circleci/config.yml
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  integration/tests/gitops/flux_test.go
  pkg/actions/flux/enable.go
  pkg/actions/flux/enable_test.go
  pkg/actions/flux/fakes/fake_flux_client.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/create/cluster.go
  pkg/flux/flux.go
  pkg/flux/flux_test.go
  pkg/gitops/gitops.go
Labels: kind/improvement

#3261 Update example 5
  examples/05-advanced-nodegroups.yaml
Labels: skip-release-notes

#3262 Don't print all key pairs
  pkg/ssh/client/ssh.go
Labels: area/testing, skip-release-notes, technical debt

#3263 Add release notes for 0.38.0
  docs/release_notes/0.38.0.md
Labels: skip-release-notes

#3265 OIDC support
  cmd/eksctl/main.go
  docs/release_notes/0.38.0.md
  examples/27-oidc-provider.yaml
  go.mod
  go.sum
  pkg/actions/identityproviders/associate.go
  pkg/actions/identityproviders/associate_test.go
  pkg/actions/identityproviders/disassociate.go
  pkg/actions/identityproviders/disassociate_test.go
  pkg/actions/identityproviders/get.go
  pkg/actions/identityproviders/manager.go
  pkg/actions/identityproviders/suite_test.go
  pkg/actions/identityproviders/tasks.go
  pkg/actions/identityproviders/wait.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/identity_provider.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/associate/associate.go
  pkg/ctl/associate/identity_provider.go
  pkg/ctl/cmdutils/builder.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/disassociate/disassociate.go
  pkg/ctl/disassociate/identity_provider.go
  pkg/ctl/disassociate/identity_provider_test.go
  pkg/ctl/get/get.go
  pkg/ctl/get/identityprovider.go
  pkg/eks/mocks/EKSAPI.go
  pkg/eks/tasks.go
Labels: kind/feature

#3233 Update SSH docs
  examples/07-ssh-keys.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/configfile_test.go
  userdocs/src/usage/managing-nodegroups.md
Labels: area/docs, kind/docs

#3275 Fix test that relies on map iteration order
  pkg/vpc/vpc_test.go
Labels: kind/bug

#3279 Fix embedded structs with JSON field in JSON schema
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/schema/definition/definition.go
Labels: kind/bug

#3285 add support for 1.19
  docs/release_notes/0.38.0.md
  integration/tests/addons/addons_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/addon/get.go
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/upgrade.go
  pkg/actions/cluster/upgrade_test.go
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.19.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/elb/cleanup.go
  pkg/elb/ingress.go
  userdocs/src/introduction.md
Labels: kind/feature

#3284 Include wellKnownPolicies in eksctl.io docs
  userdocs/src/usage/iamserviceaccounts.md
Labels: kind/docs, skip-release-notes

#3287 Fix early return from tag-common.sh function
  build/scripts/tag-common.sh
Labels: area/build-and-release, skip-release-notes

#3286 Add support for 1.19
  build/scripts/tag-release.sh
  docs/release_notes/0.38.0.md
  integration/tests/addons/addons_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/addon/get.go
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/upgrade.go
  pkg/actions/cluster/upgrade_test.go
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.19.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/elb/cleanup.go
  pkg/elb/ingress.go
  userdocs/src/introduction.md
  userdocs/src/usage/iamserviceaccounts.md
Labels: skip-release-notes

#3280 support delete addon when only the addon stack exists
  pkg/actions/addon/delete.go
  pkg/actions/addon/delete_test.go
Labels: area/add-ons, kind/feature

#3217 remove unnecessary ctl.Provider references
  pkg/actions/addon/addon.go
  pkg/actions/addon/addon_test.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/actions/addon/delete.go
  pkg/actions/addon/delete_test.go
  pkg/actions/addon/describe_versions.go
  pkg/actions/addon/describe_versions_test.go
  pkg/actions/addon/get.go
  pkg/actions/addon/get_test.go
  pkg/actions/addon/tasks.go
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/actions/fargate/unowned.go
  pkg/actions/label/label.go
  pkg/actions/label/labels_test.go
  pkg/actions/nodegroup/upgrade.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/fargate.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_endpoint.go
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/compat.go
  pkg/cfn/manager/deprecated.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/template.go
  pkg/cfn/manager/waiters.go
  pkg/ctl/create/addon.go
  pkg/ctl/create/cluster.go
  pkg/ctl/delete/addon.go
  pkg/ctl/get/addon.go
  pkg/ctl/get/labels.go
  pkg/ctl/set/labels.go
  pkg/ctl/unset/labels.go
  pkg/ctl/update/addon.go
  pkg/ctl/utils/describe_addon_versions.go
  pkg/ctl/utils/nodegroup_health.go
  pkg/iam/iam.go
  pkg/kops/kops.go
  pkg/managed/service.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: skip-release-notes, technical debt

#3288 Improve main version bumping in release scripts
  build/scripts/tag-common.sh
  build/scripts/tag-release-candidate.sh
  build/scripts/tag-release.sh
Labels: area/build-and-release, skip-release-notes

#3276 add permission boundary to addon role
  pkg/actions/addon/create.go
  pkg/actions/addon/update.go
  pkg/actions/irsa/tasks.go
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_test.go
  pkg/cfn/manager/iam.go
Labels: area/aws-iam, kind/feature

#3277 Make nodegroup CloudFormation stack slimmer
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/vpc.go
Labels: area/nodegroup, kind/improvement

#3292 Change the featureGate "DynamicKubeletConfig" to "TaintBasedEvictions" in the userdoc "Customizing kubelet configuration"
  userdocs/src/usage/customizing-the-kubelet.md
Labels: kind/improvement

#3229 Fix support for specifying subnets without ID
  examples/24-nodegroup-subnets.yaml
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/compat.go
  pkg/ctl/create/cluster.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/bug

#3297 Move managed nodegroup userdata creation to pkg/nodebootstrap
  pkg/cfn/builder/managed_launch_template.go
  pkg/nodebootstrap/managed.go
Labels: skip-release-notes, technical debt

#3299 Add additional test for VPC subnet spec
  pkg/vpc/vpc_test.go
Labels: skip-release-notes, technical debt

#3300 Improve release scripts slightly
  build/scripts/tag-common.sh
  build/scripts/tag-release-candidate.sh
Labels: area/build-and-release, skip-release-notes

#3301 Fix specifying subnets by AZ
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/vpc.go
  pkg/ctl/create/cluster.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/bug

#3305 Fix bug in deleting clusters in unowned_cluster integration test
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: skip-release-notes

#3306 Refactor VPC importing
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/compat.go
  pkg/ctl/create/cluster.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: skip-release-notes, technical debt

#3308 netlify.toml: only build on changes to docs/
  netlify.toml
Labels: area/build-and-release, skip-release-notes

#3302 Restructure release workflow to work through PRs
  .github/workflows/release-candidate.yaml
  .github/workflows/tag-release.yaml
  build/scripts/tag-common.sh
  build/scripts/tag-release-candidate.sh
  build/scripts/tag-release.sh
  pkg/version/generate/release_generate.go
Labels: area/build-and-release, skip-release-notes

#3310 bump upgrade cluster timeout to 65
  pkg/ctl/upgrade/cluster.go
Labels: area/upgrades, kind/improvement

#3319 bump EKS 1.19 coredns to 1.8.0
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.19.json
Labels: kind/improvement

#3296 create clusters in before suites
  integration/tests/addons/addons_test.go
  integration/tests/before_active/createdeletebeforeactive_test.go
  integration/tests/crud/creategetdelete_test.go
  integration/tests/inferentia/inferentia_test.go
  integration/tests/managed/managed_nodegroup_test.go
  integration/tests/update/update_cluster_test.go
Labels: skip-release-notes, technical debt

#3294 Add sample template for new nodegroup CFN format
  pkg/cfn/template/testdata/addon-example-1.json
  pkg/cfn/template/testdata/cluster-example-1.json
  pkg/cfn/template/testdata/cluster-example-2.json
  pkg/cfn/template/testdata/nodegroup-example-1.json
  pkg/cfn/template/testdata/nodegroup-example-old-format-1.json
Labels: skip-release-notes

#3320 Turn off color in integration tests
  integration/main.go
Labels: area/build-and-release, area/testing, skip-release-notes

#3324 Add release notes for 0.39.0
  docs/release_notes/0.39.0.md
Labels: skip-release-notes

#3326 Check tag-* scripts if gh logged in
  build/scripts/tag-common.sh
Labels: area/build-and-release, skip-release-notes

#3331 Allow referring to subnets by ID in nodegroups
  examples/24-nodegroup-subnets.yaml
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/improvement

#3333 Fix run step in aws-nuke github workflow
  .github/workflows/aws-cleanup.yaml
Labels: skip-release-notes

#3332 log suggestion to delete IRSA when create stack fails
  pkg/cfn/manager/iam.go
Labels: skip-release-notes

#3330 add disable-eviction flag for nodegroup drain and delete
  pkg/actions/nodegroup/drain.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/delete/nodegroup_test.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/drain/nodegroup_test.go
  pkg/drain/evictor/evictor.go
  pkg/drain/nodegroup.go
  pkg/drain/nodegroup_test.go
  userdocs/src/usage/managing-nodegroups.md
Labels: area/nodegroup, kind/feature

#3339 Prevent setting internal NodeGroup fields via ClusterConfig
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/schema/definition/definition.go
Labels: kind/bug

#3334 Improve release-drafter replace regex
  .github/release-drafter.yml
Labels: area/build-and-release, skip-release-notes

#3340 Fix netlify.toml publish path
  netlify.toml
Labels: area/build-and-release, skip-release-notes

#3337 Also check managed groups for plugin requirements
  pkg/apis/eksctl.io/v1alpha5/nodegroups.go
  pkg/eks/tasks.go
Labels: kind/bug

#3336 Also push v prefixed tags on release
  .circleci/config.yml
  .github/workflows/tag-release.yaml
Labels: area/build-and-release, skip-release-notes

#3342 Improve error when nodegroup is missing privateNetworking
  pkg/cfn/builder/nodegroup.go
  pkg/vpc/vpc.go
Labels: kind/improvement

#3343 Fix netlify.toml on release branch
  netlify.toml
Labels: area/build-and-release, skip-release-notes

#3346 Creating the FargatePodExecutionRole resource only if a Fargate profile doesn't specify a podExecutionRoleARN
  pkg/cfn/builder/cluster.go
Labels: area/fargate, kind/improvement

#3347 Add support for Asia Pacific (Osaka) region
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/eks/fargate.go
  pkg/fargate/delete.go
  pkg/fargate/fargate.go
  userdocs/src/usage/fargate-support.md
Labels: kind/feature

#3360 Put GH workflow setup in a composite action
  .github/actions/setup-identity/action.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
Labels: area/build-and-release, skip-release-notes

#3361 Move aws-nuke config to .github/
  .github/aws-nuke-config.yaml
  .github/workflows/aws-cleanup.yaml
Labels: area/build-and-release, skip-release-notes

#2688 Add EFA support
  pkg/actions/nodegroup/create.go
  pkg/addons/assets.go
  pkg/addons/assets/efa-device-plugin.yaml
  pkg/addons/device_plugin.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/network_interfaces.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/manager/nodegroup.go
  pkg/ctl/create/cluster.go
  pkg/eks/tasks.go
  pkg/iam/iam.go
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/efa.al2.sh
  pkg/nodebootstrap/assets/efa.managed.boothook
  pkg/nodebootstrap/managed.go
  pkg/nodebootstrap/userdata_al2.go
Labels: area/managed-nodegroup, area/nodegroup, kind/feature

#3363 Link to OIDC example from schema
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/identity_provider.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
Labels: kind/docs, skip-release-notes

#3365 Add slack notifications to integration tests
  .github/actions/notify-slack/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
Labels: area/build-and-release, skip-release-notes

#3364 Support enabling KMS encryption for existing clusters
  docs/release_notes/0.39.0.md
  go.mod
  go.sum
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/cluster.go
  pkg/ctl/cmdutils/kms.go
  pkg/ctl/utils/enable_secrets_encryption.go
  pkg/ctl/utils/utils.go
  pkg/eks/api.go
  pkg/eks/eks_test.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/EKSAPI.go
  pkg/eks/mocks/IAMAPI.go
  pkg/eks/mocks/mocks.go
  pkg/eks/nodegroup.go
  pkg/eks/update.go
  pkg/kubernetes/kms.go
  pkg/testutils/mockprovider/mock_provider.go
  userdocs/src/usage/kms-encryption.md
Labels: kind/feature

#3367 Fix event type quotes in workflow
  .github/workflows/integration-tests.yaml
Labels: area/build-and-release, skip-release-notes

#3368 Notify on failure not success
  .github/workflows/integration-tests.yaml
Labels: area/build-and-release, skip-release-notes
