Repository eksctl-io/eksctl, pull requests merged in 2021-12, with the labels that each got.

#4490 Separate VPC Networking into meaningful sections
  userdocs/mkdocs.yml
  userdocs/src/usage/nodegroup-customize-dns.md
  userdocs/src/usage/vpc-cluster-access.md
  userdocs/src/usage/vpc-configuration.md
  userdocs/src/usage/vpc-networking.md
  userdocs/src/usage/vpc-subnet-settings.md
Labels: kind/docs

#4502 Add `--config-file` to `set labels`
  integration/tests/labels/label_test.go
  integration/tests/labels/testdata/managed-nodegroup-with-labels.yaml
  integration/tests/params.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/test_data/cluster-with-labels.yaml
  pkg/ctl/set/labels.go
  pkg/ctl/set/set_test.go
Labels: kind/feature

#4471 remove flux1 & profiles support
  cmd/eksctl/main.go
  examples/21-eks-quickstart-app-dev.yaml
  integration/matchers/flux.go
  integration/tests/quickstart_profiles/quickstart_profiles_test.go
  integration/tests/quickstart_profiles_gen/quickstart_profiles_gen_test.go
  integration/utilities/git/git.go
  pkg/actions/cluster/owned.go
  pkg/actions/repo/enable.go
  pkg/actions/repo/enable_test.go
  pkg/actions/repo/repo_suite_test.go
  pkg/actions/repo/wait.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/create/cluster.go
  pkg/ctl/enable/enable.go
  pkg/ctl/enable/flux_test.go
  pkg/ctl/enable/profile.go
  pkg/ctl/enable/profile_test.go
  pkg/ctl/enable/repo.go
  pkg/ctl/enable/repo_test.go
  pkg/ctl/generate/generate.go
  pkg/ctl/generate/generate_suite_test.go
  pkg/ctl/generate/generate_test.go
  pkg/ctl/generate/profile.go
  pkg/ctl/generate/profile_test.go
  pkg/git/git.go
  pkg/git/git_suite_test.go
  pkg/git/git_test.go
  pkg/gitops/deploykey/deploykey.go
  pkg/gitops/fileprocessor/fileprocessor.go
  pkg/gitops/fileprocessor/gotemplates.go
  pkg/gitops/gitops.go
  pkg/gitops/gitops_suite_test.go
  pkg/gitops/profile.go
  pkg/gitops/profile_test.go
  pkg/gitops/url.go
  pkg/gitops/url_test.go
  userdocs/mkdocs.yml
  userdocs/src/community.md
  userdocs/src/usage/gitops-v1.md
Labels: components/flux, area/gitops, kind/improvement

#4519 pend failing managed ubuntu integration test
  integration/tests/managed/managed_nodegroup_test.go
Labels: skip-release-notes

#4520 Do not use GetLabels all the time
  pkg/ctl/set/labels.go
Labels: skip-release-notes

#4524 Fix types for Ipv6CidrBlock and Ipv6Pool
  go.mod
  go.sum
  pkg/cfn/builder/vpc_ipv6.go
Labels: kind/bug

#4525 set correct policies when creating vpc-cni addon for ipv6 cluster
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
Labels: kind/improvement

#4488 Create required AWS resources during karpenter installation
  CONTRIBUTING.md
  examples/29-cluster-with-karpenter.yaml
  integration/tests/karpenter/karpenter_test.go
  integration/tests/karpenter/testdata/cluster-config.yaml
  pkg/actions/karpenter/create.go
  pkg/actions/karpenter/create_test.go
  pkg/actions/karpenter/karpenter.go
  pkg/actions/karpenter/karpenter_suite_test.go
  pkg/actions/karpenter/tasks.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/karpenter.go
  pkg/cfn/manager/tasks.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/cluster_test.go
  pkg/karpenter/fakes/fake_chart_installer.go
  pkg/karpenter/karpenter.go
  pkg/karpenter/karpenter_test.go
  pkg/karpenter/providers/fakes/fake_helm_getter.go
  pkg/karpenter/providers/helm.go
  pkg/karpenter/providers/helm/helm.go
  pkg/karpenter/providers/helm/helm_test.go
  userdocs/mkdocs.yml
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/feature

#4521 docs: added missing --region flag in the for nodegroup and iamidentitymapping pages
  userdocs/src/usage/iam-identity-mappings.md
  userdocs/src/usage/nodegroup-upgrade.md
Labels: kind/docs

#4535 New release 0.77.0
  docs/release_notes/0.77.0.md
Labels: skip-release-notes

#4527 update ipv6 integration check to create & test managed nodegroup
  integration/tests/ipv6/ipv6_test.go
Labels: skip-release-notes

#4501 Add integration test for associate, disassociate and get identityprovider
  go.mod
  go.sum
  integration/tests/identity_provider/identity_provider_test.go
  integration/tests/identity_provider/testdata/cluster-role-binding.yaml
  integration/tests/identity_provider/testdata/cluster-role.yaml
Labels: area/testing, kind/improvement, area/tech-debt

#4533 Configure DNS64 and NAT64 for IPv6 subnets
  go.mod
  go.sum
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_ipv6.go
  pkg/cfn/builder/vpc_ipv6_test.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/create_tasks_test.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/eks/mocks/EC2API.go
Labels: kind/improvement

#4216 Automatically attach the correct EBS CSI Driver policies when creating the addon
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
Labels: kind/feature

#4547 Fix ignoring partitions on EBS controller
  pkg/cfn/builder/iam_test.go
  pkg/cfn/builder/statement.go
Labels: kind/bug

#4548 Increase delete wait time
  integration/tests/params.go
Labels: skip-release-notes

#4552 Add release notes for 0.78.0
  docs/release_notes/0.78.0.md
Labels: skip-release-notes

#4556 Update 29-vpc-with-ip-family.yaml
  examples/29-vpc-with-ip-family.yaml
Labels: skip-release-notes

#4531 Do not create service account if Karpenter is enabled to do so
  go.mod
  go.sum
  pkg/actions/addon/create.go
  pkg/actions/karpenter/create.go
  pkg/actions/karpenter/create_test.go
  pkg/actions/karpenter/karpenter.go
  pkg/actions/karpenter/tasks.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
  pkg/ctl/create/cluster.go
  pkg/karpenter/fakes/fake_chart_installer.go
  pkg/karpenter/karpenter.go
  pkg/karpenter/karpenter_test.go
  pkg/karpenter/providers/fakes/fake_helm_installer.go
  pkg/karpenter/providers/fakes/fake_kube_client.go
  pkg/karpenter/providers/helm.go
  pkg/karpenter/providers/helm/helm.go
  pkg/karpenter/providers/helm/helm_test.go
Labels: kind/bug
