Repository eksctl-io/eksctl, pull requests merged in 2021-08, with the labels that each got.

#4025 Add ability to set a custom subnet when creating a nodegroup
  integration/tests/crud/creategetdelete_test.go
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/ctl/cmdutils/cmdutils.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/nodegroup_test.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: area/managed-nodegroup, area/nodegroup, kind/feature

#4045 Fixed deleting the nodegroup test
  integration/tests/crud/creategetdelete_test.go
Labels: kind/bug

#3993 Set new selector session when creating nodegroup
  integration/tests/dry_run/dry_run_test.go
  pkg/actions/nodegroup/create_test.go
  pkg/eks/fakes/fake_nodegroup_initialiser.go
  pkg/eks/nodegroup_service.go
Labels: kind/bug

#4044 Add documentation for the new subnet addition feature
  userdocs/mkdocs.yml
  userdocs/src/usage/nodegroup-with-custom-subnet.md
Labels: kind/docs

#4056 Return message when VPC config missing on unowned ng create
  pkg/actions/nodegroup/create.go
Labels: kind/bug

#4051 Expose nodegroup container runtime configuration
  integration/tests/crud/creategetdelete_test.go
  integration/tests/managed/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/defaults_test.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/cmdutils/test_data/managed-nodegroup-with-container-runtime.yaml
  pkg/nodebootstrap/al2_test.go
  pkg/nodebootstrap/bindata/assets.go
  pkg/nodebootstrap/bindata/assets/bootstrap.al2.sh
  pkg/nodebootstrap/bindata/assets/bootstrap.helper.sh
  pkg/nodebootstrap/userdata.go
  userdocs/mkdocs.yml
  userdocs/src/usage/container-runtime.md
Labels: kind/feature

#4047 Fix Missing Permission in Minimum Permissions Page
  userdocs/src/usage/minimum-iam-policies.md
Labels: kind/docs, skip-release-notes

#4057 add 0.61.0 notes
  docs/release_notes/0.61.0.md
Labels: skip-release-notes

#4064 Set default CONTAINER_RUNTIME in helper script
  integration/tests/dry_run/dry_run_test.go
  pkg/nodebootstrap/bindata/assets.go
  pkg/nodebootstrap/bindata/assets/bootstrap.helper.sh
Labels: kind/bug

#4068 Fix dry run integration tests
  integration/tests/dry_run/dry_run_test.go
Labels: skip-release-notes

#4071 Add note to VPC networking guide about egress IPs
  userdocs/src/usage/vpc-networking.md
Labels: skip-release-notes

#4070 Use schemer pkg for docs
  cmd/schema/generate.go
  go.mod
  go.sum
  pkg/schema/definition/comment.go
  pkg/schema/definition/comment_test.go
  pkg/schema/definition/common.go
  pkg/schema/definition/definition.go
  pkg/schema/definition/enum.go
  pkg/schema/definition/schematypes.go
  pkg/schema/definition/suite_test.go
  pkg/schema/definition/tags.go
  pkg/schema/definition/types.go
  pkg/schema/importer/importer.go
  pkg/schema/schema.go
  pkg/schema/schema_test.go
  pkg/schema/suite_test.go
  pkg/schema/test/subpkg/subpkg.go
  pkg/schema/test/test.go
Labels: kind/docs, skip-release-notes

#4072 Add to 61 rc
  cmd/schema/generate.go
  docs/release_notes/0.61.0.md
  go.mod
  go.sum
  integration/tests/dry_run/dry_run_test.go
  pkg/nodebootstrap/bindata/assets.go
  pkg/nodebootstrap/bindata/assets/bootstrap.helper.sh
  pkg/schema/definition/comment.go
  pkg/schema/definition/comment_test.go
  pkg/schema/definition/common.go
  pkg/schema/definition/definition.go
  pkg/schema/definition/enum.go
  pkg/schema/definition/schematypes.go
  pkg/schema/definition/suite_test.go
  pkg/schema/definition/tags.go
  pkg/schema/definition/types.go
  pkg/schema/importer/importer.go
  pkg/schema/schema.go
  pkg/schema/schema_test.go
  pkg/schema/suite_test.go
  pkg/schema/test/subpkg/subpkg.go
  pkg/schema/test/test.go
  userdocs/src/usage/vpc-networking.md
Labels: skip-release-notes

#4076 Deprecate all Flux v1 commands
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/enable/flux.go
  pkg/ctl/enable/profile.go
  pkg/ctl/enable/repo.go
  pkg/ctl/generate/generate.go
  pkg/ctl/generate/profile.go
  userdocs/src/usage/gitops-v1.md
Labels: kind/improvement

#4086 use eksbuild.1 for kube-proxy on 18 and older
  pkg/addons/default/kube_proxy.go
Labels: kind/bug

#4089 Remove gitops docs links in types
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/docs, skip-release-notes

#4085 update AWS node to 1.9
  pkg/addons/default/assets.go
  pkg/addons/default/assets/aws-node.yaml
  pkg/addons/default/aws_node_generate.go
Labels: kind/improvement

#4091 revert back to build.1 for kube-proxy addon versions
  pkg/addons/default/kube_proxy.go
Labels: kind/bug

#4090 Add notes for 62
  docs/release_notes/0.62.0.md
Labels: skip-release-notes

#4092 fix panic for getting an individual nodegroup
  pkg/actions/nodegroup/get.go
Labels: kind/bug

#4099 update ebs-csi-driver policy
  pkg/cfn/builder/statement.go
Labels: kind/improvement

#3989 Deprecate `ssh.enableSsm` and disallow enabling it
  .github/workflows/integration-tests.yaml
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/custom_ami.json
  pkg/cfn/builder/testdata/launch_template/launch_template.json
  pkg/cfn/builder/testdata/launch_template/launch_template_custom_ami.json
  pkg/cfn/builder/testdata/launch_template/lt_instance_types.json
  pkg/cfn/builder/testdata/launch_template/placement.json
  pkg/cfn/builder/testdata/launch_template/spot.json
  pkg/cfn/builder/testdata/launch_template/standard.json
  pkg/ctl/cmdutils/cmd.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/nodegroup_test.go
  pkg/eks/nodegroup_service.go
  pkg/nodebootstrap/al2.go
  pkg/nodebootstrap/al2_test.go
  pkg/nodebootstrap/legacy/al2.go
  pkg/nodebootstrap/managed_al2.go
  pkg/nodebootstrap/managed_al2_test.go
  userdocs/src/introduction.md
Labels: kind/improvement

#4095 Removed update-cluster-stack cmd
  pkg/ctl/utils/update_cluster_stack.go
  pkg/ctl/utils/utils.go
Labels: technical debt, kind/improvement

#4103 Fix setting EnableSSM when a config file is not specified
  pkg/ctl/cmdutils/configfile.go
Labels: kind/bug, skip-release-notes

#4105 Fix dry-run integration tests
  integration/tests/dry_run/dry_run_test.go
Labels: kind/bug, skip-release-notes

#4098 Fetch instance type from launch template in `eksctl get nodegroups`
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/get_test.go
Labels: kind/improvement

#4109 Remove SSM option from CRUD tests
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#4112 Add release notes for 0.63
  docs/release_notes/0.63.0.md
Labels: kind/docs, skip-release-notes

#4116 Use a unique changeset name when updating addons
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
Labels: kind/bug

#4083 Add support for preserving addons
  go.mod
  go.sum
  integration/tests/addons/addons_test.go
  pkg/actions/addon/delete.go
  pkg/actions/addon/delete_test.go
  pkg/ctl/delete/addon.go
  pkg/eks/mocks/CloudFormationAPI.go
  pkg/eks/mocks/EC2API.go
Labels: kind/feature

#4118 Update release notes for 0.63
  README.md
  docs/release_notes/0.63.0.md
  userdocs/src/index.md
Labels: skip-release-notes

#4121 Update merged work and release notes for `0.63.0-rc.1`
  README.md
  docs/release_notes/0.63.0.md
  go.mod
  go.sum
  integration/tests/addons/addons_test.go
  pkg/actions/addon/delete.go
  pkg/actions/addon/delete_test.go
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/ctl/delete/addon.go
  pkg/eks/mocks/CloudFormationAPI.go
  pkg/eks/mocks/EC2API.go
  pkg/version/release.go
  userdocs/src/index.md
Labels: skip-release-notes

#4127 Update 0.63 release version for rc.1
  pkg/version/release.go
Labels: skip-release-notes

#4104 Bump vpc-resource-controller/webhook dep to v0.2.6
  pkg/addons/assets.go
  pkg/addons/assets/vpc-admission-webhook-dep.yaml
  pkg/addons/assets/vpc-resource-controller-dep.yaml
Labels: kind/improvement

#4065 Add preBootstrapCommands to userdata when using customAMI
  pkg/nodebootstrap/managed_al2.go
  pkg/nodebootstrap/managed_al2_test.go
Labels: kind/bug

#4124 Fix markdown issue in "Managing nodegroups" user docs
  userdocs/src/usage/managing-nodegroups.md
Labels: area/docs, skip-release-notes

#4132 Fix `make update-build-image-tag`
  Makefile.docker
Labels: skip-release-notes

#4131 Bump dependencies
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#4128 Fix creating Windows nodegroups in fully-private clusters
  pkg/nodebootstrap/userdata.go
  pkg/nodebootstrap/windows.go
  pkg/nodebootstrap/windows_test.go
Labels: kind/bug

#4134 Fix !!!info block so that it properly renders
  userdocs/src/usage/minimum-iam-policies.md
Labels: kind/bug

#4148 Fix deprecation warning
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/ctl/cmdutils/cmd.go
Labels: kind/bug

#4149 Update release notes
  docs/release_notes/0.64.0.md
Labels: skip-release-notes
