Repository eksctl-io/eksctl, pull requests merged in 2021-07, with the labels that each got.

#3915 Revert hiding `updateconfig`
  examples/15-managed-nodes.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/update/nodegroup.go
  pkg/ctl/update/nodegroup_test.go
  pkg/ctl/update/update.go
  userdocs/src/usage/eks-managed-nodes.md
Labels: skip-release-notes

#3921 Fix OIDC tags test
  pkg/iam/oidc/api_test.go
Labels: kind/bug, skip-release-notes

#3914 `Update` command can update multiple nodegroups
  integration/tests/managed/managed_nodegroup_test.go
  pkg/actions/nodegroup/update.go
  pkg/actions/nodegroup/update_test.go
  pkg/ctl/cmdutils/configfile.go
Labels: kind/feature, technical debt

#3923 Fix UpdateConfig error message to pass integration test
  integration/tests/managed/managed_nodegroup_test.go
Labels: skip-release-notes

#3920 Avoid cn-north-1d
  pkg/az/az.go
Labels: kind/bug, kind/hack

#3924 Ensure GPU AMI is used when using multiple instances
  pkg/eks/api.go
  pkg/eks/instance_selection_test.go
Labels: kind/bug

#3922 Write release notes for 0.56.0
  docs/release_notes/0.56.0.md
Labels: skip-release-notes

#3930 Do not fail on valid flag combinations for managed ngs
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/create/nodegroup_test.go
Labels: kind/bug

#3890 bump deps
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/eks/mocks/CloudFormationAPI.go
  pkg/eks/mocks/EC2API.go
Labels: skip-release-notes

#3938 Add new note for 56-rc
  docs/release_notes/0.56.0.md
Labels: skip-release-notes

#3943 Make EKS 1.20 the default
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/introduction.md
Labels: kind/improvement

#3945 reduce integration tests to every 12 hours
  .github/workflows/integration-tests.yaml
Labels: skip-release-notes

#3939 fix unsupported versions
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: skip-release-notes

#3952 Remove `--config-file` flag from `upgrade nodegroup`
  pkg/ctl/upgrade/nodegroup.go
Labels: kind/bug

#3954 Refactor CLI tests
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/create_test.go
  pkg/ctl/create/iamserviceaccount_test.go
  pkg/ctl/create/nodegroup_test.go
Labels: kind/improvement, skip-release-notes

#3948 Add stack status UpdateComplete as valid scenario
  pkg/cfn/waiter/stack.go
Labels: kind/improvement

#3951 Fix cfssl build issue after go mod tidy
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  .requirements
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  build/scripts/build-image-manifest.sh
  build/scripts/install-build-deps.sh
  go.mod
  go.sum
Labels: kind/bug

#3947 Use zone ID instead of zone name to avoid problematic zones
  pkg/az/az.go
  pkg/az/az_test.go
  pkg/eks/api.go
Labels: kind/bug

#3942 Cloudformation stack validation error because of underscore in EKS cluster name
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/nodegroup_test.go
  pkg/ctl/get/cluster.go
  userdocs/src/usage/creating-and-managing-clusters.md
  userdocs/src/usage/unowned-clusters.md
Labels: kind/bug

#3958 Fix Config file schema docs page horizontal scroll
  userdocs/src/usage/schema.css
  userdocs/src/usage/schema.md
Labels: kind/bug

#3956 Fix --wait issue for eksctl upgrade nodegroup command
  pkg/actions/nodegroup/upgrade.go
  pkg/ctl/upgrade/nodegroup.go
Labels: kind/bug

#3960 Fix panic for `get nodegroup`
  pkg/actions/nodegroup/get.go
Labels: kind/bug, priority/important-soon

#3964 Write release notes for 0.57.0
  docs/release_notes/0.57.0.md
Labels: skip-release-notes

#3905 Remove k8s.io/kubernetes dependency by using k8s.io/kubelet
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/testdata/one_cluster.golden
  pkg/utils/kubeconfig/testdata/one_cluster_with_stale_context.golden
  pkg/utils/kubeconfig/testdata/one_cluster_without_context.golden
  pkg/utils/kubeconfig/testdata/two_clusters.golden
Labels: skip-release-notes

#3953 Add support for configuring extra CIDRs for Control Plane SG
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/vpc.go
  userdocs/src/usage/vpc-networking.md
Labels: area/aws-vpc, kind/feature

#3897 Make managed nodegroups the default in `create cluster` and `create nodegroup`
  README.md
  integration/tests/dry_run/dry_run_test.go
  integration/tests/inferentia/inferentia_test.go
  integration/tests/managed/managed_nodegroup_test.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/nodegroup_test.go
  userdocs/src/usage/creating-and-managing-clusters.md
  userdocs/src/usage/dry-run.md
  userdocs/src/usage/eks-managed-nodes.md
  userdocs/src/usage/instance-selector.md
  userdocs/src/usage/managed-nodegroups-announcement.md
  userdocs/src/usage/managing-nodegroups.md
  userdocs/src/usage/nodegroup-upgrade.md
  userdocs/src/usage/spot-instances.md
  userdocs/src/usage/windows-worker-nodes.md
  userdocs/theme/main.html
Labels: area/general-cli, area/managed-nodegroup, kind/improvement

#3980 Bump deps
  go.mod
  go.sum
  pkg/eks/mocks/EC2API.go
  pkg/eks/mocks/EKSAPI.go
Labels: skip-release-notes

#3990 pin p2.xlarge instance test to not use us-west-2d
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#3991 add 0.58.0 release notes
  docs/release_notes/0.58.0.md
Labels: skip-release-notes

#3937 Add support for kubernetes 1.21
  integration/tests/addons/addons_test.go
  integration/tests/dry_run/dry_run_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/cluster/upgrade.go
  pkg/actions/cluster/upgrade_test.go
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.21.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/introduction.md
Labels: kind/feature

#3994 pin cluster to same zones as nodes
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#3992 Filter out GPU instances when --instance-selector-gpus=0
  integration/tests/instance_selector/instance_selector_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/eks/nodegroup_service.go
Labels: kind/bug

#4001 Document Minimal required IAM Policies for EKS Cluster Creation Upfront
  README.md
Labels: kind/docs, skip-release-notes

#4008 Update documentation about how to upgrade default Add-Ons
  userdocs/src/usage/addon-upgrade.md
  userdocs/src/usage/cluster-upgrade.md
Labels: area/docs, kind/docs

#4012 bump golang to 1.16.6
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
Labels: kind/improvement

#4013 add 0.59 release notes
  docs/release_notes/0.59.0.md
Labels: skip-release-notes

#4016 bump cirecle ubuntu image
  .circleci/config.yml
Labels: skip-release-notes

#3962 Fix --version flag issue for create managed nodegroup command
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/create/nodegroup_test.go
  userdocs/src/usage/managing-nodegroups.md
Labels: kind/bug, kind/improvement

#4005 Add <namespace>/<pod> to pod eviction errors
  pkg/drain/nodegroup.go
Labels: kind/improvement

#4023 install py3-setuptools to fix http binary
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
Labels: dependencies, skip-release-notes

#4033 Add notes for 0.60.0
  docs/release_notes/0.60.0.md
Labels: skip-release-notes
