Repository eksctl-io/eksctl, pull requests merged in 2021-11, with the labels that each got.

#4379 Use string instead of string pointer for IPFamily
  integration/tests/ipv6/ipv6_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/vpc_ipv6_test.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/cmdutils/configfile.go
Labels: skip-release-notes

#4391 update aws-node
  pkg/addons/default/assets/aws-node.yaml
Labels: kind/improvement

#4366 reduce API calls in upgrade cluster
  pkg/actions/cluster/cluster.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/fargate/create_test.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/eks/eks.go
Labels: kind/improvement

#4393 clarify up-to-date nodegroup message
  pkg/eks/nodegroup_service.go
Labels: skip-release-notes

#4392 Clean up generation of aws-node manifest
  Makefile
Labels: skip-release-notes, area/tech-debt

#4394 make kubernetes 1.21 default
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/introduction.md
Labels: kind/improvement

#4390 Add support for Windows Server 20H2
  integration/tests/windows/windows_test.go
  pkg/ami/auto_resolver.go
  pkg/ami/ssm_resolver.go
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  userdocs/src/usage/custom-ami-support.md
  userdocs/src/usage/windows-worker-nodes.md
Labels: kind/feature

#4335 bump vpc-resource-controller/webhook dep to v0.2.7
  pkg/addons/assets/vpc-admission-webhook-dep.yaml
  pkg/addons/assets/vpc-resource-controller-dep.yaml
Labels: kind/improvement

#4383 Scale managed nodegroup with --name flag
  pkg/actions/nodegroup/scale.go
  pkg/actions/nodegroup/scale_test.go
  pkg/apis/eksctl.io/v1alpha5/nodegroups.go
  pkg/ctl/cmdutils/scale.go
  pkg/ctl/cmdutils/scale_test.go
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/scale/nodegroup_test.go
Labels: kind/bug

#4247 remove aws-cleanup and integration workflows
  .github/actions/notify-slack/action.yaml
  .github/aws-nuke-config.yaml
  .github/workflows/aws-cleanup.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
Labels: skip-release-notes

#4295 Support CloudWatch log retention
  examples/11-cloudwatch-cluster-logging.yaml
  integration/tests/cloudwatch_logging/cloudwatch_logging_test.go
  integration/tests/cloudwatch_logging/testdata/cloudwatch-cluster.yaml
  integration/tests/cluster_dns/cluster_dns_test.go
  integration/tests/crud/creategetdelete_test.go
  integration/tests/managed/managed_nodegroup_test.go
  integration/utilities/cluster/cluster.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/cloudwatch.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/eks/api.go
  pkg/eks/mocks/CloudWatchLogsAPI.go
  pkg/eks/mocks/mocks.go
  pkg/eks/tasks.go
  pkg/testutils/mockprovider/mock_provider.go
  pkg/testutils/testutils.go
Labels: kind/feature

#4405 Fix Windows integration test
  integration/tests/windows/windows_test.go
Labels: kind/bug, skip-release-notes

#4409 fix panic in cloudwatch validation
  pkg/apis/eksctl.io/v1alpha5/validation.go
Labels: skip-release-notes

#4410 bump gjson
  go.mod
  go.sum
Labels: skip-release-notes

#4401 Fix wait for managed nodegroups #3889
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/actions/irsa/tasks.go
  pkg/actions/irsa/update_test.go
  pkg/actions/nodegroup/upgrade.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/api_test.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/compat.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/managed/service.go
Labels: kind/bug

#4411 Unpin and fix containerd integration test
  integration/tests/crud/creategetdelete_test.go
Labels: kind/bug

#4413 pend failing windows test
  integration/tests/windows/windows_test.go
Labels: skip-release-notes

#4380 Update to kops v1.21.2
  go.mod
  go.sum
Labels: kind/improvement

#4418 Add release notes for 0.73.0
  docs/release_notes/0.73.0.md
Labels: skip-release-notes

#4424 Revert "Tag 0.73.0-rc.0 release candidate"
  pkg/version/release.go
Labels: skip-release-notes

#4403 Fix validation for GPU instance types when AMIFamily is not set
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
Labels: kind/bug

#4397 Avoid writing temp ClusterConfig file
  integration/tests/gitops/flux_test.go
Labels: kind/improvement, skip-release-notes

#4412 add support for setting extraIPv6CIDRs
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  userdocs/src/usage/vpc-networking.md
Labels: kind/feature, area/ipv6

#4378 User can create a new VPC with a custom IPv6 CIDR
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/vpc_ipv4_test.go
  pkg/cfn/builder/vpc_ipv6.go
  pkg/cfn/builder/vpc_ipv6_test.go
  userdocs/src/usage/vpc-networking.md
Labels: kind/feature, area/ipv6

#4422 Bump GoReleaser to 0.184.0
  build/docker/build_image_manifest
  go.mod
  go.sum
Labels: skip-release-notes

#4415 Private IPv6 VPC
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/vpc_ipv4.go
  pkg/cfn/builder/vpc_ipv6.go
  pkg/cfn/builder/vpc_ipv6_test.go
  userdocs/src/usage/vpc-networking.md
Labels: kind/feature

#4435 update build image
  .github/workflows/ci.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/image_tag
Labels: skip-release-notes

#4436 Set volume size in data volume for Bottlerocket
  pkg/ami/ami_test.go
  pkg/ami/api.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/cfn/builder/block_device_mapping.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/bottlerocket.json
  pkg/cfn/builder/testdata/launch_template/bottlerocket_volume.json
Labels: kind/bug

#4442 Unpend and fix Windows integration tests
  integration/tests/windows/windows_test.go
Labels: kind/bug

#4356 Add support for Windows IPAM
  examples/14-windows-nodes.yaml
  integration/tests/windows/windows_test.go
  pkg/apis/eksctl.io/v1alpha5/nodegroups.go
  pkg/ctl/create/cluster.go
  pkg/eks/tasks.go
  pkg/windows/ipam.go
  pkg/windows/ipam_test.go
  userdocs/src/usage/windows-worker-nodes.md
Labels: kind/feature

#4450 Add release notes for 0.74
  docs/release_notes/0.74.0.md
Labels: skip-release-notes

#4456 Document logs:PutRetentionPolicy in IAM policies doc
  userdocs/src/usage/minimum-iam-policies.md
Labels: kind/docs

#4460 Fix update logic in iam service account
  pkg/kubernetes/serviceaccount.go
  pkg/kubernetes/serviceaccount_test.go
Labels: kind/bug

#4465 Add config-file option to get nodegroup
  pkg/ctl/get/nodegroup.go
  pkg/ctl/get/nodegroup_test.go
Labels: kind/feature

#4440 Improve kube-proxy updating to always get the latest version&build #4344
  integration/tests/update/update_cluster_test.go
  pkg/actions/nodegroup/create.go
  pkg/addons/default/addons.go
  pkg/addons/default/assets_test.go
  pkg/addons/default/aws_node.go
  pkg/addons/default/aws_node_test.go
  pkg/addons/default/coredns.go
  pkg/addons/default/coredns_test.go
  pkg/addons/default/helpers.go
  pkg/addons/default/helpers_test.go
  pkg/addons/default/kube_proxy.go
  pkg/addons/default/kube_proxy_test.go
  pkg/addons/default/testdata/sample-1.15-eksbuild.1.json
  pkg/addons/default/testdata/sample-1.15-invalid-image.json
  pkg/ctl/utils/update_aws_node.go
  pkg/ctl/utils/update_coredns.go
  pkg/ctl/utils/update_kube_proxy.go
  pkg/testutils/client.go
Labels: area/add-ons, kind/improvement

#4469 Add --config-flag to get labels
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/get/labels.go
  pkg/ctl/get/labels_test.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/get/nodegroup_test.go
Labels: kind/feature

#4467 Bump goreleaser to `v1.0`
  .github/workflows/ci.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: kind/bug, skip-release-notes

#4398 Add support for using existing VPC for ipv6 cluster
  integration/tests/existing_vpc/cf-template.yaml
  integration/tests/existing_vpc/existing_vpc_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/cfn/builder/vpc_existing.go
  pkg/cfn/builder/vpc_existing_test.go
  pkg/cfn/builder/vpc_ipv4.go
  pkg/cfn/builder/vpc_ipv4_test.go
Labels: kind/feature

#4470 Fixed the config naming check error
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/get/nodegroup_test.go
Labels: skip-release-notes

#4472 add 0.75 release notes
  docs/release_notes/0.75.0.md
Labels: skip-release-notes

#4473 ensure vpc-cni version is atleast 1.10.0 when ipv6 is configured
  examples/29-vpc-with-ip-family.yaml
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/vpc_existing_test.go
  userdocs/src/usage/vpc-networking.md
Labels: kind/improvement

#4479 Update cluster-upgrade.md
  userdocs/src/usage/cluster-upgrade.md
Labels: kind/docs

#4331 Add AttachPolicy to NodeGroupIAM configuration
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup_test.go
  userdocs/src/usage/iam-policies.md
Labels: kind/feature

#4468 Add config-file option to get cluster
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/get/cluster.go
  pkg/ctl/get/cluster_test.go
  pkg/ctl/get/nodegroup_test.go
  pkg/eks/mocks/KubeNodeGroup.go
Labels: kind/feature

#4464 Support scaling all nodegroups found in a config file
  integration/tests/crud/creategetdelete_test.go
  integration/tests/crud/testdata/scale-nodegroups.yaml
  integration/tests/crud/testdata/taints-max-pods.yaml
  pkg/ctl/cmdutils/scale.go
  pkg/ctl/cmdutils/scale_test.go
  pkg/ctl/cmdutils/test_data/scale-all-ng-test.yaml
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/scale/nodegroup_test.go
  userdocs/src/usage/managing-nodegroups.md
Labels: kind/feature

#4480 Karpenter install
  go.mod
  go.sum
  pkg/actions/karpenter/karpenter.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/karpenter.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/karpenter.go
  pkg/cfn/manager/tasks.go
  pkg/ctl/create/cluster.go
  pkg/karpenter/karpenter.go
  pkg/karpenter/karpenter_suite_test.go
  pkg/karpenter/karpenter_test.go
  pkg/karpenter/providers/fakes/fake_helm_getter.go
  pkg/karpenter/providers/fakes/fake_helm_installer.go
  pkg/karpenter/providers/helm.go
  pkg/karpenter/providers/helm/helm.go
  pkg/karpenter/providers/helm/helm_suite_test.go
  pkg/karpenter/providers/helm/helm_test.go
  pkg/karpenter/providers/helm/testdata/karpenter-0.4.3.tgz
  pkg/karpenter/providers/helm/testdata/karpenter-index-no-version.yaml
  pkg/karpenter/providers/helm/testdata/karpenter-index.yaml
  pkg/utils/tasks/tasks.go
Labels: kind/feature

#4487 Remove support for EKS 1.17
  pkg/actions/cluster/upgrade_test.go
  pkg/addons/default/assets/coredns-1.17.json
  pkg/addons/default/coredns_test.go
  pkg/addons/default/testdata/sample-1.17.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/eks/mocks/KubeNodeGroup.go
  userdocs/src/introduction.md
Labels: kind/feature

#4491 Fix panic in node affinity adder
  pkg/addons/default/kube_proxy.go
  pkg/addons/default/kube_proxy_test.go
  pkg/addons/default/testdata/sample-old-kube-proxy-amd.json
Labels: kind/bug

#4494 Add release notes for 0.76.0
  docs/release_notes/0.76.0.md
Labels: skip-release-notes

#4497 Add integration test for `utils schema`
  integration/tests/utils/utils_test.go
Labels: kind/feature

#4492 Add integration test for `describe-stacks`
  integration/tests/crud/creategetdelete_test.go
Labels: kind/improvement

#4489 Deprecate golint and apply some changes from revive
  .golangci.yml
  integration/tests/backwards_compat/backwards_compatibility_test.go
  integration/tests/before_active/createdeletebeforeactive_test.go
  integration/tests/cloudwatch_logging/cloudwatch_logging_test.go
  integration/tests/cluster_api/cluster_api_endpoints_test.go
  integration/tests/cluster_dns/cluster_dns_test.go
  integration/tests/dry_run/dry_run_test.go
  integration/tests/eks_connector/eks_connector_test.go
  integration/tests/instance_selector/instance_selector_test.go
  integration/tests/quickstart_profiles_gen/quickstart_profiles_gen_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/identityproviders/wait.go
  pkg/actions/nodegroup/create.go
  pkg/actions/repo/enable.go
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/network_interfaces.go
  pkg/ctl/cmdutils/nodegroup.go
  pkg/ctl/create/cluster.go
  pkg/ctl/enable/flux.go
  pkg/ctl/get/identityprovider.go
  pkg/ctl/scale/nodegroup.go
  pkg/eks/eks.go
  pkg/git/git.go
  pkg/printers/table.go
  pkg/version/generate/release_generate.go
  pkg/vpc/vpc.go
Labels: kind/feature
