Repository eksctl-io/eksctl, pull requests merged in 2021-04, with the labels that each got.

#3512 use random cluster name in dry run integration test
  integration/tests/dry_run/dry_run_test.go
Labels: skip-release-notes

#3511 eksctl scale nodegroups supports only providing one of min/max/desired size
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/ctl/cmdutils/scale.go
  pkg/ctl/cmdutils/scale_test.go
  pkg/ctl/scale/nodegroup_test.go
Labels: skip-release-notes

#3530 bump integration base timeouts
  integration/tests/fargate/fargate_test.go
  integration/tests/params.go
Labels: skip-release-notes

#3526 Make EKS 1.19 the default
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/api_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/introduction.md
Labels: kind/improvement

#3519 fix(types.go): add capacity-optimized-prioritized (#3516)
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  userdocs/src/usage/spot-instances.md
Labels: area/nodegroup, kind/feature

#3533 Fix dry-run test
  integration/tests/dry_run/dry_run_test.go
Labels: skip-release-notes

#3527 Add documentation for dry-run
  userdocs/src/usage/creating-and-managing-clusters.md
Labels: skip-release-notes

#3515 Get nodegroup desired capacity from autoscaling instead of cloudformation
  pkg/cfn/manager/api.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/testutils/mockprovider/mock_provider.go
Labels: kind/feature

#3535 Add unit tests for instance selector
  pkg/actions/nodegroup/create.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/create/cluster.go
  pkg/eks/api.go
  pkg/eks/fakes/fake_instance_selector.go
  pkg/eks/nodegroup_service.go
  pkg/eks/nodegroup_service_test.go
  pkg/testutils/mockprovider/mock_provider.go
Labels: area/testing, skip-release-notes

#3542 Add instance selector doc to navbar
  userdocs/mkdocs.yml
Labels: skip-release-notes

#3549 Support comma separated array for group flag in create iamidentitymapping
  pkg/ctl/create/iamidentitymapping.go
Labels: kind/bug

#3548 Preserve capabilities when creating changeset
  pkg/cfn/manager/api.go
Labels: kind/improvement

#3547 Bump deps and build image
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/cfn/builder/api_matchers_test.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/iam_test.go
  pkg/eks/mocks/EC2API.go
Labels: skip-release-notes

#3544 Support passing releaseVersion for Managed Nodegroups
  pkg/actions/nodegroup/upgrade.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/managed/service.go
  userdocs/src/usage/eks-managed-nodes.md
Labels: kind/feature

#3543 Use the AutoScalingGroup for getting & scaling the nodegroups
  pkg/actions/nodegroup/export_test.go
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/scale.go
  pkg/actions/nodegroup/scale_test.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
Labels: kind/improvement

#3550 Add release notes for 45
  docs/release_notes/0.45.0.md
Labels: skip-release-notes

#3555 Bump goreleaser timeout to 60m
  build/scripts/do-release-candidate.sh
Labels: skip-release-notes

#3554 Fix error message
  pkg/actions/cluster/unowned.go
Labels: skip-release-notes

#3557 Revert bootstrap changes
  docs/current-001-node_bootstrap.md
  docs/release_notes/0.45.0.md
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/export_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cloudconfig/cloudconfig.go
  pkg/eks/nodegroup.go
  pkg/nodebootstrap/README.md
  pkg/nodebootstrap/al2.go
  pkg/nodebootstrap/al2_test.go
  pkg/nodebootstrap/assets.go
  pkg/nodebootstrap/assets/10-eksclt.al2.conf
  pkg/nodebootstrap/assets/bootstrap.al2.sh
  pkg/nodebootstrap/assets/bootstrap.helper.sh
  pkg/nodebootstrap/assets/bootstrap.ubuntu.sh
  pkg/nodebootstrap/assets/docker-daemon.json
  pkg/nodebootstrap/assets/kubelet.yaml
  pkg/nodebootstrap/fakes/fake_bootstrapper.go
  pkg/nodebootstrap/managed.go
  pkg/nodebootstrap/maxpods.go
  pkg/nodebootstrap/maxpods_generate.go
  pkg/nodebootstrap/nodebootstrap_suite_test.go
  pkg/nodebootstrap/reserved.go
  pkg/nodebootstrap/reserved_data.go
  pkg/nodebootstrap/reserved_generate.go
  pkg/nodebootstrap/reserved_test.go
  pkg/nodebootstrap/ubuntu.go
  pkg/nodebootstrap/ubuntu_test.go
  pkg/nodebootstrap/userdata.go
  pkg/nodebootstrap/userdata_al2.go
  pkg/nodebootstrap/userdata_bottlerocket.go
  pkg/nodebootstrap/userdata_bottlerocket_test.go
  pkg/nodebootstrap/userdata_test.go
  pkg/nodebootstrap/userdata_ubuntu.go
  pkg/nodebootstrap/userdata_win.go
  pkg/nodebootstrap/userdata_win_test.go
  pkg/nodebootstrap/windows.go
  pkg/nodebootstrap/windows_test.go
Labels: skip-release-notes

#3576 set unowned cluster KMS integration tests to pending
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: skip-release-notes

#3578 add force option to eksctl delete cluster
  pkg/actions/cluster/cluster.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/unowned_test.go
  pkg/ctl/delete/cluster.go
Labels: area/deletions, kind/improvement

#3581 Fix KMS test on unowned clusters
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: kind/bug

#3570 Add flag that allows skipping add-on compatibility checks during creation of ARM nodegroups
  pkg/actions/nodegroup/create.go
  pkg/ctl/create/nodegroup.go
Labels: kind/feature

#3585 add force suggestion to addon creation
  pkg/actions/addon/create.go
Labels: area/add-ons, kind/improvement

#3582 add --wait flag for eksctl create/update addon
  integration/tests/addons/addons_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/addon/addon.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/actions/addon/export_test.go
  pkg/actions/addon/tasks.go
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/ctl/create/addon.go
  pkg/ctl/update/addon.go
Labels: area/add-ons, kind/feature

#3590 Bump goreleaser timeout for releases this time
  build/scripts/do-release.sh
Labels: skip-release-notes

#3593 Revert "Merge pull request #3587 from weaveworks/release-0.45-0b4e8323"
  pkg/version/release.go
Labels: skip-release-notes

#3518 Add well-known IAM Role Service Account policy for the EBS CSI driver
  examples/13-iamserviceaccounts.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/well_known_iam_policy.go
  pkg/cfn/builder/iam_helper.go
  userdocs/src/usage/iamserviceaccounts.md
Labels: kind/improvement

#3592 InstanceSelector only returns instances supported in the provided AZs
  integration/tests/dry_run/dry_run_test.go
  pkg/actions/nodegroup/create.go
  pkg/ctl/create/cluster.go
  pkg/eks/nodegroup_service.go
  pkg/eks/nodegroup_service_test.go
Labels: kind/improvement

#3602 Check instance types are set in get nodegroups
  pkg/actions/nodegroup/get.go
Labels: area/managed-nodegroup, kind/bug

#3589 Refactor cfn template tests
  .golangci.yml
  pkg/cfn/builder/api_suite_test.go
  pkg/cfn/builder/api_test.go
  pkg/cfn/builder/builder_suite_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/export_test.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_endpoint.go
  pkg/cfn/builder/vpc_test.go
Labels: skip-release-notes, technical debt

#3607 Fix typo
  userdocs/src/usage/iam-permissions-boundary.md
Labels: kind/docs

#3605 Update IAMServiceaccount uses a unique changeset name to allow successive updates
  go.mod
  go.sum
  pkg/actions/irsa/tasks.go
  pkg/actions/irsa/update_test.go
Labels: kind/bug

#3567 Removed deprecated labels for 1.19+ clusters
  integration/data/windows-server-iis.yaml
  pkg/addons/assets.go
  pkg/addons/assets/vpc-admission-webhook-dep.yaml
  pkg/addons/assets/vpc-resource-controller-dep.yaml
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.19.json
  pkg/addons/default/kube_proxy.go
  userdocs/src/usage/windows-worker-nodes.md
Labels: kind/bug

#3603 move any commit job to github actions
  .circleci/config.yml
  .github/workflows/test-and-build.yaml
  Makefile
Labels: skip-release-notes

#3609 add 0.46.0 release notes
  docs/release_notes/0.46.0.md
Labels: skip-release-notes

#3612 Fix get nodegroups from stack that failed to delete
  pkg/cfn/manager/nodegroup.go
Labels: kind/improvement

#3608 Load env from host into Flux exec
  pkg/actions/flux/enable.go
  pkg/executor/executor.go
  pkg/flux/flux.go
  pkg/flux/flux_test.go
Labels: kind/improvement

#3586 Add test for KMS encryption
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: area/testing, skip-release-notes

#3619 neuron: use the proper tutorial link
  pkg/eks/tasks.go
Labels: kind/bug

#3622 Correctly parse --install-nvidia/neuron-plugin flags
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
Labels: kind/bug

#3615 Handle race condition in Fargate profile creation
  pkg/eks/fargate.go
Labels: area/fargate, kind/improvement

#3624 add 0.47.0 release notes
  docs/release_notes/0.47.0.md
Labels: skip-release-notes

#3634 Bump all the deps
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  Makefile.docker
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/eks/mocks/AutoScalingAPI.go
  pkg/eks/mocks/EC2API.go
  pkg/eks/mocks/SSMAPI.go
Labels: skip-release-notes

#3598 Add valid entries of `cloudWatch.clusterLogging.enableTypes` to schema
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/cloudwatch.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/defaults_test.go
  pkg/apis/eksctl.io/v1alpha5/schema.go
Labels: kind/docs

#3628 Update VPC controllers to v0.2.5
  pkg/addons/assets.go
  pkg/addons/assets/vpc-admission-webhook-dep.yaml
  pkg/addons/assets/vpc-resource-controller-dep.yaml
Labels: kind/improvement

#3643 Addon create and update respects general timeout flag
  pkg/actions/addon/addon.go
  pkg/actions/addon/addon_test.go
  pkg/actions/addon/create_test.go
  pkg/actions/addon/delete_test.go
  pkg/actions/addon/describe_versions_test.go
  pkg/actions/addon/get_test.go
  pkg/actions/addon/tasks.go
  pkg/actions/addon/update_test.go
  pkg/ctl/create/addon.go
  pkg/ctl/create/cluster.go
  pkg/ctl/delete/addon.go
  pkg/ctl/get/addon.go
  pkg/ctl/update/addon.go
  pkg/ctl/utils/describe_addon_versions.go
Labels: kind/improvement

#3639 Propagate user defined tags to instance and volumes in EKS nodes
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/custom_ami.json
  pkg/cfn/builder/testdata/launch_template/placement.json
  pkg/cfn/builder/testdata/launch_template/spot.json
  pkg/cfn/builder/testdata/launch_template/ssh_disabled.json
  pkg/cfn/builder/testdata/launch_template/ssh_enabled.json
  pkg/cfn/builder/testdata/launch_template/standard.json
Labels: kind/improvement

#3641 Fix delete iamserviceaccount, where sa name is overwritten by paralle…
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/tasks.go
Labels: kind/bug

#3648 Add release notes for 48
  docs/release_notes/0.48.0.md
Labels: skip-release-notes
