Repository eksctl-io/eksctl, pull requests merged in 2021-09, with the labels that each got.

#4155 bump go-releaser
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#4165 Update to go 1.17
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  integration/main.go
  integration/matchers/flux.go
  integration/matchers/git.go
  integration/runner/runner_test.go
  integration/tests/addons/addons_test.go
  integration/tests/backwards_compat/backwards_compatibility_test.go
  integration/tests/before_active/createdeletebeforeactive_test.go
  integration/tests/cluster_api/cluster_api_endpoints_test.go
  integration/tests/cluster_dns/cluster_dns_test.go
  integration/tests/crud/creategetdelete_test.go
  integration/tests/dry_run/dry_run_test.go
  integration/tests/fargate/fargate_test.go
  integration/tests/gitops/flux_test.go
  integration/tests/inferentia/inferentia_test.go
  integration/tests/instance_selector/instance_selector_test.go
  integration/tests/managed/managed_nodegroup_test.go
  integration/tests/params.go
  integration/tests/quickstart_profiles/quickstart_profiles_test.go
  integration/tests/quickstart_profiles_gen/quickstart_profiles_gen_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  integration/tests/update/update_cluster_test.go
  integration/tests/windows/windows_test.go
  integration/utilities/git/git.go
  integration/utilities/kube/kube.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/version/generate/release_generate.go
  pkg/version/generate/release_generate_test.go
Labels: skip-release-notes

#4167 use secure jwt package
  go.mod
  go.sum
Labels: skip-release-notes

#4169 remote unsecure jwt package
  go.mod
Labels: skip-release-notes

#4170 add 0.65.0 release notes
  docs/release_notes/0.65.0.md
Labels: skip-release-notes

#4175 bump cfssl to latest master to remove insecure jwt package
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#4160 TaintBasedEvictions feature flag no longer needed as of 1.18
  userdocs/src/usage/customizing-the-kubelet.md
Labels: skip-release-notes

#4176 Bump goreleaser, cfssl and gh cli
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#4174 Add support for running external plugin
  cmd/eksctl/main.go
  integration/tests/anywhere/anywhere_run_test.go
  integration/tests/params.go
  pkg/actions/anywhere/anywhere.go
  pkg/actions/anywhere/anywhere_suite_test.go
  pkg/actions/anywhere/anywhere_test.go
  pkg/actions/anywhere/testdata/eksctl-anywhere.tar.gz
Labels: kind/feature, blocked/aws

#4178 update goreleaser v0.177.0 in 0.65 release
  .github/workflows/ci.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#4179 add 0.66.0 notes
  docs/release_notes/0.66.0.md
Labels: skip-release-notes

#4182 only trigger goreleaser once
  build/scripts/do-release-candidate.sh
  build/scripts/do-release.sh
Labels: skip-release-notes

#4183 fix plugin integration test
  integration/tests/anywhere/anywhere_run_test.go
Labels: skip-release-notes

#4186 fix download previous release script
  integration/scripts/download-previous-release.sh
Labels: skip-release-notes

#4159 Add func for lax parsing of YAML data
  pkg/kubernetes/manifests.go
  pkg/kubernetes/manifests_test.go
  pkg/kubernetes/testdata/list-with-comment-nodes.yaml
Labels: kind/improvement

#4193 add 0.67.0 notes
  docs/release_notes/0.67.0.md
Labels: skip-release-notes

#4196 don't issue describe cluster call in eksctl utils describe-addon-vers…
  pkg/ctl/utils/describe_addon_versions.go
Labels: skip-release-notes

#4201 Delete IAM role if RegisterCluster fails
  pkg/connector/connector.go
  pkg/connector/connector_test.go
  pkg/ctl/register/cluster.go
Labels: kind/improvement

#4187 import service role during upgrade cluster
  pkg/cfn/manager/cluster.go
Labels: kind/bug

#4207 Increase timeout in Fargate tests
  integration/tests/fargate/fargate_test.go
Labels: kind/bug, area/fargate, skip-release-notes

#4161 Add support for specifying wellKnownPolicies when using addons
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/addon_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/iam.go
Labels: kind/feature

#4194 Add token cache for MFA users and credentials
  integration/tests/caching/credential_caching_test.go
  pkg/credentials/credentials_suite_test.go
  pkg/credentials/fakes/fake_clock.go
  pkg/credentials/filecache.go
  pkg/credentials/filecache_test.go
  pkg/eks/api.go
  userdocs/src/introduction.md
Labels: kind/feature

#4220 Add validation to fix gitops field panic
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/enable/flux_test.go
Labels: kind/bug

#4222 Added new documentation for eksctl anywhere
  userdocs/mkdocs.yml
  userdocs/src/usage/eksctl-anywhere.md
Labels: kind/feature

#4224 Bump nuke action timeout
  .github/workflows/aws-cleanup.yaml
Labels: skip-release-notes

#4225 Do not run integration tests on Sunday
  .github/workflows/integration-tests.yaml
Labels: skip-release-notes

#4209 Use new manifests for EKS Connector
  integration/tests/eks_connector/eks_connector_test.go
  pkg/connector/connector.go
  pkg/connector/connector_test.go
  pkg/connector/kubernetes.go
  pkg/connector/manifest_test.go
  pkg/connector/resources_test.go
  pkg/connector/testdata/eks-connector-binding-expected.yaml
  pkg/connector/testdata/eks-connector-binding.yaml
  pkg/connector/testdata/eks-connector-clusterrole-expected.yaml
  pkg/connector/testdata/eks-connector-clusterrole.yaml
  pkg/connector/testdata/eks-connector-console-dashboard-full-access-group-expected.yaml
  pkg/connector/testdata/eks-connector-console-dashboard-full-access-group.yaml
  pkg/connector/testdata/eks-connector-expected.yaml
  pkg/connector/testdata/eks-connector.yaml
  pkg/ctl/deregister/cluster.go
  pkg/ctl/register/cluster.go
  userdocs/src/usage/eks-connector.md
Labels: kind/improvement

#4226 Update release notes for 0.67
  docs/release_notes/0.67.0.md
Labels: skip-release-notes

#4227 Release 0.67
  .github/workflows/aws-cleanup.yaml
  .github/workflows/integration-tests.yaml
  docs/release_notes/0.67.0.md
  integration/tests/caching/credential_caching_test.go
  integration/tests/eks_connector/eks_connector_test.go
  integration/tests/fargate/fargate_test.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/addons/default/assets.go
  pkg/addons/default/assets/aws-node.yaml
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/addon_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/iam.go
  pkg/cfn/manager/cluster.go
  pkg/connector/connector.go
  pkg/connector/connector_test.go
  pkg/connector/kubernetes.go
  pkg/connector/manifest_test.go
  pkg/connector/resources_test.go
  pkg/connector/testdata/eks-connector-binding-expected.yaml
  pkg/connector/testdata/eks-connector-binding.yaml
  pkg/connector/testdata/eks-connector-clusterrole-expected.yaml
  pkg/connector/testdata/eks-connector-clusterrole.yaml
  pkg/connector/testdata/eks-connector-console-dashboard-full-access-group-expected.yaml
  pkg/connector/testdata/eks-connector-console-dashboard-full-access-group.yaml
  pkg/connector/testdata/eks-connector-expected.yaml
  pkg/connector/testdata/eks-connector.yaml
  pkg/credentials/credentials_suite_test.go
  pkg/credentials/fakes/fake_clock.go
  pkg/credentials/filecache.go
  pkg/credentials/filecache_test.go
  pkg/ctl/cmdutils/gitops.go
  pkg/ctl/deregister/cluster.go
  pkg/ctl/enable/flux_test.go
  pkg/ctl/register/cluster.go
  pkg/eks/api.go
  pkg/version/release.go
  userdocs/mkdocs.yml
  userdocs/src/introduction.md
  userdocs/src/usage/eks-connector.md
  userdocs/src/usage/eksctl-anywhere.md
Labels: skip-release-notes

#4232 Update documentation for EKS Connector
  userdocs/src/usage/eks-connector.md
Labels: kind/improvement

#4233 Fix typo in warning message for existing service accounts.
  pkg/ctl/create/iamserviceaccount.go
Labels: kind/improvement

#4231 Add support for EC2 detailed monitoring in nodeGroup
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
Labels: kind/feature

#3944 Remove support for 1.16
  pkg/actions/cluster/upgrade_test.go
  pkg/addons/default/assets.go
  pkg/addons/default/assets/coredns-1.15.json
  pkg/addons/default/assets/coredns-1.16.json
  pkg/addons/default/coredns_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/improvement

#4205 Drain nodegroups during cluster deletion
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/unowned.go
  pkg/actions/nodegroup/drain.go
  pkg/ctl/cmdutils/nodegroup.go
  pkg/ctl/cmdutils/nodegroup_test.go
  pkg/ctl/delete/nodegroup.go
Labels: kind/bug, technical debt, area/deletions, kind/improvement

#4244 Gracefully delete vpc-cni during cluster deletion
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/unowned_test.go
Labels: kind/improvement

#4248 Add notes for 68
  docs/release_notes/0.68.0.md
Labels: skip-release-notes

#4253 Skip addons task when no addon is configured
  pkg/ctl/create/cluster.go
Labels: kind/improvement
