Repository eksctl-io/eksctl, pull requests merged in 2021-10, with the labels that each got.

#4218 Enable create iamidentitymapping in AWS CN partition
  pkg/authconfigmap/service_access.go
  pkg/ctl/create/iamidentitymapping.go
Labels: kind/bug

#4265 Add release notes for 0.69
  docs/release_notes/0.69.0.md
Labels: skip-release-notes

#4258 add support for specifying latest version in cluster config
  integration/tests/addons/addons_test.go
  pkg/ctl/create/cluster.go
Labels: kind/improvement

#4293 pend failing integration test
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#4292 Add ipFamily to config
  examples/29-vpc-with-ip-family.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/usage/vpc-networking.md
Labels: kind/feature

#4296 Change ip to IP and update schema description
  examples/29-vpc-with-ip-family.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/schema.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/usage/vpc-networking.md
Labels: kind/feature

#4290 Parse task log to be more human readable
  pkg/cfn/manager/tasks_test.go
  pkg/utils/tasks/tasks.go
  pkg/utils/tasks/tasks_test.go
Labels: kind/feature

#4297 Managed addons check
  examples/29-vpc-with-ip-family.yaml
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  userdocs/src/usage/vpc-networking.md
Labels: kind/feature

#4298 Add OIDC check for ipv6 cluster
  examples/29-vpc-with-ip-family.yaml
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  userdocs/src/usage/vpc-networking.md
Labels: kind/feature
