Repository eksctl-io/eksctl, pull requests merged in 2022-02, with the labels that each got.

#4727 wait for karpenter stack to be deleted
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/owned_test.go
Labels: skip-release-notes

#4728 Improve GitHub workflow names
  .github/workflows/link-checker.yaml
  .github/workflows/lint.yaml
Labels: skip-release-notes, area/tech-debt

#4729 Updated minimum IAM policies
  userdocs/src/usage/minimum-iam-policies.md
Labels: skip-release-notes

#4730 Add `list-integration-suites` make command for listing integration suites
  Makefile
Labels: area/testing, skip-release-notes

#4724 Return AMI ID in `get nodegroup` for MNGs using custom AMIs
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/get_test.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
Labels: kind/feature

#4733 add more instance types to GPU integration test
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#4725 Allow additional volume mappings
  integration/tests/assertions.go
  integration/tests/crud/creategetdelete_test.go
  integration/tests/managed/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/defaults_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/block_device_mapping.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes.json
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes_missing_size.json
  userdocs/mkdocs.yml
  userdocs/src/usage/nodegroup-additional-volume-mappings.md
Labels: kind/feature

#4742 Make the error clearer that a public subnet is required
  pkg/vpc/vpc.go
Labels: kind/bug

#4739 Automatically detect role-name when iamserviceaccount update happens
  pkg/actions/addon/update_test.go
  pkg/actions/irsa/update.go
  pkg/actions/irsa/update_test.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_test.go
  pkg/cfn/manager/iam.go
  pkg/cfn/outputs/api.go
  pkg/ctl/update/iamserviceaccount.go
Labels: kind/bug

#4743 Revert "Automatically detect role-name when iamserviceaccount update happens"
  pkg/actions/addon/update_test.go
  pkg/actions/irsa/update.go
  pkg/actions/irsa/update_test.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_test.go
  pkg/cfn/manager/iam.go
  pkg/cfn/outputs/api.go
  pkg/ctl/update/iamserviceaccount.go
Labels: skip-release-notes

#4744 Automatically detect role-name when iamserviceaccount update happens
  pkg/actions/addon/update_test.go
  pkg/actions/irsa/update.go
  pkg/actions/irsa/update_test.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/iam_test.go
  pkg/cfn/manager/iam.go
  pkg/cfn/outputs/api.go
  pkg/ctl/update/iamserviceaccount.go
Labels: kind/bug

#4737 Show nodegroup type in get nodegroup
  integration/tests/crud/creategetdelete_test.go
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/get_test.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/ctl/get/nodegroup.go
Labels: kind/feature

#4738 deprecate albIngress field and replace with awsLoadBalancerController
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
Labels: kind/improvement

#4761 Fix dry-run integration tests
  integration/tests/dry_run/dry_run_test.go
Labels: kind/bug, skip-release-notes

#4759 Remove DeleteStackByName*
  pkg/actions/addon/delete.go
  pkg/actions/addon/delete_test.go
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/irsa/update.go
  pkg/actions/irsa/update_test.go
  pkg/addons/irsa_helper.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/ctl/update/iamserviceaccount.go
  pkg/fargate/delete.go
  pkg/fargate/fargate_test.go
Labels: kind/feature

#4767 Added analytics for eksctl docs
  userdocs/theme/partials/header.html
Labels: kind/feature, kind/docs, skip-release-notes

#4773 Fix GA tag ID
  userdocs/theme/partials/header.html
Labels: kind/docs, skip-release-notes

#4765 Migrate release jobs to GitHub Actions
  .circleci/config.yml
  .github/workflows/docker-publish.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-candidate.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/publish-release.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-build.yaml
  Dockerfile
  build/scripts/do-release-candidate.sh
  build/scripts/do-release.sh
Labels: kind/improvement, area/tech-debt

#4770 refactor AZ package to be simpler
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/az/az.go
  pkg/az/az_test.go
  pkg/eks/api.go
Labels: skip-release-notes

#4776 Add release notes for 0.84
  docs/release_notes/0.84.0.md
Labels: skip-release-notes

#4772 Another reduction of describe via reducing the number of list calls
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/unowned.go
  pkg/actions/nodegroup/delete.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/actions/nodegroup/upgrade.go
  pkg/actions/nodegroup/upgrade_test.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup.go
  pkg/ctl/cmdutils/nodegroup.go
  pkg/managed/service.go
Labels: kind/feature

#4780 Removed unused template variable
  pkg/cfn/manager/api.go
  pkg/cfn/manager/nodegroup.go
Labels: kind/feature

#4782 Move list clusters into cluster pkg and add tests
  pkg/actions/cluster/export_test.go
  pkg/actions/cluster/fakes/fake_aws_provider.go
  pkg/actions/cluster/fakes/fake_stack_provider.go
  pkg/actions/cluster/get.go
  pkg/actions/cluster/get_test.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/cfn/manager/tasks_test.go
  pkg/cfn/manager/template_test.go
  pkg/ctl/get/cluster.go
  pkg/eks/eks.go
  pkg/eks/eks_test.go
Labels: skip-release-notes

#4786 Fix tag filter for release workflow
  .github/workflows/publish-release-candidate.yaml
Labels: kind/bug, skip-release-notes

#4788 Revert "Prepare for next development iteration"
  docs/release_notes/0.84.0.md
  pkg/version/release.go
Labels: skip-release-notes

#4792 Use bash interpreter in release scripts
  build/scripts/do-release-candidate.sh
  build/scripts/do-release.sh
Labels: kind/bug, skip-release-notes

#4795 Pass GitHub token to release scripts
  .github/workflows/publish-release-type.yaml
Labels: skip-release-notes, area/ci

#4781 Added MaxInstanceLifetime for unmanaged nodegroups
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
Labels: kind/feature

#4800 Pass secrets to release workflow
  .github/workflows/publish-release-candidate.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/publish-release.yaml
  docs/release_notes/0.84.0.md
Labels: skip-release-notes

#4791 log region for every command and improve help message
  pkg/ctl/associate/identity_provider.go
  pkg/ctl/cmdutils/cmd.go
  pkg/ctl/cmdutils/cmdutils.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/iamidentitymapping.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/delete/cluster.go
  pkg/ctl/delete/iamidentitymapping.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/disassociate/identity_provider.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/get/addon.go
  pkg/ctl/get/cluster.go
  pkg/ctl/get/fargate.go
  pkg/ctl/get/iamidentitymapping.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/ctl/get/identityprovider.go
  pkg/ctl/get/labels.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/set/labels.go
  pkg/ctl/unset/labels.go
  pkg/ctl/update/iamserviceaccount.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/utils/associate_iam_oidc_provider.go
  pkg/ctl/utils/describe_stacks.go
  pkg/ctl/utils/enable_secrets_encryption.go
  pkg/ctl/utils/update_aws_node.go
  pkg/ctl/utils/update_cluster_logging.go
  pkg/ctl/utils/update_coredns.go
  pkg/ctl/utils/update_kube_proxy.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/ctl/utils/write_kubeconfig.go
Labels: kind/improvement

#4751 Add support for Karpenter defaultInstanceProfile setting
  pkg/actions/karpenter/create.go
  pkg/actions/karpenter/create_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
  pkg/karpenter/fakes/fake_chart_installer.go
  pkg/karpenter/karpenter.go
  pkg/karpenter/karpenter_test.go
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/feature

#4798 Removed the cache as essentially it is not needed in most cases
  pkg/actions/cluster/cluster.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/fargate/create_test.go
  pkg/ctl/delete/cluster.go
  pkg/eks/api.go
  pkg/eks/cache.go
  pkg/eks/eks.go
  pkg/eks/eks_test.go
  pkg/eks/update.go
Labels: kind/feature

#4343 Dump logs to disk on failure
  .gitignore
  cmd/eksctl/logger.go
  cmd/eksctl/main.go
  integration/tests/dump_logs/dumplogs_test.go
Labels: kind/feature

#4768 Updated the deprecated link checker
  .github/workflows/exclude-file.txt
  .github/workflows/link-checker.yaml
  .github/workflows/markdown-link-check-config.json
  COMMUNITY.md
  docs/guidelines/design-conventions.md
  docs/proposal-008-flux2.md
  userdocs/src/index.md
  userdocs/src/usage/nodegroup-customize-dns.md
  userdocs/src/usage/vpc-networking.md
Labels: kind/improvement, skip-release-notes, area/ci

#4825 remove deprecated field that breaks `upgrade nodegroup` timeout value
  pkg/ctl/cmdutils/cmd.go
  pkg/ctl/cmdutils/cmdutils.go
Labels: kind/bug

#4819 Add support for more Graviton instance types
  pkg/utils/instance/instance.go
Labels: kind/feature

#4826 allow case insensitivity for AMIFamily
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/ctl/cmdutils/cmd.go
Labels: kind/improvement

#4830 Allow AWS_PROFILE env var to be used write-kubeconig
  pkg/ctl/cmdutils/cmdutils.go
Labels: kind/bug

#4805 Fix all Karpenter issues for the new 0.6.2 version
  examples/29-cluster-with-karpenter.yaml
  pkg/actions/karpenter/create.go
  pkg/actions/karpenter/create_test.go
  pkg/actions/karpenter/tasks.go
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
  pkg/karpenter/karpenter.go
  pkg/karpenter/karpenter_test.go
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/bug

#4828 Move some validation functions to standard `ValidateClusterConfig` validation function
  pkg/actions/nodegroup/create.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/utils/enable_secrets_encryption.go
  pkg/eks/api.go
  pkg/eks/eks.go
  pkg/eks/eks_test.go
  pkg/eks/nodegroup.go
Labels: skip-release-notes, area/tech-debt

#4829 set userId prefix when creating clusters
  integration/tests/params.go
Labels: skip-release-notes

#4831 add docs on vpc-cni permission boundaries
  userdocs/src/usage/iam-permissions-boundary.md
Labels: kind/docs, kind/bug

#4809 Add support for Bottlerocket nodgroups with NVIDIA accelerated hardware
  pkg/ami/ssm_resolver.go
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/eks/tasks.go
  pkg/utils/instance/instance.go
  userdocs/src/usage/gpu-support.md
Labels: kind/feature, area/nodegroup, bottlerocket

#4839 Update the karpenter version for the integration test
  integration/tests/karpenter/testdata/cluster-config.yaml
Labels: skip-release-notes

#4840 Fix cluster api endpoint test
  integration/tests/cluster_api/cluster_api_endpoints_test.go
Labels: skip-release-notes

#4836 move build-all-distros to github actions
  .github/workflows/build-all-distros-nightly.yaml
Labels: skip-release-notes

#4834 Fix aws-iam-authenticator api version in kube config file
  pkg/utils/kubeconfig/export_test.go
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_suite_test.go
  pkg/utils/kubeconfig/kubeconfig_test.go
  pkg/utils/kubeconfig/testdata/aws-iam-authenticator
Labels: kind/feature, kind/bug

#4841 set build image version in build-all-distros
  .github/workflows/build-all-distros-nightly.yaml
Labels: skip-release-notes

#4835 add support for ed25519
  pkg/ssh/client/assets/id_ed25519_tests1.pub
  pkg/ssh/client/assets/invalid.pub
  pkg/ssh/client/ssh.go
  pkg/ssh/client/ssh_test.go
Labels: kind/bug

#4843 Fix bug preventing update addon from setting stack name
  pkg/cfn/manager/api.go
Labels: kind/bug

#4842 check if ClusterEndpoint is set before mutating
  pkg/ctl/cmdutils/configfile.go
Labels: skip-release-notes

#4844 remove circleci
  .circleci/config.yml
  Makefile
  README.md
  userdocs/src/index.md
Labels: skip-release-notes

#4845 Fix Karpenter integration test
  integration/tests/karpenter/karpenter_test.go
  integration/tests/params.go
  pkg/ctl/create/cluster.go
Labels: skip-release-notes

#4846 remove circleci doc
  CONTRIBUTING.md
Labels: skip-release-notes

#4848 Starting release procedure for 0.86.0
  docs/release_notes/0.86.0.md
Labels: skip-release-notes

#4854 Fix backwards compatibility check test
  integration/scripts/download-previous-release.sh
Labels: skip-release-notes

#4808 Fix cache misses in GitHub Actions workflows
  .github/workflows/cache-dependencies.yaml
  .github/workflows/lint.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
Labels: kind/bug
