Repository eksctl-io/eksctl, pull requests merged in 2022-05, with the labels that each got.

#5198 Bundling dependabot PRs
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#5190 Small tweaks to top banner in docs
  userdocs/src/extra.css
  userdocs/theme/main.html
Labels: kind/docs, skip-release-notes

#5208 Bundling dependabot PRs
  go.mod
  go.sum
Labels: skip-release-notes

#5201 Support Karpenter version `0.9.0`
  examples/29-cluster-with-karpenter.yaml
  integration/tests/karpenter/testdata/cluster-config.yaml
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/feature, area/karpenter

#5187 Support AWS Local Zones
  examples/33-local-zones.yaml
  pkg/actions/nodegroup/create.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/vpc_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_subnets_test.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/cfn/builder/vpc_existing.go
  pkg/cfn/builder/vpc_ipv4.go
  pkg/cfn/builder/vpc_ipv6.go
  pkg/cfn/builder/vpc_ipv6_test.go
  pkg/cfn/outputs/api.go
  pkg/ctl/create/cluster.go
  pkg/eks/api.go
  pkg/kops/kops.go
  pkg/vpc/importer.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
  pkg/vpc/zone.go
Labels: kind/feature

#5218 Fix not checking for missing stack error
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/get_test.go
Labels: kind/bug

#5223 Added release notes for 0.97
  docs/release_notes/0.97.0.md
Labels: skip-release-notes

#5151 Trim equal sign suffix from AWS ed25519 encoded fingerprint
  pkg/ssh/client/ssh.go
  pkg/ssh/client/ssh_test.go
Labels: kind/bug

#5227 Workflow update for dependabot
  .github/dependabot.yml
Labels: skip-release-notes

#5242 Bundling dependabot PRs
  go.mod
  go.sum
Labels: skip-release-notes

#5243 Grouping dependabot updates for github actions
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/rebase.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/stale.yml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
Labels: skip-release-notes

#5245 Migrate integration tests over to aws-go-sdk-v2
  go.mod
  go.sum
  integration/matchers/cloudformation.go
  integration/matchers/config.go
  integration/matchers/matchers.go
  integration/matchers/session.go
  integration/tests/assertions.go
  integration/tests/before_active/createdeletebeforeactive_test.go
  integration/tests/cloudwatch_logging/cloudwatch_logging_test.go
  integration/tests/cluster_api/cluster_api_endpoints_test.go
  integration/tests/crud/creategetdelete_test.go
  integration/tests/identity_provider/identity_provider_test.go
  integration/tests/ipv6/ipv6_test.go
  integration/tests/kms/kms_test.go
  integration/tests/managed/managed_nodegroup_test.go
  integration/tests/override_bootstrap/override_bootstrap_test.go
  integration/tests/update/update_cluster_test.go
Labels: skip-release-notes

#5253 Adding release notes for 0.98.0
  docs/release_notes/0.98.0.md
Labels: skip-release-notes

#5249 Add integration tests for AWS Local Zones
  integration/tests/local_zones/local_zones_test.go
  integration/tests/local_zones/testdata/local-zones.yaml
  integration/utilities/cluster/cluster.go
Labels: area/testing, skip-release-notes

#5261 Fix selecting subnet IDs from subnet names
  pkg/cfn/builder/nodegroup_subnets_test.go
  pkg/vpc/vpc.go
Labels: kind/bug

#5252 Theme updates to eksctl docs
  userdocs/mkdocs.yml
  userdocs/requirements.txt
  userdocs/src/announcements/managed-nodegroups-announcement.md
  userdocs/src/announcements/nodegroup-override-announcement.md
  userdocs/src/index.md
  userdocs/src/stylesheets/extra.css
  userdocs/src/stylesheets/schema.css
  userdocs/theme/main.html
  userdocs/theme/partials/copyright.html
  userdocs/theme/partials/header.html
Labels: kind/improvement, area/docs

#5278 Bundling dependabot PRs
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/cache-dependencies.yaml
  .github/workflows/docker-publish.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/rebase.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
  go.mod
  go.sum
Labels: skip-release-notes

#5284 Make INTEGRATION_TEST_FOCUS value work again
  Makefile
  integration/main.go
  pkg/eks/mocks/KubeNodeGroup.go
Labels: kind/bug

#5286 Fix ASG tag propagation
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/tasks_test.go
Labels: kind/bug

#5290 Added a greetings workflow
  .github/workflows/greetings.yml
Labels: skip-release-notes

#5296 Release notes
  docs/release_notes/0.99.0.md
Labels: skip-release-notes

#5293 Fix what counts as ARM GPU instance type
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/utils/instance/instance.go
Labels: kind/bug

#5283 Add dependabot-bundler as triggerable action to the project
  .github/workflows/dependabot-bundler.yaml
Labels: skip-release-notes

#5288 Detect kubectl version during kubeconfig generation and avoid known non-working configurations
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
  pkg/utils/kubeconfig/testdata/fake-version
Labels: kind/improvement

#5316 Update dependabot bundler
  .github/workflows/dependabot-bundler.yaml
Labels: skip-release-notes

#5322 Pass ClusterConfig via stdin instead of writing to temp files
  integration/tests/cluster_api/cluster_api_endpoints_test.go
  integration/tests/existing_vpc/existing_vpc_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: technical debt, area/testing, skip-release-notes

#5287 Fix eksctl utils write-config breaks in kubectl 1.24
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
Labels: kind/bug

#5330 Add p4de instance types to EFA plugin
  pkg/addons/assets/efa-device-plugin.yaml
Labels: kind/feature

#5332 Add release notes for 0.100
  docs/release_notes/0.100.0.md
Labels: skip-release-notes

#5146 Parallel drain all nodegroups
  pkg/actions/nodegroup/drain.go
  pkg/drain/nodegroup.go
  pkg/drain/nodegroup_test.go
Labels: kind/feature, area/nodegroup

#5354 Update the labels the dependanbot applies to PRs it creates
  .github/workflows/dependabot-bundler.yaml
Labels: skip-release-notes, dependencies
