Repository eksctl-io/eksctl, pull requests merged in 2022-10, with the labels that each got.

#5634 Make Kubernetes 1.23 the default
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/introduction.md
Labels: kind/improvement

#5735 Updates to karpenter cloudformation policies
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
Labels: kind/improvement, area/karpenter

#5752 Setup identity as weaveworks bot before triggering Netlify deployment
  .github/workflows/publish-docs.yaml
Labels: kind/bug

#5761 Release notes for 0.115.0
  docs/release_notes/0.115.0.md
Labels: skip-release-notes

#5758 Updated deps and increased open pull request limit for dependabot PRs
  .github/dependabot.yml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  .golangci.yml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/actions/addon/create.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/awsapi/elasticloadbalancingv2.go
  pkg/awsapi/outposts.go
  pkg/ctl/completion/completion_test.go
  pkg/drain/nodegroup.go
  pkg/ssh/client/ssh.go
  pkg/testutils/mockprovider/mock_provider.go
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/vpc/vpc_test.go
Labels: skip-release-notes

#5753 Partially remove aws sdk go v1 dependencies
  pkg/actions/karpenter/create.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/authconfigmap/authconfigmap.go
  pkg/cfn/builder/iam_helper.go
  pkg/cfn/builder/nodegroup_subnets_test.go
  pkg/cfn/manager/api_test.go
  pkg/connector/arn.go
  pkg/connector/connector.go
  pkg/eks/api.go
  pkg/eks/eks.go
  pkg/eks/mocks/AutoScalingAPI.go
  pkg/eks/mocks/CloudFormationAPI.go
  pkg/eks/mocks/CloudTrailAPI.go
  pkg/eks/mocks/CloudWatchLogsAPI.go
  pkg/eks/mocks/mocks.go
  pkg/iam/arn.go
  pkg/printers/json.go
  pkg/printers/json_test.go
Labels: dependencies, area/tech-debt

#5775 Remove deprecated field disableASGTagPropagation
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
Labels: area/tech-debt

#5774 Fixed failing crud test
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#5776 Updated packages
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#5772 Fix authentication failures
  go.mod
  integration/tests/crud/creategetdelete_test.go
  pkg/eks/auth/generator.go
  pkg/eks/auth/generator_test.go
  pkg/eks/auth/token_source.go
  pkg/eks/client.go
  pkg/eks/client_test.go
  pkg/utils/kubeconfig/kubeconfig.go
Labels: kind/bug

#5625 Adjust the command line parameters to be consistent for shorthand option -c
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/ctl/get/labels.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/set/labels.go
  pkg/ctl/unset/labels.go
  pkg/ctl/update/iamserviceaccount.go
  pkg/ctl/utils/describe_addon_versions.go
  pkg/ctl/utils/nodegroup_health.go
Labels: area/general-cli, kind/improvement

#5785 Remove incorrect test
  integration/tests/crud/creategetdelete_test.go
Labels: area/testing, skip-release-notes

#5741 Add Support for Windows Server 2022
  integration/tests/windows/windows_test.go
  pkg/ami/auto_resolver.go
  pkg/ami/auto_resolver_test.go
  pkg/ami/ssm_resolver.go
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/outposts_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/ctl/create/nodegroup_test.go
  userdocs/src/usage/custom-ami-support.md
Labels: kind/feature

#5799 Remove redundant tests
  integration/tests/windows/windows_test.go
Labels: area/testing, skip-release-notes

#5781 Fix adding taints and labels as ASG tags
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
Labels: kind/bug

#5802 Fix Windows 2022 tests
  integration/data/windows-server-iis-2022.yaml
  integration/tests/windows/windows_test.go
Labels: area/testing, skip-release-notes

#5800 Bundling dependabot updates
  .github/workflows/docker-publish.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/iam.go
Labels: skip-release-notes

#5808 Fix max-pods for managed nodegroups
  pkg/nodebootstrap/managed_al2.go
  pkg/nodebootstrap/managed_al2_test.go
Labels: kind/bug, area/managed-nodegroup

#5833 Dependencies updates
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/cloudtrail.go
Labels: skip-release-notes

#5695 Add ready plugin to CoreDNS and use health.lameduck for a safer shutdown
  pkg/addons/default/assets/coredns-1.20.json
  pkg/addons/default/assets/coredns-1.21.json
  pkg/addons/default/assets/coredns-1.22.json
  pkg/addons/default/assets/coredns-1.23.json
Labels: kind/improvement

#5834 Added networking.k8s.io api to allowlist ingress operations
  pkg/authconfigmap/assets/emr-containers-rbac.yaml
Labels: kind/improvement

#5837 Add support for me-central-1
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/feature, area/regions

#5838 upgrade helm to 3.10.1 and temporarily pin chai2010
  go.mod
  go.sum
Labels: skip-release-notes, dependencies

#5840 Tweaked release drafter and community doc
  .github/release-drafter.yml
  .github/workflows/greetings.yml
  COMMUNITY.md
Labels: skip-release-notes

#5841 Release notes for 0.117.0
  docs/release_notes/0.117.0.md
Labels: skip-release-notes
