Repository eksctl-io/eksctl, pull requests merged in 2022-07, with the labels that each got.

#5471 Release Notes for 0.105.0
  docs/release_notes/0.105.0.md
Labels: skip-release-notes

#5469 Add integration test for dry-run with custom subnets
  integration/tests/dry_run/assets/cloudformation-vpc.yaml
  integration/tests/dry_run/dry_run_test.go
Labels: area/testing, skip-release-notes

#5454 Lookup instance availability for all AZs
  pkg/actions/nodegroup/create.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/az/az.go
  pkg/az/az_test.go
  pkg/ctl/cmdutils/cluster.go
  pkg/ctl/create/cluster.go
  pkg/eks/api.go
  pkg/eks/api_test.go
  pkg/utils/nodes/nodes.go
Labels: kind/feature, do-not-merge

#5474 Remove unused aws sdk v1 cloudformation service
  pkg/eks/api.go
Labels: skip-release-notes, area/tech-debt

#5495 Fix merging with release branch
  build/scripts/publish-docs.sh
Labels: skip-release-notes, area/ci

#5501 Release notes for 0.106
  docs/release_notes/0.106.0.md
Labels: skip-release-notes

#5518 Increase update test's timeout
  integration/tests/update/update_cluster_test.go
Labels: skip-release-notes

#5463 fix panic when stack has no physical resource id
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
Labels: kind/bug

#5527 Bump deps
  go.mod
  go.sum
Labels: skip-release-notes

#5533 Upgrade more deps
  go.mod
  go.sum
Labels: skip-release-notes

#5534 Add release notes for 0.107.0
  docs/release_notes/0.107.0.md
Labels: skip-release-notes

#5462 Add capacity reservation to spec
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_id.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_preference.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_resource_group_arn.json
Labels: kind/feature

#5546 Updates dependabot deps
  .github/workflows/docker-publish.yaml
  go.mod
  go.sum
Labels: skip-release-notes

#5545 Fix formatting in retry attempt log message for `disassociate identityprovider`
  pkg/actions/identityproviders/disassociate.go
Labels: kind/bug

#5543 Add support for ed25519 inline key
  go.mod
  go.sum
  pkg/ssh/client/ssh.go
  pkg/ssh/client/ssh_test.go
Labels: kind/bug

#5552 Release notes for 0.108.0
  docs/release_notes/0.108.0.md
Labels: skip-release-notes
