Repository eksctl-io/eksctl, pull requests merged in 2022-06, with the labels that each got.

#5345 Add tolerations for taints on NVIDIA specific node groups
  pkg/addons/device_plugin.go
  pkg/eks/tasks.go
Labels: kind/feature

#5248 Do not require overrideBootstrapCommand when ami family is Windows
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/improvement

#5369 Automate release process
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .goreleaser.yml
  build/scripts/do-release-candidate.sh
  build/scripts/do-release.sh
  build/scripts/tag-common.sh
  build/scripts/tag-release-candidate.sh
  build/scripts/tag-release.sh
  pkg/version/generate/release_generate.go
  pkg/version/generate/release_generate_test.go
Labels: area/build-and-release, skip-release-notes, area/ci

#5372 Added release docs
  docs/release_notes/0.101.0.md
Labels: skip-release-notes

#5367 Improved example and updated error message regarding taints
  examples/34-taints.yaml
  pkg/utils/taints/taints.go
  userdocs/mkdocs.yml
  userdocs/src/usage/nodegroup-taints.md
Labels: kind/feature, kind/docs

#5374 Small update to greetings messages
  .github/workflows/greetings.yml
Labels: skip-release-notes

#5357 Ignore IAM OIDC errors if no OIDC provider is associated with cluster
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/unowned.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/utils/associate_iam_oidc_provider.go
  pkg/eks/eks.go
  pkg/iam/oidc/api.go
Labels: kind/improvement

#5365 Return an error when container runtime and overrideBootstrapCommand are defined together
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/bug

#5383 Fix authorization error check from Fargate
  pkg/fargate/fargate.go
Labels: kind/bug

#5274 Add additional EFA supported instances.
  pkg/addons/assets/efa-device-plugin.yaml
Labels: kind/improvement

#5384 Fix AWS IAM Auth dependency
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/connector/arn.go
  pkg/connector/arn_test.go
  pkg/connector/connector.go
  tools.go
Labels: kind/bug

#5389 Added release notes for 102.0
  docs/release_notes/0.102.0.md
Labels: skip-release-notes

#5393 Revert "Fix AWS IAM Auth dependency"
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/connector/arn.go
  pkg/connector/arn_test.go
  pkg/connector/connector.go
  tools.go
Labels: kind/bug

#5394 Small fix for notes
  docs/release_notes/0.102.0.md
  go.mod
  go.sum
Labels: skip-release-notes

#5404 Add LogRetentionInDays update to update-cluster-logging command
  pkg/ctl/create/cluster.go
  pkg/ctl/utils/update_cluster_logging.go
  pkg/eks/update.go
  pkg/eks/update_test.go
Labels: kind/feature

#5392 Fix documentation on updating a managed nodegroup and the error message during updating
  pkg/actions/nodegroup/update.go
  userdocs/src/usage/eks-managed-nodes.md
Labels: kind/docs, area/docs

#5395 Add Wait for nodegroup updates
  pkg/actions/nodegroup/update.go
  pkg/actions/nodegroup/update_test.go
  pkg/cfn/waiter/update_nodegroup.go
  pkg/cfn/waiter/update_nodegroup_test.go
  pkg/cfn/waiter/waiter_suite_test.go
  pkg/ctl/update/nodegroup.go
Labels: kind/feature

#5424 Fix the build flow for actions which use the eksctl build container
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
Labels: kind/bug

#5439 Remove redundant `gh auth status` check in publish-docs workflow
  build/scripts/publish-docs.sh
Labels: skip-release-notes, area/ci

#5440 Add release notes for 0.103
  docs/release_notes/0.103.0.md
Labels: skip-release-notes

#5402 Remove aws iam authenticator
  .github/actions/setup-identity/action.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/connector/arn.go
  pkg/connector/arn_test.go
  pkg/connector/connector.go
  tools.go
Labels: kind/bug

#5418 Update aws-node addon
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/addons/default/assets/aws-node.yaml
  pkg/addons/default/assets_test.go
  pkg/addons/default/aws_node_generate.go
  pkg/addons/default/aws_node_test.go
  pkg/apis/eksctl.io/v1alpha5/addon_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/improvement

#5390 Lookup instance availability for all AZs
  pkg/actions/nodegroup/create.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/az/az.go
  pkg/az/az_test.go
  pkg/ctl/cmdutils/cluster.go
  pkg/ctl/create/cluster.go
  pkg/eks/api.go
  pkg/eks/api_test.go
  pkg/utils/nodes/nodes.go
Labels: kind/feature

#5453 Revert "Lookup instance availability for all AZs"
  pkg/actions/nodegroup/create.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/az/az.go
  pkg/az/az_test.go
  pkg/ctl/cmdutils/cluster.go
  pkg/ctl/create/cluster.go
  pkg/eks/api.go
  pkg/eks/api_test.go
  pkg/utils/nodes/nodes.go
Labels: kind/bug

#5459 Added release docs for 0.104.0
  docs/release_notes/0.104.0.md
Labels: skip-release-notes

#5461 Use `git switch <branch>`
  build/scripts/publish-docs.sh
Labels: skip-release-notes, area/ci

#5466 Fix docs for `--force` in addons
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/ctl/create/addon.go
  pkg/ctl/update/addon.go
Labels: kind/docs

#5458 Do not wait for coredns if there are no nodegroups
  pkg/actions/addon/addon.go
Labels: kind/bug
