Repository eksctl-io/eksctl, pull requests merged in 2022-09, with the labels that each got.

#5660 Add RBAC Permissions for PVC for emr-containers
  pkg/authconfigmap/assets/emr-containers-rbac.yaml
Labels: kind/bug

#5659 Docs update for supported command for non-eksctl created cluster
  userdocs/src/usage/unowned-clusters.md
Labels: kind/docs, area/docs

#5667 add notes for release 0.111.0
  docs/release_notes/0.111.0.md
Labels: skip-release-notes

#5687 Updates to release drafter files
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
Labels: kind/improvement, skip-release-notes

#5688 Fix cluster name in nodegroup-override-announcement
  userdocs/src/announcements/nodegroup-override-announcement.md
Labels: kind/docs

#5661 pin kubernetes version to 1.22
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/utils/kubeconfig/testdata/one_cluster.golden
  pkg/utils/kubeconfig/testdata/one_cluster_without_context.golden
  pkg/utils/kubeconfig/testdata/two_clusters.golden
Labels: kind/improvement, area/tech-debt

#5464 Enable the use of config-file for identitymapping creation
  examples/35-iamidentitymappings.yaml
  pkg/actions/iamidentitymapping/create.go
  pkg/actions/iamidentitymapping/iamidentitymapping.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/identitymapping.go
  pkg/apis/eksctl.io/v1alpha5/identitymapping_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/create/iamidentitymapping.go
  pkg/eks/tasks.go
  userdocs/src/usage/iam-identity-mappings.md
Labels: kind/feature

#5700 fix unit tests
  pkg/printers/testdata/jsontest_2clusters.golden
  pkg/printers/testdata/jsontest_single.golden
  pkg/printers/testdata/yamltest_2clusters.golden
  pkg/printers/testdata/yamltest_single.golden
Labels: skip-release-notes

#5696 Fix managed suite failures
  go.mod
  go.sum
  integration/tests/managed/managed_nodegroup_test.go
  pkg/addons/default/assets/aws-node.yaml
  pkg/addons/default/aws_node_generate.go
  pkg/addons/default/aws_node_test.go
  pkg/awsapi/autoscaling.go
  pkg/awsapi/cloudformation.go
  pkg/awsapi/cloudwatchlogs.go
  pkg/awsapi/elasticloadbalancingv2.go
  pkg/awsapi/iam.go
  pkg/awsapi/ssm.go
  pkg/awsapi/sts.go
Labels: skip-release-notes

#5710 Add release notes for 0.112
  docs/release_notes/0.112.0.md
Labels: skip-release-notes

#5701 Set default scaling config max size to 1
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/bug, area/autoscaler

#5717 feat(make): remove old update-maxpods instruction from Makefile
  Makefile
Labels: skip-release-notes, area/tech-debt

#5719 add release notes for 0.113.0
  docs/release_notes/0.113.0.md
Labels: skip-release-notes

#5680 Stop using 's' as indicator that a method returns a list
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/fargate/create_test.go
  pkg/actions/nodegroup/delete.go
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/get_test.go
  pkg/actions/nodegroup/upgrade.go
  pkg/actions/nodegroup/upgrade_test.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/cluster.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/fargate.go
  pkg/cfn/manager/iam.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/karpenter.go
  pkg/cfn/manager/nodegroup.go
  pkg/ctl/cmdutils/filter/filterfakes/fake_nodegroup_filter.go
  pkg/ctl/cmdutils/filter/nodegroup_filter.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/ctl/utils/describe_stacks.go
  pkg/eks/eks.go
  pkg/eks/nodegroup.go
Labels: kind/improvement, skip-release-notes, area/tech-debt

#5730 Dependencies update
  .github/workflows/pr-labels.yaml
  .github/workflows/stale.yml
  go.mod
  go.sum
Labels: skip-release-notes

#5678 For managed nodegroups, propagate labels and taints as tags to ASG
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/cfn/manager/tasks.go
  userdocs/src/usage/autoscaling.md
Labels: kind/feature, area/autoscaler

#5666 Don't re-create existing addons when taking a config file as input
  integration/tests/addons/addons_test.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
Labels: kind/bug, area/add-ons

#5729 Fix creating ARM-based GPU nodegroups for self-managed Bottlerocket
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/managed_nodegroup.go
Labels: kind/bug

#5712 Add validation error when using private subnets with privateNetworking disabled
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/improvement

#5746 add notes for release 0.114.0
  docs/release_notes/0.114.0.md
Labels: skip-release-notes
