Repository eksctl-io/eksctl, pull requests merged in 2022-08, with the labels that each got.

#5555 Fix typo in error message for IAM service account
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/create/iamserviceaccount_test.go
Labels: kind/improvement

#5561 Housekeeping things
  COMMUNITY.md
  CONTRIBUTING.md
  examples/04-existing-vpc.yaml
  examples/10-encrypted-volumes.yaml
  examples/23-kubeflow-spot-instance.yaml
  pkg/actions/cluster/delete.go
  pkg/apis/eksctl.io/register.go
  pkg/cloudconfig/cloudconfig.go
  pkg/ctl/cmdutils/nodegroup.go
  userdocs/src/usage/addons.md
  userdocs/src/usage/eksctl-anywhere.md
  userdocs/src/usage/faq.md
  userdocs/src/usage/unowned-clusters.md
Labels: skip-release-notes

#5566 Changed albIngress to awsLoadBalancerController in usage iam-policies example
  userdocs/src/usage/iam-policies.md
Labels: kind/docs, kind/improvement, area/docs

#5567 Updates to dependencies
  .github/workflows/link-checker.yaml
  go.mod
  go.sum
Labels: skip-release-notes

#5536 WIP Remove support for 1.19
  pkg/actions/cluster/upgrade_test.go
  pkg/addons/default/coredns_test.go
  pkg/addons/default/kube_proxy_test.go
  pkg/addons/default/testdata/sample-1.20.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/introduction.md
  userdocs/src/usage/addons.md
  userdocs/src/usage/dry-run.md
Labels: kind/improvement

#5571 Fix coredns wait when there are no nodes
  pkg/actions/addon/addon.go
Labels: kind/bug

#5584 Updated dependencies and action
  .github/workflows/docker-publish.yaml
  go.mod
  go.sum
Labels: skip-release-notes

#5598 Upgrade dependencies
  go.mod
  go.sum
Labels: skip-release-notes

#5519 Add support for Kubernetes 1.23
  pkg/actions/cluster/upgrade.go
  pkg/actions/cluster/upgrade_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/introduction.md
Labels: kind/improvement

#5586 Fix docs publishing workflow
  .github/workflows/publish-docs.yaml
Labels: skip-release-notes

#5574 Update docs on ASG tags
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/usage/autoscaling.md
Labels: kind/docs, area/nodegroup

#5610 Remove support for WindowsServer20H2CoreContainer & WindowsServer2004CoreContainer AMIs
  integration/data/windows-server-iis-20H2.yaml
  integration/tests/windows/windows_test.go
  pkg/ami/auto_resolver.go
  pkg/ami/ssm_resolver.go
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/ctl/create/nodegroup_test.go
  userdocs/src/usage/custom-ami-support.md
Labels: kind/feature

#5611 Add release notes for 0.109
  docs/release_notes/0.109.0.md
Labels: skip-release-notes

#5627 Allow creating Windows and Ubuntu nodegroups with NVIDIA GPU instances
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  userdocs/src/usage/gpu-support.md
Labels: area/nodegroup, kind/improvement

#5604 Unpin k8s.io/kubernetes dependency from 1.19
  go.mod
  go.sum
Labels: skip-release-notes

#5623 Karpenter version v0.15.0 support
  examples/29-cluster-with-karpenter.yaml
  integration/tests/karpenter/testdata/cluster-config.yaml
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/improvement, area/karpenter

#5635 Add coredns-1.23 asset
  build/updates/dump-coredns-manifests.sh
  pkg/addons/default/assets/coredns-1.23.json
Labels: skip-release-notes

#5636 Updated packages
  .github/workflows/release-merge.yaml
  .github/workflows/update-generated.yaml
  go.mod
  go.sum
Labels: skip-release-notes

#5643 Return StackName field when getting a single managed nodegroup
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/get_test.go
Labels: kind/bug, area/nodegroup

#5626 Update maintainer list in release drafter
  .github/release-drafter.yml
Labels: skip-release-notes

#5644 Fix ARN partition issue to support IPv6 in China regions
  pkg/actions/addon/create.go
Labels: kind/bug, area/ipv6

#5648 Release 0.110.0
  docs/release_notes/0.110.0.md
Labels: skip-release-notes
