Repository eksctl-io/eksctl, pull requests merged in 2022-01, with the labels that each got.

#4550 Add g5 instance to list of GPU instance types
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/utils/instance/instance.go
Labels: kind/feature

#4558 Check InstanceRoleARN exists before deleting authconfigmap entry
  pkg/ctl/delete/nodegroup.go
Labels: kind/bug

#4566 Move `ipFamily` config file field to `KubernetesNetworkConfig`
  examples/29-vpc-with-ip-family.yaml
  integration/tests/ipv6/ipv6_test.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/vpc_existing.go
  pkg/cfn/builder/vpc_existing_test.go
  pkg/cfn/builder/vpc_ipv6_test.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/usage/vpc-ip-family.md
Labels: kind/improvement, area/ipv6

#4563 Fix `get clusters --all-regions`
  pkg/ctl/get/cluster.go
  pkg/eks/eks.go
  pkg/eks/eks_test.go
Labels: kind/bug

#4567 Merge main into ipv6
  docs/release_notes/0.78.0.md
  docs/release_notes/0.8.0.md
  go.sum
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/delete/nodegroup.go
  pkg/utils/instance/instance.go
  pkg/version/release.go
  userdocs/src/usage/vpc-cluster-access.md
Labels: kind/improvement, area/ipv6, area/tech-debt

#4568 Failing early if missing flux binary during cluster creation
  pkg/ctl/create/cluster.go
Labels: kind/feature

#4573 Add extra validation for `kubernetesNetworkConfig.IPFamily` to avoid panic
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/manager/create_tasks.go
Labels: kind/bug, skip-release-notes, area/ipv6

#4571 Add support for IPv6 VPC and k8s clusters
  docs/release_notes/0.8.0.md
  examples/29-vpc-with-ip-family.yaml
  go.mod
  go.sum
  integration/tests/dry_run/dry_run_test.go
  integration/tests/existing_vpc/cf-template.yaml
  integration/tests/existing_vpc/existing_vpc_test.go
  integration/tests/ipv6/ipv6_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/create_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/builder_suite_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/cfn/builder/vpc_existing.go
  pkg/cfn/builder/vpc_existing_test.go
  pkg/cfn/builder/vpc_ipv4.go
  pkg/cfn/builder/vpc_ipv4_test.go
  pkg/cfn/builder/vpc_ipv6.go
  pkg/cfn/builder/vpc_ipv6_test.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/create_tasks_test.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  pkg/eks/mocks/EC2API.go
  pkg/utils/strings/strings.go
  pkg/utils/utils.go
  pkg/vpc/vpc.go
  userdocs/src/usage/vpc-cluster-access.md
  userdocs/src/usage/vpc-configuration.md
  userdocs/src/usage/vpc-ip-family.md
  userdocs/src/usage/vpc-networking.md
Labels: kind/feature, area/ipv6

#4574 Update aws-go-sdk to an ipv6 supported version
  go.mod
  go.sum
  pkg/eks/mocks/CloudTrailAPI.go
  pkg/eks/mocks/EC2API.go
Labels: kind/feature

#4578 Increase timeout for associate and disassociate commands
  integration/tests/identity_provider/identity_provider_test.go
Labels: kind/bug

#4579 Fix placement of ipFamily field in dry-run test
  integration/tests/dry_run/dry_run_test.go
Labels: kind/bug

#4581 Fix validation for ipFamily when serviceIPv4CIDR is set
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/bug

#4582 Add release notes for 0.79
  docs/release_notes/0.79.0.md
Labels: skip-release-notes

#4583 Unset kubernetesNetworkConfig for `create nodegroup` test
  integration/tests/dry_run/dry_run_test.go
Labels: kind/bug

#4576 Add warning to cluster access about publicAccessCIDRs
  userdocs/src/usage/vpc-cluster-access.md
Labels: kind/docs

#4562 Merge Karpenter branch into main
  CONTRIBUTING.md
  examples/29-cluster-with-karpenter.yaml
  go.mod
  go.sum
  integration/tests/karpenter/karpenter_test.go
  integration/tests/karpenter/testdata/cluster-config.yaml
  pkg/actions/addon/create.go
  pkg/actions/karpenter/create.go
  pkg/actions/karpenter/create_test.go
  pkg/actions/karpenter/karpenter.go
  pkg/actions/karpenter/karpenter_suite_test.go
  pkg/actions/karpenter/tasks.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
  pkg/cfn/manager/create_tasks.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/cluster_test.go
  pkg/karpenter/fakes/fake_chart_installer.go
  pkg/karpenter/karpenter.go
  pkg/karpenter/karpenter_suite_test.go
  pkg/karpenter/karpenter_test.go
  pkg/karpenter/providers/fakes/fake_helm_getter.go
  pkg/karpenter/providers/fakes/fake_helm_installer.go
  pkg/karpenter/providers/fakes/fake_kube_client.go
  pkg/karpenter/providers/helm.go
  pkg/karpenter/providers/helm/helm.go
  pkg/karpenter/providers/helm/helm_suite_test.go
  pkg/karpenter/providers/helm/helm_test.go
  pkg/karpenter/providers/helm/testdata/karpenter-0.4.3.tgz
  pkg/karpenter/providers/helm/testdata/karpenter-index-no-version.yaml
  pkg/karpenter/providers/helm/testdata/karpenter-index.yaml
  pkg/utils/tasks/tasks.go
  userdocs/mkdocs.yml
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/feature

#4587 Fix Karpenter integration test config
  integration/tests/karpenter/testdata/cluster-config.yaml
Labels: skip-release-notes

#4526 Use CloudFormation for cluster endpoint access control, tagging, logging and publicAccessCIDRs
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/builder_suite_test.go
  pkg/cfn/builder/cloudwatch_logging.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/ctl/create/cluster.go
  pkg/eks/tasks.go
  pkg/eks/update.go
  pkg/eks/update_test.go
Labels: kind/improvement

#4591 Revert "pend failing managed ubuntu integration test"
  integration/tests/managed/managed_nodegroup_test.go
Labels: skip-release-notes

#4599 add support for eksctl utils write-kubeconfig with a cfg file
  pkg/ctl/utils/write_kubeconfig.go
Labels: kind/improvement

#4598 add support for eksctl utils update-legacy-subnet-settings with a cfg file
  pkg/ctl/utils/update_legacy_subnet_settings.go
Labels: kind/improvement

#4597 add support for eksctl utils describe-stacks with a cfg file
  pkg/ctl/utils/describe_stacks.go
Labels: kind/improvement

#4601 update deps
  .github/workflows/ci.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes, dependencies

#4605 Fixed the prefix of the ipv6 family example
  examples/30-vpc-with-ip-family.yaml
  pkg/ctl/cmdutils/configfile_test.go
Labels: kind/bug

#4609 Fix logging in integration tests
  pkg/cfn/builder/cloudwatch_logging.go
Labels: kind/bug

#4610 Remove flux binary from build image
  .github/workflows/ci.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
Labels: kind/bug

#4617 Prefix things with eksctl for Karpenter
  pkg/actions/karpenter/create.go
  pkg/actions/karpenter/create_test.go
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
Labels: skip-release-notes

#4618 remove NAT64/DNS64 from ipv6 clusters
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_ipv6.go
  pkg/cfn/builder/vpc_ipv6_test.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/create_tasks_test.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
Labels: kind/bug

#4619 Make config file case insensitive for IPFamily value
  integration/tests/ipv6/ipv6_test.go
  pkg/actions/addon/create.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/vpc_existing.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/nodegroup.go
  pkg/ctl/cmdutils/configfile.go
Labels: kind/bug

#4615 Remove redundant calls to WaitForControlPlane
  pkg/actions/addon/tasks.go
  pkg/eks/fargate.go
  pkg/eks/tasks.go
Labels: kind/improvement

#4620 add 0.80.0 release notes
  docs/release_notes/0.80.0.md
Labels: skip-release-notes

#4623 Added missing save after iam mapping is created
  pkg/actions/karpenter/create.go
  pkg/actions/karpenter/create_test.go
  userdocs/src/usage/minimum-iam-policies.md
Labels: kind/bug

#4629 only wait for addons to be healthy if atleast 1 node instance exists
  pkg/actions/addon/tasks.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/types_test.go
Labels: kind/bug

#4634 Increase timeout and added more debug information for karpenter test
  integration/tests/karpenter/karpenter_test.go
  pkg/karpenter/providers/helm/helm.go
Labels: skip-release-notes

#4636 Added missing oidc requirement
  examples/29-cluster-with-karpenter.yaml
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/docs, kind/bug

#4649 Apply undo flag when running `drain nodegroup`
  pkg/actions/cluster/delete.go
  pkg/actions/nodegroup/drain.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
Labels: kind/bug

#4647 Using kubectl instead of the API
  integration/tests/karpenter/karpenter_test.go
Labels: skip-release-notes

#4644 update deps
  .github/workflows/ci.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/eks/mocks/EC2API.go
Labels: skip-release-notes

#4646 Add docs for troubleshooting kubectl log authorization errors
  userdocs/src/usage/troubleshooting.md
Labels: kind/docs, area/docs

#4506 Add node drain wait period
  pkg/actions/cluster/delete.go
  pkg/actions/nodegroup/drain.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/drain/nodegroup_test.go
  pkg/drain/nodegroup.go
  pkg/drain/nodegroup_test.go
Labels: kind/feature

#4658 Added using kubeconfig flag and removed deleting the cluster so we can debug it.
  integration/tests/karpenter/karpenter_test.go
Labels: skip-release-notes

#4660 update deps
  .github/workflows/ci.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#4656 refactor nodegroup upgrade into pkg/actions/nodegroup/ and backfill tests
  pkg/actions/nodegroup/ami.go
  pkg/actions/nodegroup/ami_test.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/actions/nodegroup/nodegroup_suite_test.go
  pkg/actions/nodegroup/testdata/al2-template.json
  pkg/actions/nodegroup/testdata/al2-updated-template.json
  pkg/actions/nodegroup/upgrade.go
  pkg/actions/nodegroup/upgrade_test.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/managed/service.go
Labels: skip-release-notes, area/tech-debt

#4664 Add ec2:DescribeInstanceTypes to autoScaler policy statements
  pkg/cfn/builder/statement.go
Labels: kind/improvement

#4668 Add release notes for 0.81
  docs/release_notes/0.81.0.md
Labels: skip-release-notes

#4673 add ec2:DescribeVpcPeeringConnections node policy albIngress
  pkg/cfn/builder/statement.go
Labels: kind/bug

#4682 instance-selector is now patched to work w/ EKS AMI V20220123
  go.mod
  go.sum
Labels: skip-release-notes, area/tech-debt

#4684 Increase lint timeout
  Makefile
Labels: kind/bug

#4689 Improve ipv6 docs and link to docs in help text
  pkg/ctl/cmdutils/group.go
  userdocs/mkdocs.yml
  userdocs/src/usage/vpc-ip-family.md
Labels: kind/docs, area/docs

#4688 Fix bug causing the identityProviders to be marshalled incorrectly
  pkg/apis/eksctl.io/v1alpha5/identity_provider.go
  pkg/apis/eksctl.io/v1alpha5/identity_provider_test.go
Labels: kind/bug

#4692 Fix karpenter integration test
  integration/tests/karpenter/karpenter_test.go
  integration/tests/karpenter/testdata/cluster-config.yaml
Labels: skip-release-notes

#4699 pend flakely karpenter test
  integration/tests/karpenter/karpenter_test.go
Labels: skip-release-notes

#4704 Use correct kubeconfig for karpenter install
  integration/tests/karpenter/karpenter_test.go
  pkg/actions/karpenter/karpenter.go
  pkg/ctl/create/cluster.go
  pkg/karpenter/providers/helm/helm.go
  pkg/kubernetes/client.go
Labels: kind/bug

#4702 Avoid force-pushing to `docs` branch to publish docs
  .github/workflows/check-links.yaml
  .github/workflows/release.yaml
  Makefile.docs
  build/scripts/publish-docs.sh
  build/scripts/tag-release.sh
Labels: kind/improvement

#4706 add 0.82.0 release notes
  docs/release_notes/0.82.0.md
Labels: skip-release-notes

#4709 Update example karpenter version
  examples/29-cluster-with-karpenter.yaml
Labels: skip-release-notes

#4711 Fix deletion logic in case the cluster does not exist
  pkg/ctl/delete/cluster.go
Labels: kind/bug

#4716 pend flakely ipv6 test
  integration/tests/ipv6/ipv6_test.go
Labels: skip-release-notes

#4686 fix bug preventing IPv6 clusters using an existing VPC
  integration/tests/existing_vpc/existing_vpc_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/actions/nodegroup/create_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/cfn/builder/vpc_existing.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/nodegroup.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/test_data/ipv6-existing-vpc.yaml
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/bug

#4694 Erroring out if the subnet is not public
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/feature

#4666 Upgrade non-al2 managed nodegroups by updating the `Version` field in the nodegroup stack
  integration/tests/managed/managed_nodegroup_test.go
  pkg/actions/nodegroup/nodegroup_suite_test.go
  pkg/actions/nodegroup/testdata/al2-force-false-template.json
  pkg/actions/nodegroup/testdata/al2-no-force-template.json
  pkg/actions/nodegroup/testdata/br-force-false-template.json
  pkg/actions/nodegroup/testdata/br-force-true-template.json
  pkg/actions/nodegroup/testdata/br-updated-template.json
  pkg/actions/nodegroup/upgrade.go
  pkg/actions/nodegroup/upgrade_test.go
  pkg/ami/ssm_resolver.go
Labels: kind/bug

#4659 Adding an option for `--disable-nodegroup-eviction` when deleting a cluster
  pkg/actions/cluster/cluster.go
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/delete_test.go
  pkg/actions/cluster/export_test.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/nodegroup/drain.go
  pkg/ctl/delete/cluster.go
  pkg/ctl/delete/cluster_test.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
Labels: kind/feature

#4717 Fix ASG names in `get nodegroup`
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/get_test.go
Labels: kind/bug

#4723 bump deps
  .github/workflows/ci.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes, dependencies

#4726 Revert "Erroring out if the subnet is not public"
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/bug
