Repository eksctl-io/eksctl, pull requests merged in 2022-03, with the labels that each got.

#4866 error when creating managed bottlerocket GPU instances
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
Labels: kind/bug

#4875 Merge #4873 to release-0.86 branch
  build/scripts/do-release-candidate.sh
  build/scripts/do-release.sh
Labels: skip-release-notes

#4886 Bump deps
  go.mod
  go.sum
Labels: skip-release-notes

#4887 add 0.87.0 notes
  docs/release_notes/0.87.0.md
Labels: skip-release-notes

#4894 Fix missing stack name in case only the stack is provided.
  pkg/cfn/manager/api.go
  pkg/cfn/manager/api_test.go
Labels: kind/bug

#4895 Revert "Tag 0.87.0-rc.0 release candidate"
  pkg/version/release.go
Labels: skip-release-notes

#4897 set tag env var in rc release script
  build/scripts/do-release-candidate.sh
Labels: skip-release-notes

#4898 Fix GitHub Actions caching
  .github/workflows/cache-dependencies.yaml
  .github/workflows/lint.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
Labels: kind/bug, area/ci

#4896 Validate AZ configuration correctly
  pkg/ctl/create/cluster.go
  pkg/eks/api.go
  pkg/eks/api_test.go
Labels: kind/bug, skip-release-notes

#4899 update notes
  docs/release_notes/0.87.0.md
Labels: skip-release-notes

#4905 Added clarity for overrideBootstrapCommand
  userdocs/src/usage/container-runtime.md
Labels: kind/docs

#4855 move unmanaged nodegroup summaries to pkg/actions/nodegroup
  integration/matchers/json.go
  pkg/actions/nodegroup/get.go
  pkg/actions/nodegroup/get_test.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/nodegroup_test.go
  pkg/ctl/get/nodegroup.go
Labels: skip-release-notes

#4860 Don't attach the control plane security group to managed nodegroups
  pkg/vpc/importer.go
  pkg/vpc/importer_test.go
Labels: kind/improvement

#4900 separate KMS into its own suite and reduce nodegroup creation time
  integration/tests/fargate/fargate_test.go
  integration/tests/kms/kms_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: skip-release-notes

#4912 Fix broken links to 'IAM Service Accounts' in docs
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
Labels: kind/docs

#4903 Pin karpenter support to 0.6.*
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/improvement

#4893 Fix build image URL in Dockerfile
  Makefile.docker
Labels: kind/bug, area/ci

#4921 Fix schema.json
  .github/workflows/exclude-file.txt
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
Labels: skip-release-notes, area/tech-debt

#4904 Fixing the cidr range calculation in case of a custom cidr block
  pkg/cfn/builder/vpc.go
  pkg/cfn/builder/vpc_ipv6.go
  pkg/cfn/builder/vpc_ipv6_test.go
Labels: kind/bug

#4933 Fix checking cluster stack for owned clusters
  pkg/cfn/manager/api.go
  pkg/cfn/manager/api_test.go
Labels: kind/bug, skip-release-notes

#4943 Add notes for 0.88
  docs/release_notes/0.88.0.md
Labels: skip-release-notes

#4945 Revert "Fix backwards compatibility check test"
  integration/scripts/download-previous-release.sh
Labels: skip-release-notes

#4950 Fix integration tests for `get cluster`
  integration/matchers/cluster.go
Labels: area/testing, skip-release-notes

#4942 Remove unused `ssmAPI` field
  pkg/ctl/get/labels.go
  pkg/ctl/set/labels.go
  pkg/ctl/unset/labels.go
  pkg/ctl/utils/nodegroup_health.go
  pkg/managed/service.go
Labels: skip-release-notes, area/tech-debt

#4928 Fix nodegroup get when no nodes are present
  pkg/kubernetes/nodegroup.go
  pkg/kubernetes/nodegroup_test.go
Labels: kind/bug

#4922 Empty `get addons` returns empty json/yaml array instead of empty string
  pkg/ctl/get/addon.go
  pkg/printers/json.go
  pkg/printers/json_test.go
  pkg/printers/yaml.go
  pkg/printers/yaml_test.go
Labels: kind/bug

#4923 Core Team Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/core-team-spike.md
  .github/ISSUE_TEMPLATE/core-team-story.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/request-for-help.md
Labels: skip-release-notes

#4959 bump containerd
  go.mod
  go.sum
Labels: skip-release-notes

#4964 Revert "Drain nodes in parallel"
  go.mod
  go.sum
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/nodegroup/drain.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/delete/nodegroup_test.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/drain/nodegroup_test.go
  pkg/drain/nodegroup.go
  pkg/drain/nodegroup_test.go
  pkg/eks/client.go
  userdocs/src/usage/managing-nodegroups.md
Labels: skip-release-notes

#4960 update to go 1.18
  .github/workflows/lint.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes

#4974 Added release doc for 0.89.0 rc
  docs/release_notes/0.89.0.md
Labels: skip-release-notes

#4966 Drain nodes in parallel
  go.mod
  go.sum
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/cluster/cluster.go
  pkg/actions/cluster/delete.go
  pkg/actions/cluster/delete_test.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/nodegroup/drain.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/delete/cluster.go
  pkg/ctl/delete/cluster_test.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/delete/nodegroup_test.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/drain/nodegroup_test.go
  pkg/drain/nodegroup.go
  pkg/drain/nodegroup_test.go
  pkg/eks/client.go
  userdocs/src/usage/managing-nodegroups.md
Labels: skip-release-notes

#4988 bump deps
  .github/workflows/lint.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes, dependencies

#4989 add slack notifications to release and build all
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/publish-release-candidate.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/publish-release.yaml
Labels: skip-release-notes

#4926 Set up AWS SDK v2 and migrate STS service
  .github/workflows/lint.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/update-generated.yaml
  .requirements
  Dockerfile
  Makefile
  build/docker/build_image_manifest
  build/docker/image_tag
  build/scripts/generate-aws-interfaces.sh
  go.mod
  go.sum
  integration/tests/params.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/awsapi/cloudformation.go
  pkg/awsapi/generate/add_import.go
  pkg/awsapi/generate/generate.go
  pkg/awsapi/sts.go
  pkg/connector/connector.go
  pkg/connector/connector_test.go
  pkg/credentials/fakes/fake_aws_credentials_provider.go
  pkg/credentials/fakes/fake_flock.go
  pkg/credentials/filecache.go
  pkg/credentials/filecache_test.go
  pkg/credentials/filecache_v2.go
  pkg/credentials/filecache_v2_test.go
  pkg/ctl/register/cluster.go
  pkg/eks/api.go
  pkg/eks/apiv2.go
  pkg/eks/client.go
  pkg/eks/logging_retryer.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/STS.go
  pkg/eks/mocksv2/generate.go
  pkg/eks/retryer_v2.go
  pkg/eks/services_v2.go
  pkg/testutils/mockprovider/mock_provider.go
  tools.go
Labels: kind/improvement, dependencies, area/tech-debt

#4992 use go 1.18 for build all distros
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/publish-release-type.yaml
Labels: skip-release-notes

#5005 Add Go version to link checker workflow
  .github/workflows/link-checker.yaml
Labels: skip-release-notes

#4962 Added propagate asg tags to propagate labels and taints on creation
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  userdocs/src/usage/autoscaling.md
Labels: kind/feature

#5008 Update `mkdocs`
  userdocs/requirements.txt
Labels: skip-release-notes

#4999 Update docs to mention what happens when you create an addon with no policy sources
  userdocs/src/usage/addons.md
Labels: kind/docs, area/docs

#5004 Add notes for 0.90.0
  docs/release_notes/0.90.0.md
Labels: skip-release-notes

#5019 Fix release workflow
  .github/workflows/publish-release-type.yaml
Labels: kind/bug, skip-release-notes

#5020 Revert "Prepare for next development iteration"
  pkg/version/release.go
Labels: skip-release-notes

#4937 Migrate ELB and ELBv2 to aws-sdk-go-v2
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/awsapi/elasticloadbalancing.go
  pkg/awsapi/elasticloadbalancingv2.go
  pkg/awsapi/generate/generate.go
  pkg/eks/api.go
  pkg/eks/mocks/ELBAPI.go
  pkg/eks/mocks/ELBV2API.go
  pkg/eks/mocks/mocks.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/services_v2.go
  pkg/elb/cleanup.go
  pkg/testutils/mockprovider/mock_provider.go
Labels: kind/improvement, area/tech-debt

#5024 Fix missing permission boundary from Karpetner iam resource
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
Labels: kind/bug

#4968 Removed legacy path for al2 and ubuntu
  examples/31-override-bootstrap-command-unmanaged-nodegroup.yaml
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/eks/nodegroup_service.go
  pkg/nodebootstrap/al2_test.go
  pkg/nodebootstrap/assets/assets.go
  pkg/nodebootstrap/assets/scripts/10-eksctl.al2.conf
  pkg/nodebootstrap/legacy/al2.go
  pkg/nodebootstrap/legacy/legacy_suite_test.go
  pkg/nodebootstrap/legacy/maxpods.go
  pkg/nodebootstrap/legacy/maxpods_generate.go
  pkg/nodebootstrap/legacy/reserved.go
  pkg/nodebootstrap/legacy/reserved_data.go
  pkg/nodebootstrap/legacy/reserved_generate.go
  pkg/nodebootstrap/legacy/reserved_test.go
  pkg/nodebootstrap/legacy/scripts/bootstrap.legacy.al2.sh
  pkg/nodebootstrap/legacy/scripts/bootstrap.legacy.ubuntu.sh
  pkg/nodebootstrap/legacy/ubuntu.go
  pkg/nodebootstrap/legacy/userdata.go
  pkg/nodebootstrap/legacy/userdata_test.go
  pkg/nodebootstrap/ubuntu_test.go
  pkg/nodebootstrap/userdata.go
  userdocs/src/usage/nodegroup-override-announcement.md
  userdocs/theme/main.html
Labels: kind/feature, kind/breaking

#5009 Migrate usage of SSM to aws-sdk-go-v2
  go.mod
  go.sum
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/create_test.go
  pkg/actions/nodegroup/upgrade.go
  pkg/actions/nodegroup/upgrade_test.go
  pkg/ami/ami_test.go
  pkg/ami/api.go
  pkg/ami/auto_resolver.go
  pkg/ami/auto_resolver_test.go
  pkg/ami/resolver.go
  pkg/ami/ssm_resolver.go
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/awsapi/generate/generate.go
  pkg/awsapi/ssm.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/eks/api.go
  pkg/eks/api_test.go
  pkg/eks/fakes/fake_nodegroup_initialiser.go
  pkg/eks/mocks/SSMAPI.go
  pkg/eks/mocks/mocks.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/nodegroup_service.go
  pkg/eks/services_v2.go
  pkg/testutils/mockprovider/mock_provider.go
Labels: technical debt, kind/improvement

#5036 Fix typo in ELB cleanup process
  pkg/eks/services_v2.go
Labels: skip-release-notes
