Repository eksctl-io/eksctl, pull requests merged in 2022-11, with the labels that each got.

#5857 Update python version for netlify docs
  netlify.toml
  userdocs/runtime.txt
  userdocs/src/usage/managing-nodegroups.md
Labels: area/build-and-release, area/tech-debt

#5845 Add note on how to upgrade managed nodegroups using custom AMI
  userdocs/src/usage/eks-managed-nodes.md
Labels: kind/docs, area/docs

#5832 Karpenter support with OCI registry, minimum supported version is now v0.17.0 for new cluster creation
  examples/29-cluster-with-karpenter.yaml
  go.mod
  go.sum
  integration/tests/karpenter/testdata/cluster-config.yaml
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/awsapi/cloudformation.go
  pkg/awsapi/cloudwatchlogs.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/karpenter/karpenter.go
  pkg/karpenter/karpenter_test.go
  pkg/karpenter/providers/helm.go
  pkg/karpenter/providers/helm/helm.go
  pkg/karpenter/providers/helm/helm_test.go
  pkg/karpenter/providers/helm/testdata/karpenter-0.18.0.tgz
  pkg/karpenter/providers/helm/testdata/karpenter-index-no-version.yaml
  pkg/karpenter/providers/helm/testdata/karpenter-index.yaml
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/feature, kind/breaking, area/karpenter

#5870 Retry temporary failure in identity provider test
  integration/tests/identity_provider/identity_provider_test.go
  pkg/actions/identityproviders/associate.go
Labels: area/testing, skip-release-notes

#5864 Add trn1 instance types to the neuron device plugin
  pkg/addons/assets/neuron-device-plugin.yaml
Labels: kind/improvement

#5872 Add release notes for 0.118.0
  docs/release_notes/0.118.0.md
Labels: skip-release-notes

#5875 Improve error message when Fargate is unsupported in an AZ
  pkg/fargate/create.go
  pkg/fargate/fargate_test.go
Labels: area/fargate, kind/improvement

#5852 Make AMI Bottlerocket value case insensitive
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/defaults_test.go
Labels: kind/bug

#5889 Fix setting cluster DNS for managed Ubuntu
  pkg/cfn/builder/managed_nodegroup_ami_type_test.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/manager/nodegroup.go
  pkg/nodebootstrap/al2.go
  pkg/nodebootstrap/managed_bottlerocket_test.go
  pkg/nodebootstrap/managed_ubuntu_test.go
  pkg/nodebootstrap/ubuntu.go
  pkg/nodebootstrap/userdata.go
Labels: kind/bug

#5890 Upgrade vulnerable dependencies
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/autoscaling.go
  pkg/awsapi/cloudtrail.go
  pkg/awsapi/cloudwatchlogs.go
  pkg/eks/mocksv2/CloudTrail.go
Labels: area/tech-debt

#5885 Updates to additional volumes mapping section and docs theme
  userdocs/mkdocs.yml
  userdocs/requirements.txt
  userdocs/src/stylesheets/extra.css
  userdocs/src/usage/nodegroup-additional-volume-mappings.md
Labels: kind/docs, kind/improvement, area/docs

#5880 Add resolve conflicts option on addon create
  integration/tests/addons/addons_test.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  userdocs/src/usage/addons.md
Labels: kind/feature, area/add-ons

#5854 Fix AWS auth when `AWS_PROFILE` is set
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/associate/identity_provider.go
  pkg/ctl/cmdutils/cmdutils.go
  pkg/ctl/create/addon.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/fargate.go
  pkg/ctl/create/iamidentitymapping.go
  pkg/ctl/create/iamserviceaccount.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/delete/addon.go
  pkg/ctl/delete/cluster.go
  pkg/ctl/delete/fargate.go
  pkg/ctl/delete/iamidentitymapping.go
  pkg/ctl/delete/iamserviceaccount.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/deregister/cluster.go
  pkg/ctl/disassociate/identity_provider.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/enable/flux.go
  pkg/ctl/get/addon.go
  pkg/ctl/get/cluster.go
  pkg/ctl/get/fargate.go
  pkg/ctl/get/iamidentitymapping.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/ctl/get/identityprovider.go
  pkg/ctl/get/labels.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/register/cluster.go
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/set/labels.go
  pkg/ctl/unset/labels.go
  pkg/ctl/update/addon.go
  pkg/ctl/update/cluster.go
  pkg/ctl/update/iamserviceaccount.go
  pkg/ctl/update/nodegroup.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/ctl/utils/associate_iam_oidc_provider.go
  pkg/ctl/utils/describe_addon_versions.go
  pkg/ctl/utils/describe_stacks.go
  pkg/ctl/utils/enable_secrets_encryption.go
  pkg/ctl/utils/install_vpc_controllers.go
  pkg/ctl/utils/nodegroup_health.go
  pkg/ctl/utils/set_public_access_cidrs.go
  pkg/ctl/utils/update_aws_node.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
  pkg/ctl/utils/update_cluster_logging.go
  pkg/ctl/utils/update_coredns.go
  pkg/ctl/utils/update_kube_proxy.go
  pkg/ctl/utils/update_legacy_subnet_settings.go
  pkg/ctl/utils/write_kubeconfig.go
  pkg/eks/api.go
  pkg/eks/apiv2.go
  pkg/eks/client_test.go
  pkg/testutils/mockprovider/mock_provider.go
Labels: kind/bug

#5899 Remove dependency on k8s.io/legacy-cloud-providers
  go.mod
  go.sum
  pkg/elb/cleanup.go
Labels: dependencies, area/tech-debt

#5901 Fix publish-docs workflow
  .github/workflows/publish-docs.yaml
Labels: kind/bug, area/build-and-release

#5904 Add release notes for 0.119.0
  docs/release_notes/0.119.0.md
Labels: skip-release-notes

#5925 Upgrade dependencies
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes, dependencies

#5907 Update base image in the build container
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: area/build-and-release, kind/improvement

#5807 Add support for EKS 1.24
  pkg/actions/cluster/upgrade.go
  pkg/actions/cluster/upgrade_test.go
  pkg/addons/default/assets/coredns-1.24.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/defaults_test.go
  pkg/apis/eksctl.io/v1alpha5/outposts_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/nodebootstrap/windows_test.go
  userdocs/src/introduction.md
Labels: kind/feature

#5936 Added specific zones for cluster creation for inferentia
  integration/tests/inferentia/inferentia_test.go
Labels: skip-release-notes

#5937 Fix dry run integration test
  integration/tests/dry_run/dry_run_test.go
Labels: skip-release-notes

#5939 Fix crud test
  pkg/apis/eksctl.io/v1alpha5/validation.go
Labels: skip-release-notes

#5938 Release notes for 0.120.0
  docs/release_notes/0.120.0.md
Labels: skip-release-notes

#5906 Support for clusters with trn1 instance types
  integration/tests/trainium/trainium_test.go
  pkg/addons/assets/neuron-device-plugin.yaml
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/eks/tasks.go
  pkg/utils/instance/instance.go
Labels: kind/feature

#5927 Update deprecated set-output in workflows
  .github/workflows/publish-release-type.yaml
  .github/workflows/update-generated.yaml
Labels: area/tech-debt, area/ci

#5926 Added slack notifications for publish docs workflow
  .github/workflows/publish-docs.yaml
Labels: area/build-and-release, area/tech-debt, area/ci

#5946 Standardize cluster / nodegroup version before doing validations and …
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/create_test.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/ctl/cmdutils/cmd.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/nodegroup_test.go
  pkg/nodebootstrap/windows_test.go
Labels: skip-release-notes

#5932 Improve windows tests
  integration/tests/windows/windows_test.go
Labels: skip-release-notes

#5947 Update error handling for RegisterCluster
  pkg/connector/connector.go
  pkg/connector/connector_test.go
Labels: kind/bug

#5941 Standardize cluster / nodegroup version before doing validations and setting defaults
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/create_test.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/ctl/cmdutils/cmd.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/nodegroup_test.go
  pkg/nodebootstrap/windows_test.go
Labels: skip-release-notes

#5945 Release notes for 0.121.0
  docs/release_notes/0.121.0.md
Labels: skip-release-notes

#5950 fix release notes
  docs/release_notes/0.121.0.md
Labels: skip-release-notes

#5929 Do not wait for aws-ebs-csi-driver if there are no nodegroups
  integration/tests/addons/addons_test.go
  pkg/actions/addon/addon.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/bug

#5969 Bump dependencies
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/eks.go
  pkg/awsapi/elasticloadbalancingv2.go
  pkg/awsapi/ssm.go
  pkg/awsapi/sts.go
  pkg/eks/mocksv2/SSM.go
Labels: skip-release-notes, dependencies

#5973 Improve log message when calling DescribeCluster during registration fails
  pkg/connector/connector.go
Labels: kind/improvement

#5970 Update Kubernetes configuration
  integration/data/podinfo.yaml
  integration/data/windows-server-iis-2022.yaml
  integration/data/windows-server-iis.yaml
  pkg/addons/assets/efa-device-plugin.yaml
  pkg/addons/assets/neuron-device-plugin.yaml
  pkg/addons/assets/nvidia-device-plugin.yaml
  pkg/addons/assets/vpc-admission-webhook-dep.yaml
  pkg/addons/assets/vpc-resource-controller-dep.yaml
  pkg/addons/default/assets/aws-node.yaml
  pkg/iam/oidc/api.go
Labels: technical debt, area/tech-debt

#5975 Fix release version in notifications
  .github/workflows/publish-release-type.yaml
  .github/workflows/update-generated.yaml
Labels: kind/bug, area/build-and-release

#5976 Removed the pkg/apis/eksctl.io/v1alpha5/schema.go file
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/schema.go
Labels: technical debt, area/tech-debt

#5996 Support for Addon filters in utils describe-addon-versions
  go.mod
  go.sum
  integration/tests/addons/addons_test.go
  pkg/actions/addon/describe_versions.go
  pkg/actions/addon/describe_versions_test.go
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/awsapi/cloudwatchlogs.go
  pkg/awsapi/eks.go
  pkg/ctl/utils/describe_addon_versions.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  userdocs/src/usage/addons.md
Labels: kind/feature

#5997 Release notes for 0.123.0
  docs/release_notes/0.123.0.md
Labels: skip-release-notes
