Repository eksctl-io/eksctl, pull requests merged in 2023-04, with the labels that each got.

#6488 Update build image manifest, tag file and workflows, dependencies
  .github/workflows/exclude-file.txt
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/stale.yml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/autoscaling.go
  pkg/awsapi/iam.go
Labels: technical debt, dependencies, area/tech-debt

#6460 Add support for Spot Interruption Queue within Karpenter
  examples/29-cluster-with-karpenter.yaml
  integration/tests/karpenter/testdata/cluster-config.yaml
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/feature, area/karpenter

#6406 Add wait flag to `scale nodegroup`
  pkg/actions/nodegroup/scale.go
  pkg/actions/nodegroup/scale_test.go
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/scale/nodegroup_test.go
  pkg/eks/client.go
  pkg/eks/nodegroup.go
  pkg/testutils/mockprovider/mock_provider.go
  userdocs/src/usage/managing-nodegroups.md
Labels: kind/feature, area/autoscaler

#6497 Fix CRUD integration test
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#6496 Add release notes for 0.137.0
  docs/release_notes/0.137.0.md
Labels: skip-release-notes

#6500 Add volcano podgroups permissions
  pkg/authconfigmap/assets/emr-containers-rbac.yaml
Labels: kind/improvement

#6502 Add support for EKS 1.26
  pkg/actions/cluster/upgrade.go
  pkg/actions/cluster/upgrade_test.go
  pkg/actions/nodegroup/testdata/al2-updated-template.json
  pkg/actions/nodegroup/testdata/br-updated-template.json
  pkg/addons/default/assets/coredns-1.26.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/introduction.md
Labels: kind/feature

#6526 Add release notes for 0.138
  docs/release_notes/0.138.0.md
Labels: skip-release-notes

#6376 Update installation instructions
  README.md
  userdocs/src/introduction.md
Labels: kind/docs, area/docs

#6524 Fix empty info block on Default Addon Upgrades page
  userdocs/src/usage/addon-upgrade.md
Labels: kind/docs, area/docs

#6408 AWS Private link support for fully private cluster
  userdocs/src/usage/eks-private-cluster.md
Labels: kind/docs, area/docs

#6540 Temporarily remove failing Bottlerocket upgrade test
  integration/tests/managed/managed_nodegroup_test.go
Labels: area/testing, skip-release-notes

#6541 Security Policy for eksctl project
  README.md
  SECURITY.md
Labels: kind/feature, area/docs

#6553 Revert "Temporarily remove failing Bottlerocket upgrade test (#6540)"
  integration/tests/managed/managed_nodegroup_test.go
Labels: skip-release-notes

#6555 Updated schema for unsupported fields for managed nodegroups
  .github/workflows/docker-publish.yaml
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/docs, area/docs, dependencies

#6464 Only select AZs that support all instance types on nodegroup creation
  integration/tests/existing_vpc/existing_vpc_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/az/az.go
  pkg/cfn/builder/cluster_test.go
  pkg/cfn/builder/export_test.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_ami_type_test.go
  pkg/cfn/builder/managed_nodegroup_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_subnets_test.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/bottlerocket.json
  pkg/cfn/builder/testdata/launch_template/bottlerocket_additional_encrypted_volume.json
  pkg/cfn/builder/testdata/launch_template/bottlerocket_volume.json
  pkg/cfn/builder/testdata/launch_template/custom_ami.json
  pkg/cfn/builder/testdata/launch_template/launch_template.json
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes.json
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes_missing_size.json
  pkg/cfn/builder/testdata/launch_template/launch_template_custom_ami.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_id.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_preference.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_resource_group_arn.json
  pkg/cfn/builder/testdata/launch_template/lt_instance_types.json
  pkg/cfn/builder/testdata/launch_template/placement.json
  pkg/cfn/builder/testdata/launch_template/spot.json
  pkg/cfn/builder/testdata/launch_template/ssh_disabled.json
  pkg/cfn/builder/testdata/launch_template/ssh_enabled.json
  pkg/cfn/builder/testdata/launch_template/standard.json
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/ctl/create/cluster_test.go
  pkg/utils/nodes/nodes.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/bug, area/nodegroup, area/managed-nodegroup

#6554 Force kubeconfig get-token output format to json
  pkg/eks/client_test.go
  pkg/utils/kubeconfig/kubeconfig.go
Labels: kind/bug

#6560 Add release notes for 0.140.0
  docs/release_notes/0.140.0.md
Labels: skip-release-notes
