Repository eksctl-io/eksctl, pull requests merged in 2023-08, with the labels that each got.

#6898 Remove `iam:ListInstanceProfiles` from the required permissions list
  userdocs/src/usage/minimum-iam-policies.md
Labels: kind/docs, area/docs

#6901 Pin actions to a full length commit SHA
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/cache-dependencies.yaml
  .github/workflows/docker-publish.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/greetings.yml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/rebase.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
Labels: technical debt, dependencies, area/tech-debt, area/ci

#6899 Add support for Tel Aviv (il-central-1)
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/index.md
Labels: kind/feature, area/regions

#6895 Bump dependencies
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/eks/api.go
Labels: dependencies, area/tech-debt

#6903 Fix PR Rebase workflow
  .github/workflows/rebase.yaml
  CONTRIBUTING.md
Labels: kind/bug

#6920 Bump dependencies
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#6921 Release notes for 0.152.0
  docs/release_notes/0.152.0.md
Labels: skip-release-notes

#6897 Improve error message when `overrideBootstrapCommand` is required for `customAMIs`
  pkg/apis/eksctl.io/v1alpha5/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: area/general-cli, kind/improvement

#6931 Allow setting cluster-dns-ip for Bottlerocket
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/bug, bottlerocket

#6934 Remove PR rebase workflow
  .github/workflows/rebase.yaml
  CONTRIBUTING.md
Labels: technical debt, area/tech-debt

#6923 Update Bottlerocket image version on nodegroup upgrade
  pkg/actions/nodegroup/testdata/br-updated-template.json
  pkg/actions/nodegroup/upgrade_test.go
  pkg/ami/ssm_resolver.go
Labels: kind/feature, area/managed-nodegroup, bottlerocket

#6875 Unit test creating the EKS provider
  pkg/eks/api.go
  pkg/eks/api_test.go
  pkg/eks/apiv2.go
  pkg/eks/export_test.go
  pkg/eks/fakes/fake_configuration_loader.go
  pkg/eks/testdata/cached-credentials.yaml
Labels: technical debt, area/tech-debt

#6946 Bump dependencies
  go.mod
  go.sum
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: dependencies, area/tech-debt

#6948 Add release notes for 0.153.0
  docs/release_notes/0.153.0.md
Labels: skip-release-notes

#6965 Bring Windows integration test runtime down to less than half
  integration/main.go
  integration/tests/windows/windows_test.go
Labels: area/testing, area/tech-debt, area/ci

#6968 Add references to Enterprise support with Flux on Gitops page
  userdocs/src/usage/gitops-v2.md
Labels: kind/docs, area/docs

#6967 Fix error message for Bottlerocket validation
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/bug

#6972 Release notes for 0.154.0
  docs/release_notes/0.154.0.md
Labels: skip-release-notes

#6969 Switch default volume type back to gp3 for ISO regions
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/defaults_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/configfile.go
Labels: area/nodegroup, area/managed-nodegroup, kind/improvement

#6993 Fix merge release workflow when there is nothing to merge
  .github/workflows/release-merge.yaml
Labels: kind/bug, area/ci

#6994 Replace deprecated Ginkgo CLI options
  integration/main.go
Labels: area/tech-debt, area/ci

#6996 Update Ginkgo
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  .requirements
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
Labels: dependencies, area/tech-debt

#6998 Bump dependencies
  go.mod
  go.sum
  pkg/awsapi/elasticloadbalancingv2.go
Labels: dependencies, area/tech-debt

#6992 Improve unit tests' runtime
  .github/workflows/test-and-build.yaml
  Makefile
  pkg/cfn/manager/api.go
  pkg/cfn/waiter/stack.go
  pkg/ctl/create/cluster_test.go
  pkg/eks/fargate.go
  pkg/eks/nodegroup_service.go
  pkg/karpenter/providers/helm.go
  pkg/outposts/outposts.go
Labels: area/tech-debt

#7000 Add release notes for 0.155
  docs/release_notes/0.155.0.md
Labels: skip-release-notes

#7025 Bump dependencies
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/docker-publish.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
  .requirements
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#6935 Cleanup subnets with invalid AZs before importing VPC from CFN stack
  integration/tests/crud/creategetdelete_test.go
  pkg/vpc/vpc.go
  pkg/vpc/vpc_test.go
Labels: kind/bug

#7027 Adopters for eksctl
  CONTRIBUTING.md
  userdocs/mkdocs.yml
  userdocs/src/adopters.md
  userdocs/src/favicon_300px.png
  userdocs/src/stylesheets/extra.css
  userdocs/theme/assets/adopters/aws-logo.png
  userdocs/theme/assets/adopters/gophers.png
  userdocs/theme/assets/adopters/placeholder.svg
  userdocs/theme/assets/adopters/weave-logo.png
  userdocs/theme/main.html
  userdocs/theme/partials/copyright.html
Labels: kind/feature, area/docs
