Repository eksctl-io/eksctl, pull requests merged in 2023-05, with the labels that each got.

#6569 Correct typo on NAT Gateway configuration value choices
  userdocs/src/usage/vpc-configuration.md
Labels: area/tech-debt

#6573 Release notes for 0.141.0
  docs/release_notes/0.141.0.md
Labels: skip-release-notes

#6492 Support for clusters with inf2 and trn1n instance types
  integration/tests/inferentia/inferentia_test.go
  integration/tests/trainium/trainium_test.go
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/utils/instance/instance.go
Labels: kind/feature

#6595 Bump dependencies
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: skip-release-notes, dependencies

#6597 Revert "Adding support for inf2 and trn1n instances"
  integration/tests/inferentia/inferentia_test.go
  integration/tests/trainium/trainium_test.go
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/utils/instance/instance.go
Labels: skip-release-notes

#6611 Add TagResource perm to EFS wellknown policy
  pkg/cfn/builder/statement.go
Labels: kind/improvement

#6613 Bump dependencies and update build image
  .github/workflows/link-checker.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  .requirements
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/sts.go
Labels: dependencies, area/tech-debt

#6612 Make IMDSv2 the default
  pkg/actions/nodegroup/testdata/al2-force-false-template.json
  pkg/actions/nodegroup/testdata/al2-no-force-template.json
  pkg/actions/nodegroup/testdata/al2-updated-template.json
  pkg/actions/nodegroup/testdata/br-force-false-template.json
  pkg/actions/nodegroup/testdata/br-force-true-template.json
  pkg/actions/nodegroup/testdata/br-updated-template.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/bottlerocket.json
  pkg/cfn/builder/testdata/launch_template/bottlerocket_additional_encrypted_volume.json
  pkg/cfn/builder/testdata/launch_template/bottlerocket_volume.json
  pkg/cfn/builder/testdata/launch_template/custom_ami.json
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes.json
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes_missing_size.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_id.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_preference.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_resource_group_arn.json
  pkg/cfn/builder/testdata/launch_template/placement.json
  pkg/cfn/builder/testdata/launch_template/spot.json
  pkg/cfn/builder/testdata/launch_template/ssh_disabled.json
  pkg/cfn/builder/testdata/launch_template/ssh_enabled.json
  pkg/cfn/builder/testdata/launch_template/standard.json
  pkg/cfn/template/testdata/nodegroup-example-1.json
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
Labels: kind/feature

#6618 Update integration tests and userdocs references to IMDSv1
  examples/05-advanced-nodegroups.yaml
  integration/tests/dry_run/dry_run_test.go
  userdocs/src/usage/dry-run.md
  userdocs/src/usage/eks-managed-nodes.md
Labels: skip-release-notes

#6624 Revert defaulting to IMDSv2
  examples/05-advanced-nodegroups.yaml
  integration/tests/dry_run/dry_run_test.go
  pkg/actions/nodegroup/testdata/al2-force-false-template.json
  pkg/actions/nodegroup/testdata/al2-no-force-template.json
  pkg/actions/nodegroup/testdata/al2-updated-template.json
  pkg/actions/nodegroup/testdata/br-force-false-template.json
  pkg/actions/nodegroup/testdata/br-force-true-template.json
  pkg/actions/nodegroup/testdata/br-updated-template.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/bottlerocket.json
  pkg/cfn/builder/testdata/launch_template/bottlerocket_additional_encrypted_volume.json
  pkg/cfn/builder/testdata/launch_template/bottlerocket_volume.json
  pkg/cfn/builder/testdata/launch_template/custom_ami.json
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes.json
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes_missing_size.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_id.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_preference.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_resource_group_arn.json
  pkg/cfn/builder/testdata/launch_template/placement.json
  pkg/cfn/builder/testdata/launch_template/spot.json
  pkg/cfn/builder/testdata/launch_template/ssh_disabled.json
  pkg/cfn/builder/testdata/launch_template/ssh_enabled.json
  pkg/cfn/builder/testdata/launch_template/standard.json
  pkg/cfn/template/testdata/nodegroup-example-1.json
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/usage/dry-run.md
  userdocs/src/usage/eks-managed-nodes.md
Labels: skip-release-notes

#6623 Add release notes for 0.142.0
  docs/release_notes/0.142.0.md
Labels: skip-release-notes

#6628 Fix readiness probe in HTTP test
  integration/data/test-http.yaml
Labels: kind/bug, area/testing

#6631 Enforce IMDSv2 by default
  examples/05-advanced-nodegroups.yaml
  integration/tests/dry_run/dry_run_test.go
  pkg/actions/nodegroup/testdata/al2-force-false-template.json
  pkg/actions/nodegroup/testdata/al2-no-force-template.json
  pkg/actions/nodegroup/testdata/al2-updated-template.json
  pkg/actions/nodegroup/testdata/br-force-false-template.json
  pkg/actions/nodegroup/testdata/br-force-true-template.json
  pkg/actions/nodegroup/testdata/br-updated-template.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/launch_template/bottlerocket.json
  pkg/cfn/builder/testdata/launch_template/bottlerocket_additional_encrypted_volume.json
  pkg/cfn/builder/testdata/launch_template/bottlerocket_volume.json
  pkg/cfn/builder/testdata/launch_template/custom_ami.json
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes.json
  pkg/cfn/builder/testdata/launch_template/launch_template_additional_volumes_missing_size.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_id.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_preference.json
  pkg/cfn/builder/testdata/launch_template/launch_template_with_capacity_reservation_resource_group_arn.json
  pkg/cfn/builder/testdata/launch_template/placement.json
  pkg/cfn/builder/testdata/launch_template/spot.json
  pkg/cfn/builder/testdata/launch_template/ssh_disabled.json
  pkg/cfn/builder/testdata/launch_template/ssh_enabled.json
  pkg/cfn/builder/testdata/launch_template/standard.json
  pkg/cfn/template/testdata/nodegroup-example-1.json
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/usage/dry-run.md
  userdocs/src/usage/eks-managed-nodes.md
Labels: kind/improvement

#6639 Add support for EKS 1.27
  integration/tests/managed/managed_nodegroup_test.go
  integration/tests/params.go
  integration/tests/trainium/trainium_test.go
  pkg/actions/cluster/upgrade.go
  pkg/actions/cluster/upgrade_test.go
  pkg/actions/nodegroup/testdata/al2-updated-template.json
  pkg/actions/nodegroup/testdata/br-updated-template.json
  pkg/addons/default/assets/coredns-1.27.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/introduction.md
  userdocs/src/usage/container-runtime.md
Labels: kind/feature

#6643 Updated bufpipe dependency from 1.0.3 to 1.0.4
  go.mod
  go.sum
  pkg/awsapi/cloudtrail.go
Labels: dependencies, area/tech-debt

#6644 Upgrade sourcegraph/go-diff from 0.6.2 to 0.7.1
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#6638 Set default Windows volume name to /dev/sda1
  pkg/cfn/builder/block_device_mapping.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/testdata/launch_template/windows.json
Labels: kind/bug

#6389 Clean up ALBs using `spec.ingressClassName` and ALB security groups
  pkg/elb/cleanup.go
  pkg/elb/ingress.go
Labels: kind/bug

#6646 Bump schemer from v0.0.0-2021 to v0.0.0-2023
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#6649 Fix logging stack events logic for Trainium and Inferentia integration tests
  integration/tests/inferentia/inferentia_test.go
  integration/tests/trainium/trainium_test.go
Labels: area/testing, area/tech-debt

#6630 port Add ready plugin to CoreDNS and use health.lameduck for a safer shutdown to 1.25, 1.26 and 1.27
  pkg/addons/default/assets/coredns-1.25.json
  pkg/addons/default/assets/coredns-1.26.json
  pkg/addons/default/assets/coredns-1.27.json
  pkg/addons/default/testdata/sample-1.22.json
  pkg/addons/default/testdata/sample-1.25.json
Labels: kind/improvement

#6651 Allow creating subnets with resource-based hostnames
  examples/02-custom-vpc-cidr-no-nodes.yaml
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/cfn/builder/vpc_ipv4.go
  pkg/cfn/builder/vpc_ipv6.go
Labels: kind/feature

#6655 Updated IAM policy statement for loadbalancer controller
  pkg/cfn/builder/statement.go
Labels: kind/improvement
