Repository eksctl-io/eksctl, pull requests merged in 2023-07, with the labels that each got.

#6747 Fix documentation for EKS interface endpoint
  userdocs/src/usage/eks-private-cluster.md
Labels: kind/docs, area/docs

#6432 Migrate to sdk v2 - configuration loading
  Makefile
  go.mod
  go.sum
  pkg/actions/cluster/cluster.go
  pkg/actions/cluster/delete_test.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/unowned.go
  pkg/actions/cluster/unowned_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/awsapi/iam.go
  pkg/awsapi/ssm.go
  pkg/credentials/filecache.go
  pkg/credentials/filecache_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/create/nodegroup_test.go
  pkg/ctl/delete/nodegroup.go
  pkg/ctl/drain/nodegroup.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/update/nodegroup.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/eks/api.go
  pkg/eks/apiv2.go
  pkg/eks/fakes/fake_instance_selector.go
  pkg/eks/instance_selector_test.go
  pkg/eks/logging_retryer.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/generate.go
  pkg/eks/nodegroup_service.go
  pkg/eks/retryer_v2.go
  pkg/eks/services_v2.go
  pkg/testutils/mockprovider/mock_provider.go
Labels: technical debt, area/tech-debt

#6756 fix index out of range error when aws-node, kube-proxy or coredns are missing
  pkg/addons/default/addons.go
  pkg/addons/default/aws_node.go
  pkg/addons/default/coredns.go
  pkg/addons/default/kube_proxy.go
Labels: kind/bug

#6754 Bump dependencies
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#6758 Replaced weaveworksbot with eksctlbot in workflows and actions
  .github/actions/setup-identity/action.yaml
  .github/release-drafter.yml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-candidate.yaml
  .github/workflows/publish-release.yaml
  .github/workflows/rebase.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  .goreleaser.brew.yml
Labels: kind/improvement

#6760 Add release notes for 0.148
  docs/release_notes/0.148.0.md
Labels: skip-release-notes

#6677 Pin K8s dependencies chain to 1.25
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: technical debt, dependencies, area/tech-debt

#6763 Adding Inf2 and trn1n support
  integration/tests/inferentia/inferentia_test.go
  integration/tests/trainium/trainium_test.go
  pkg/addons/assets/efa-device-plugin.yaml
  pkg/addons/assets/neuron-device-plugin.yaml
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/utils/instance/instance.go
Labels: kind/feature

#6773 Revert "Support for Inf2 and trn1n instance types"
  integration/tests/inferentia/inferentia_test.go
  integration/tests/trainium/trainium_test.go
  pkg/addons/assets/efa-device-plugin.yaml
  pkg/addons/assets/neuron-device-plugin.yaml
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/utils/instance/instance.go
Labels: skip-release-notes

#6777 Fix generating mocks for aws-sdk-go-v2 interfaces
  Makefile
Labels: kind/bug, area/ci

#6768 Update current github urls with new eksctl-io github organisation urls
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/request-for-help.md
  .github/workflows/greetings.yml
  .github/workflows/publish-release-type.yaml
  .github/workflows/update-generated.yaml
  .goreleaser-local.yaml
  .goreleaser.brew.yml
  .goreleaser.yml
  ATTRIBUTIONS.md
  COMMUNITY.md
  CONTRIBUTING.md
  LICENSE
  README.md
  docs/contributor-meetings.md
  docs/current-001-node_bootstrap.md
  docs/proposal-000-template.md
  docs/proposal-002_existing-vpc.md
  docs/proposal-003-extending-use-of-config-file.md
  docs/proposal-006-build-improvements.md
  docs/proposal-007-apply.md
  docs/proposal-008-flux2.md
  docs/release_notes/0.1.38.md
  docs/release_notes/0.1.39.md
  docs/release_notes/0.2.0.md
  docs/release_notes/0.2.1.md
  docs/release_notes/0.3.0.md
  docs/release_notes/0.47.0.md
  docs/release_notes/0.71.0.md
  integration/scripts/download-previous-release.sh
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/identity_provider.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/az/az.go
  pkg/eks/services_v2.go
  userdocs/mkdocs.yml
  userdocs/src/announcements/managed-nodegroups-announcement.md
  userdocs/src/announcements/nodegroup-override-announcement.md
  userdocs/src/community.md
  userdocs/src/index.md
  userdocs/src/introduction.md
  userdocs/src/stylesheets/extra.css
  userdocs/src/usage/autoscaling.md
  userdocs/src/usage/creating-and-managing-clusters.md
  userdocs/src/usage/eks-managed-nodes.md
  userdocs/src/usage/gitops-v2.md
  userdocs/src/usage/instance-selector.md
  userdocs/src/usage/nodegroup-taints.md
  userdocs/src/usage/outposts.md
  userdocs/src/usage/troubleshooting.md
  userdocs/src/usage/unowned-clusters.md
  userdocs/src/usage/vpc-configuration.md
  userdocs/src/usage/vpc-subnet-settings.md
Labels: kind/feature

#6787 Fix `AWS_REGION` and `AWS_DEFAULT_REGION` support for eksctl commands
  pkg/eks/api.go
  pkg/eks/apiv2.go
Labels: kind/bug, regression

#6788 Bump dependencies
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#6799 Release notes for 0.149.0
  docs/release_notes/0.149.0.md
Labels: skip-release-notes

#6800 Fix origin check in release script
  build/scripts/tag-common.sh
Labels: kind/bug, area/ci

#6769 Switch from Docker Hub registry to ECR registry
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  Makefile.docker
  README.md
  userdocs/src/introduction.md
Labels: kind/feature

#6803 Bump dependencies
  go.mod
  go.sum
  pkg/awsapi/cloudwatchlogs.go
  pkg/awsapi/iam.go
Labels: dependencies, area/tech-debt

#6805 Add announcement for transfer to new Github Organisation
  userdocs/theme/main.html
Labels: kind/docs, area/docs

#6813 Bundle dependabot updates
  go.mod
  go.sum
Labels: skip-release-notes, dependencies

#6778 Migrate to mockery v2
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  .mockery.yaml
  .requirements
  ATTRIBUTIONS.md
  Dockerfile
  Makefile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocks/mocks.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
  pkg/eks/mocksv2/generate.go
  pkg/eks/nodegroup.go
  tools.go
Labels: kind/improvement, area/tech-debt

#6816 Release notes for 0.150.0
  docs/release_notes/0.150.0.md
Labels: skip-release-notes

#6819 Bump mockery from 2.30.17 to 2.32.0
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#6828 Remove mockery config from `.dockerignore`
  .dockerignore
Labels: kind/bug

#6829 Update release notes for 0.150
  docs/release_notes/0.150.0.md
Labels: skip-release-notes

#6830 Bump dependencies
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
Labels: skip-release-notes

#6814 Select one subnet for AZs where multiple are present and no VPC config provided
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/vpc_test.go
  pkg/vpc/vpc.go
Labels: kind/bug, area/aws-vpc

#6804 Support custom AMIs for self-managed Windows nodegroups
  examples/32-windows-nodes-with-containerd.yaml
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/nodebootstrap/powershell/powershell.go
  pkg/nodebootstrap/powershell/powershell_test.go
  pkg/nodebootstrap/windows.go
  pkg/nodebootstrap/windows_test.go
  userdocs/src/announcements/nodegroup-override-announcement.md
  userdocs/src/usage/custom-ami-support.md
Labels: kind/feature

#6832 Paginate instance type offerings response
  pkg/az/az.go
  pkg/az/az_test.go
Labels: kind/bug, area/nodegroup, area/managed-nodegroup

#6704 Remove support for EKS 1.22
  integration/tests/unowned_cluster/unowned_cluster_test.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/upgrade_test.go
  pkg/actions/fargate/create_test.go
  pkg/actions/nodegroup/get_test.go
  pkg/addons/default/assets/coredns-1.22.json
  pkg/addons/default/coredns_test.go
  pkg/addons/default/kube_proxy_test.go
  pkg/addons/default/testdata/sample-1.23.json
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/introduction.md
Labels: kind/improvement

#6842 Removing unused workflow
  .github/workflows/dependabot-bundler.yaml
Labels: skip-release-notes

#6836 Cleanup Flux Integration
  integration/tests/gitops/flux_test.go
  integration/tests/params.go
  pkg/flux/flux.go
  pkg/flux/flux_test.go
  userdocs/src/usage/gitops-v2.md
Labels: area/gitops, area/tech-debt

#6841 Fix setting link-time variables for release version
  .goreleaser-local.yaml
  .goreleaser.yml
Labels: kind/bug, area/build-and-release, area/ci

#6840 Fix error with tar in `Post Cache go-build and mod` step
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
Labels: kind/bug, area/ci

#6852 Bump dependencies
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/test-and-build.yaml
  go.mod
  go.sum
  pkg/awsapi/cloudformation.go
  pkg/eks/mocksv2/CloudFormation.go
Labels: dependencies, area/tech-debt

#6850 Support custom Ubuntu AMIs for EKS-managed nodegroups
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  userdocs/src/usage/custom-ami-support.md
Labels: kind/feature, area/managed-nodegroup

#6859 Bump dependencies
  go.mod
  go.sum
  pkg/awsapi/autoscaling.go
Labels: technical debt, dependencies, area/tech-debt

#6860 Add release notes for 0.151
  docs/release_notes/0.151.0.md
Labels: skip-release-notes

#6868 Fix `k8s.io/kubernetes` version
  go.mod
Labels: dependencies, area/tech-debt

#6851 Add option to print specific events when running `eksctl describe-stacks`
  integration/tests/params.go
  pkg/ctl/utils/describe_stacks.go
Labels: kind/feature, area/general-cli
