Repository eksctl-io/eksctl, pull requests merged in 2023-06, with the labels that each got.

#6645 Only retry on appropriate API Errors when calling `eks:DescribeUpdate`
  pkg/actions/cluster/delete.go
  pkg/cfn/manager/delete_tasks.go
  pkg/eks/fargate.go
  pkg/eks/waiter/waiter.go
  pkg/fargate/fargate.go
  pkg/iam/oidc/api.go
  pkg/utils/apierrors/errors.go
  pkg/utils/apierrors/errors_test.go
Labels: kind/bug, area/upgrades

#6659 Add integration tests for resource-based hostnames
  integration/tests/kms_subnet/kms_subnet_test.go
  integration/tests/kms_subnet/testdata/kms-subnet-cluster.yaml
Labels: area/testing, kind/improvement

#6664 Add release notes for 0.144
  docs/release_notes/0.144.0.md
Labels: skip-release-notes

#6660 Cleanup of readme and contributing docs, fixed formatting and typos
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/release_notes/0.144.0.md
  snap/snapcraft.yaml
Labels: technical debt, area/tech-debt

#6667 Updated wellKnownPolicy for Cluster Autoscaler and LoadBalancer Contr…
  pkg/cfn/builder/statement.go
Labels: kind/improvement

#6675 Make the output stream for eksctl command configurable
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/create_test.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/get/addon.go
  pkg/ctl/get/cluster.go
  pkg/ctl/get/fargate.go
  pkg/ctl/get/iamidentitymapping.go
  pkg/ctl/get/iamserviceaccount.go
  pkg/ctl/get/identityprovider.go
  pkg/ctl/get/labels.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/utils/describe_stacks.go
Labels: kind/feature, area/general-cli

#6674 Bump dependencies
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/cloudformation.go
  pkg/awsapi/cloudtrail.go
  pkg/awsapi/iam.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
Labels: technical debt, dependencies, area/tech-debt

#6678 Add notes for release 0.145.0
  docs/release_notes/0.145.0.md
Labels: skip-release-notes

#6690 Bump dependencies
  .github/workflows/docker-publish.yaml
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#6692 Update vpc-cni to 1.12.6
  pkg/addons/default/assets/aws-node.yaml
  pkg/addons/default/aws_node_generate.go
  pkg/addons/default/aws_node_test.go
Labels: kind/improvement

#6697 New eksctl slack channel
  .github/workflows/exclude-file.txt
  COMMUNITY.md
  CONTRIBUTING.md
  README.md
  userdocs/src/community.md
  userdocs/src/index.md
  userdocs/src/introduction.md
Labels: kind/docs, area/docs

#6701 Release notes for 0.146.0
  docs/release_notes/0.146.0.md
Labels: skip-release-notes

#6729 Update docs with `preserve` option to create addon resolveConflicts
  userdocs/src/usage/addons.md
Labels: kind/docs, area/docs

#6707 Fix CoreDNS probes for Kubernetes 1.26
  pkg/addons/default/assets/coredns-1.26.json
  pkg/addons/default/testdata/sample-1.22.json
  pkg/addons/default/testdata/sample-1.25.json
Labels: kind/improvement

#6730 Bump dependencies
  .github/workflows/docker-publish.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/cloudtrail.go
  pkg/awsapi/cloudwatchlogs.go
  pkg/awsapi/iam.go
  pkg/eks/mocksv2/CloudWatchLogs.go
Labels: dependencies, area/tech-debt

#6695 Use nodeAffinity to determine if an addon supports ARM64
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/create_test.go
  pkg/addons/default/addons.go
  pkg/addons/default/aws_node.go
  pkg/addons/default/aws_node_test.go
  pkg/addons/default/coredns.go
  pkg/addons/default/coredns_test.go
  pkg/addons/default/kube_proxy.go
  pkg/addons/default/kube_proxy_test.go
Labels: kind/improvement

#6735 Add identity action to update-generated workflow
  .github/workflows/update-generated.yaml
Labels: technical debt, area/tech-debt

#6736 Release notes for 0.147.0
  docs/release_notes/0.147.0.md
Labels: skip-release-notes

#6746 Added new logo and favicon assets
  .gitignore
  README.md
  userdocs/mkdocs.yml
  userdocs/src/index.md
  userdocs/src/stylesheets/extra.css
  userdocs/theme/assets/images/favicon.png
  userdocs/theme/assets/images/logo.png
Labels: kind/docs, area/docs

#6742 Bump dependencies
  go.mod
  go.sum
Labels: dependencies, area/tech-debt
