Repository eksctl-io/eksctl, pull requests merged in 2023-10, with the labels that each got.

#7126 Fix coredns 1.28 asset
  pkg/addons/default/assets/coredns-1.28.json
Labels: kind/bug

#7116 Set AWS credential expiry window to 30 minutes
  go.mod
  go.sum
  pkg/eks/api_test.go
  pkg/eks/apiv2.go
Labels: kind/improvement

#7029 Fix ELB cleanup failure due to resource name end with a hyphen
  pkg/elb/cleanup.go
  pkg/elb/cleanup_test.go
  pkg/elb/elb_suite_test.go
Labels: kind/bug

#7149 Add release notes for 0.162
  docs/release_notes/0.162.0.md
Labels: skip-release-notes

#7170 Bump dependencies and update build image
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/greetings.yml
  .github/workflows/link-checker.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: dependencies, area/tech-debt, area/ci

#7173 Update build distros workflow to save disk space
  .github/workflows/build-all-distros-nightly.yaml
Labels: kind/bug, area/ci

#7201 Add support for P5 instances
  pkg/utils/instance/instance.go
Labels: kind/feature

#7178 Automatically update coredns assets using Github workflows
  .github/workflows/update-generated.yaml
  Makefile
  pkg/addons/default/scripts/update_coredns_assets.go
Labels: kind/improvement

#7205 Fix kOps privilege escalation vulnerability, update permissions for stale workflow and dependencies
  .github/workflows/stale.yml
  go.mod
  go.sum
  pkg/awsapi/elasticloadbalancingv2.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: dependencies, area/tech-debt

#7206 Release notes for 0.163.0
  docs/release_notes/0.163.0.md
Labels: skip-release-notes

#7090 Add `eksctl utils update-cluster-vpc-config` to update the cluster VPC config
  .mockery.yaml
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/update_cluster_vpc.go
  pkg/ctl/utils/mocks/VPCConfigUpdater.go
  pkg/ctl/utils/nodegroup_health.go
  pkg/ctl/utils/set_public_access_cidrs.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
  pkg/ctl/utils/update_cluster_vpc_config.go
  pkg/ctl/utils/update_cluster_vpc_config_test.go
  pkg/ctl/utils/utils.go
  pkg/ctl/utils/vpc_helper.go
  pkg/ctl/utils/vpc_helper_test.go
  pkg/eks/update.go
Labels: area/aws-vpc, kind/improvement, do-not-merge

#7218 Allow mutating control plane subnets and security groups
  examples/38-cluster-subnets-sgs.yaml
  integration/tests/managed/managed_nodegroup_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/apis/eksctl.io/v1alpha5/vpc.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/cfn/builder/cluster.go
  pkg/ctl/cmdutils/update_cluster_vpc.go
  pkg/ctl/utils/mocks/VPCConfigUpdater.go
  pkg/ctl/utils/set_public_access_cidrs.go
  pkg/ctl/utils/update_cluster_endpoint_access.go
  pkg/ctl/utils/update_cluster_vpc_config.go
  pkg/ctl/utils/update_cluster_vpc_config_test.go
  pkg/ctl/utils/vpc_helper.go
  pkg/ctl/utils/vpc_helper_test.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
  userdocs/mkdocs.yml
  userdocs/src/getting-started.md
  userdocs/src/usage/cluster-subnets-security-groups.md
  userdocs/src/usage/vpc-cluster-access.md
Labels: kind/feature

#7217 Don't close error channel early when wait flag is used
  pkg/actions/addon/tasks.go
Labels: kind/bug

#7219 Add release notes for 0.164
  docs/release_notes/0.164.0.md
  userdocs/src/usage/cluster-subnets-security-groups.md
Labels: skip-release-notes

#7230 Fix README Links
  README.md
Labels: kind/docs, area/docs

#7208 Improve CRUD suite runtime
  integration/scripts/ginkgo-parallel-procs.sh
  integration/tests/crud/creategetdelete_test.go
  integration/tests/crud/testdata/scale-nodegroups.yaml
  integration/tests/crud/testdata/taints-max-pods.yaml
  integration/tests/managed/managed_nodegroup_test.go
Labels: area/tech-debt
