Repository eksctl-io/eksctl, pull requests merged in 2023-11, with the labels that each got.

#7246 [CRUD integration] Add wait flag to delete cluster command
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#7248 [CRUD Suite] Delete extra subnet before deleting cluster
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#7250 [CRUD Suite] Delete nodegroups in subnet before the subnet itself
  integration/tests/crud/creategetdelete_test.go
Labels: skip-release-notes

#7267 Bump dependencies
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/docker-publish.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/iam.go
  pkg/awsapi/ssm.go
  pkg/ctl/utils/mocks/VPCConfigUpdater.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: dependencies, area/tech-debt

#7292 Bump aws-sdk dependencies
  go.mod
  go.sum
Labels: technical debt, dependencies, area/tech-debt

#7312 Add support for creating and fetching pod identity associations
  go.mod
  go.sum
  pkg/actions/podidentityassociation/creator.go
  pkg/actions/podidentityassociation/creator_test.go
  pkg/actions/podidentityassociation/fakes/fake_stack_manager.go
  pkg/actions/podidentityassociation/getter.go
  pkg/actions/podidentityassociation/getter_test.go
  pkg/actions/podidentityassociation/podidentityassociation_suite_test.go
  pkg/actions/podidentityassociation/tasks.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/well_known_iam_policy.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/awsapi/eks.go
  pkg/cfn/builder/iam.go
  pkg/cfn/template/iam_helpers.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/pod_identity_association.go
  pkg/ctl/create/create.go
  pkg/ctl/create/pod_identity_association.go
  pkg/ctl/create/pod_identity_association_test.go
  pkg/ctl/get/get.go
  pkg/ctl/get/pod_identity_association.go
  pkg/ctl/get/pod_identity_association_test.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/tasks.go
  pkg/utils/names/names.go
Labels: kind/feature

#7316 Ignore google docs domains for link checker
  .github/workflows/exclude-file.txt
Labels: technical debt, area/tech-debt

#7315 Implement updating and deleting pod identity associations
  integration/tests/pod_identity_associations/pod_identity_associations_test.go
  pkg/actions/addon/tasks.go
  pkg/actions/cluster/owned.go
  pkg/actions/podidentityassociation/creator.go
  pkg/actions/podidentityassociation/deleter.go
  pkg/actions/podidentityassociation/deleter_test.go
  pkg/actions/podidentityassociation/tasks.go
  pkg/actions/podidentityassociation/updater.go
  pkg/actions/podidentityassociation/updater_test.go
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/iam.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/api_test.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/waiters.go
  pkg/cfn/template/iam_helpers.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/pod_identity_association.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/pod_identity_association_test.go
  pkg/ctl/delete/delete.go
  pkg/ctl/delete/pod_identity_association.go
  pkg/ctl/update/pod_identity_association.go
  pkg/ctl/update/update.go
  pkg/eks/tasks.go
  pkg/utils/names/names.go
Labels: kind/feature

#7314 Add release notes for 0.165.0
  docs/release_notes/0.165.0
Labels: skip-release-notes

#7334 Add release notes for 0.165.0
  docs/release_notes/0.165.0.md
Labels: skip-release-notes

#7336 Fix `build-integration-test` for pod_identity_associations
  integration/tests/pod_identity_associations/pod_identity_associations_test.go
Labels: kind/bug, area/ci

#7337 Update build image tag and actions
  .github/workflows/docker-publish.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/autoscaling.go
  pkg/awsapi/cloudformation.go
  pkg/awsapi/cloudtrail.go
  pkg/awsapi/cloudwatchlogs.go
  pkg/awsapi/elasticloadbalancingv2.go
  pkg/ctl/utils/mocks/VPCConfigUpdater.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: technical debt, area/tech-debt
