Repository eksctl-io/eksctl, pull requests merged in 2023-12, with the labels that each got.

#7345 Fix STS interface
  go.sum
  pkg/awsapi/generate/generate.go
  pkg/awsapi/sts.go
Labels: kind/bug, area/ci

#7375 Update reference for bottlerocket settings
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/docs, area/docs

#7343 Add utils command to migrate to pod identity associations
  integration/scripts/ginkgo-parallel-procs.sh
  integration/tests/pod_identity_associations/pod_identity_associations_test.go
  pkg/actions/podidentityassociation/creator.go
  pkg/actions/podidentityassociation/creator_test.go
  pkg/actions/podidentityassociation/deleter.go
  pkg/actions/podidentityassociation/deleter_test.go
  pkg/actions/podidentityassociation/fakes/fake_stack_creator.go
  pkg/actions/podidentityassociation/fakes/fake_stack_updater.go
  pkg/actions/podidentityassociation/migrator.go
  pkg/actions/podidentityassociation/migrator_test.go
  pkg/actions/podidentityassociation/tasks.go
  pkg/actions/podidentityassociation/updater.go
  pkg/actions/podidentityassociation/updater_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/iam.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/iam.go
  pkg/cfn/manager/api.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/iam.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/pod_identity_association.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/create/pod_identity_association.go
  pkg/ctl/utils/migrate_to_pod_identity.go
  pkg/ctl/utils/utils.go
  userdocs/src/usage/pod-identity-associations.md
Labels: kind/feature

#7379 Generate deep copies of IAMStatement
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
Labels: area/build-and-release, skip-release-notes

#7381 Skip pod identity migration integration tests
  integration/tests/pod_identity_associations/pod_identity_associations_test.go
Labels: skip-release-notes

#7378 Add release notes for 0.166
  docs/release_notes/0.166.0.md
Labels: skip-release-notes

#7405 Fix log message around used EC2 key pair
  pkg/ssh/loader.go
Labels: kind/bug, area/general-cli

#7407 [PodID Test] Skip role creation if already existing
  integration/tests/pod_identity_associations/pod_identity_associations_test.go
Labels: skip-release-notes

#7408 Bump dependencies
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/stale.yml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/autoscaling.go
  pkg/awsapi/cloudformation.go
  pkg/awsapi/cloudtrail.go
  pkg/awsapi/cloudwatchlogs.go
  pkg/awsapi/eks.go
  pkg/awsapi/elasticloadbalancing.go
  pkg/awsapi/elasticloadbalancingv2.go
  pkg/awsapi/iam.go
  pkg/awsapi/outposts.go
  pkg/awsapi/ssm.go
  pkg/ctl/utils/mocks/VPCConfigUpdater.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: dependencies, area/tech-debt

#7420 Bump AWS dependencies, fix test
  go.mod
  go.sum
  pkg/awsapi/eks.go
  pkg/eks/mocksv2/EKS.go
  pkg/printers/testdata/jsontest_2clusters.golden
  pkg/printers/testdata/jsontest_single.golden
  pkg/printers/testdata/yamltest_2clusters.golden
  pkg/printers/testdata/yamltest_single.golden
Labels: dependencies, area/tech-debt

#7419 Add support for ca-west-1
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/getting-started.md
Labels: kind/feature

#7422 Add support for fetching and deleting EKS Access Entries
  integration/scripts/ginkgo-parallel-procs.sh
  integration/tests/accessentries/accessentries_test.go
  integration/tests/dry_run/dry_run_test.go
  pkg/accessentry/service.go
  pkg/actions/accessentry/fakes/fake_stack_remover.go
  pkg/actions/accessentry/getter.go
  pkg/actions/accessentry/getter_test.go
  pkg/actions/accessentry/remover.go
  pkg/actions/accessentry/remover_test.go
  pkg/actions/accessentry/task.go
  pkg/apis/eksctl.io/v1alpha5/access_entry_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/cluster.go
  pkg/cfn/manager/delete_tasks.go
  pkg/ctl/cmdutils/access_entry.go
  pkg/ctl/create/access_entry.go
  pkg/ctl/delete/access_entry.go
  pkg/ctl/delete/access_entry_test.go
  pkg/ctl/delete/delete.go
  pkg/ctl/get/access_entry.go
  pkg/ctl/get/access_entry_test.go
  pkg/ctl/get/get.go
  pkg/ctl/utils/export_test.go
  pkg/ctl/utils/update_authentication_mode.go
  pkg/ctl/utils/update_authentication_mode_test.go
  pkg/ctl/utils/update_cluster_vpc_config_test.go
  pkg/ctl/utils/utils.go
  pkg/ctl/utils/utils_test.go
Labels: kind/feature

#7423 Add documentation for EKS Access Entries support
  examples/40-access-entries.yaml
  userdocs/mkdocs.yml
  userdocs/src/getting-started.md
  userdocs/src/usage/access-entries.md
  userdocs/theme/home.html
Labels: kind/docs, area/docs

#7424 Add release notes for 0.167.0
  docs/release_notes/0.167.0.md
Labels: skip-release-notes

#7429 Add missing permission 'deletecollection for pvc' to emr-containers role, needed for Spark jobs running on AWS "EMR on EKS" Service version >= 6.12
  pkg/authconfigmap/assets/emr-containers-rbac.yaml
Labels: kind/improvement

#7204 Ignore unsupported zone types when creating a zone mapping
  pkg/vpc/zone.go
Labels: kind/bug
