Repository eksctl-io/eksctl, pull requests merged in 2023-09, with the labels that each got.

#7033 Add release notes for 0.156.0
  docs/release_notes/0.156.0.md
Labels: skip-release-notes

#7030 Disallow passing a vpc.securityGroup with external security group rules
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/create_test.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/vpc_ipv4.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
Labels: kind/bug

#7047 Add note on how to use `--include/exclude` flags when creating iamserviceaccounts
  userdocs/src/usage/iamserviceaccounts.md
Labels: kind/docs, area/docs

#7050 Material version updates and added social cards, cookie consent and feedback widgets
  .gitignore
  Makefile.docs
  README.md
  userdocs/mkdocs.yml
  userdocs/requirements.txt
  userdocs/src/img/favicon.png
  userdocs/src/img/logo.png
Labels: kind/feature, kind/docs

#7051 Bump dependencies
  go.mod
  go.sum
  pkg/awsapi/elasticloadbalancingv2.go
Labels: skip-release-notes, dependencies

#7052 Release notes for 0.157.0
  docs/release_notes/0.157.0.md
Labels: skip-release-notes

#7063 Corrected Chocolatey Install Command
  README.md
  userdocs/src/introduction.md
Labels: kind/docs, area/docs

#7032 Call `kubectl version` command with `--output=json` flag
  pkg/ctl/create/cluster.go
  pkg/info/info.go
  pkg/utils/kubeconfig/export_test.go
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
  pkg/utils/kubectl/export_test.go
  pkg/utils/kubectl/fakes/fake_kubernetes_version_getter.go
  pkg/utils/kubectl/kubectl.go
  pkg/utils/kubectl/kubectl_suite_test.go
  pkg/utils/kubectl/kubectl_test.go
  pkg/utils/kubectl/testdata/fake-version
Labels: kind/bug

#7068 Upgrade goproxy to fix DoS vulnerability
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#7067 Bump `github.com/cloudflare/cfssl` to fix indirect deps DOS vulnerability
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#7072 Release notes for 0.158.0
  docs/release_notes/0.158.0.md
Labels: skip-release-notes

#7075 Update to Go 1.20
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
  .golangci.yml
  .requirements
  ATTRIBUTIONS.md
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  integration/matchers/kubernetes.go
  integration/tests/existing_vpc/existing_vpc_test.go
  integration/tests/ipv6/ipv6_test.go
  pkg/actions/nodegroup/nodegroup_suite_test.go
  pkg/apis/eksctl.io/v1alpha5/generate.go
  pkg/cfn/builder/vpc.go
  pkg/ctl/cmdutils/scale.go
  pkg/executor/executor.go
  pkg/karpenter/karpenter.go
  pkg/karpenter/providers/helm/helm_test.go
  pkg/kubernetes/client.go
  pkg/nodebootstrap/assets/assets.go
  pkg/outposts/cluster_extender.go
Labels: area/tech-debt

#7087 Fix doc example for bottlerocket bootstrap container
  userdocs/src/usage/custom-ami-support.md
Labels: kind/docs, area/docs

#7065 Allow managed suite specs to run in parallel
  integration/tests/managed/managed_nodegroup_test.go
  integration/tests/params.go
  integration/tests/update/update_cluster_test.go
  integration/utilities/kube/kube.go
Labels: area/tech-debt

#7074 Update github actions and tidy up
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/cache-dependencies.yaml
  .github/workflows/docker-publish.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
  go.mod
  go.sum
  pkg/awsapi/cloudwatchlogs.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: skip-release-notes, dependencies

#7091 Add release notes for 0.159.0
  docs/release_notes/0.159.0.md
Labels: skip-release-notes

#7108 Add support for EKS 1.28
  go.sum
  pkg/actions/cluster/upgrade.go
  pkg/actions/cluster/upgrade_test.go
  pkg/actions/nodegroup/testdata/al2-updated-template.json
  pkg/addons/default/assets/coredns-1.28.json
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  userdocs/src/introduction.md
Labels: kind/feature

#7109 Bump dependencies
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/docker-publish.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-docs.yaml
  .github/workflows/publish-release-type.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-merge.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-build.yaml
  .github/workflows/update-generated.yaml
  .requirements
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: dependencies, area/tech-debt

#7113 Release notes for 0.160.0
  docs/release_notes/0.160.0.md
Labels: skip-release-notes

#7077 Move addons related tasks to actions package
  pkg/actions/addon/addon.go
  pkg/actions/addon/delete.go
  pkg/actions/addon/tasks.go
  pkg/actions/cluster/owned.go
  pkg/actions/cluster/unowned.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
Labels: area/tech-debt

#7118 Fix `deleteAddonsStacksTasks` generator
  pkg/actions/addon/create_test.go
  pkg/actions/addon/delete.go
  pkg/actions/addon/delete_test.go
  pkg/actions/addon/fakes/fake_stack_manager.go
  pkg/actions/addon/tasks.go
  pkg/actions/addon/update_test.go
Labels: skip-release-notes

#7115 Refine log statements using `%w` for better formatting and UX
  integration/tests/params.go
  pkg/actions/cluster/delete.go
  pkg/actions/nodegroup/drain.go
  pkg/actions/nodegroup/get.go
Labels: kind/improvement

#7117 Make EKS 1.27 default
  integration/tests/managed/managed_nodegroup_test.go
  integration/tests/unowned_cluster/unowned_cluster_test.go
  integration/tests/update/update_cluster_test.go
  integration/utilities/cluster/cluster.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
  userdocs/src/introduction.md
Labels: kind/feature

#7121 Upgrade go-restful
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#7120 Update gomarkdown to fix out-of-bounds read while parsing citations
  go.mod
  go.sum
Labels: dependencies, area/tech-debt

#7092 Docs Landing page
  .github/release-drafter.yml
  COMMUNITY.md
  README.md
  userdocs/README.md
  userdocs/mkdocs.yml
  userdocs/src/adopters.md
  userdocs/src/community.md
  userdocs/src/getting-started.md
  userdocs/src/index.md
  userdocs/src/installation.md
  userdocs/src/javascripts/extra.js
  userdocs/src/stylesheets/extra.css
  userdocs/theme/assets/images/cluster-demo.png
  userdocs/theme/assets/images/illustration.png
  userdocs/theme/assets/images/outposts.png
  userdocs/theme/home.html
  userdocs/theme/main.html
Labels: kind/feature, kind/docs, area/docs

#7122 Release notes
  docs/release_notes/0.161.0.md
Labels: skip-release-notes
