Repository eksctl-io/eksctl, pull requests merged in 2024-04, with the labels that each got.

#7712 Bump dependencies
  go.mod
  go.sum
  pkg/awsapi/cloudformation.go
  pkg/awsapi/iam.go
Labels: skip-release-notes

#7715 Fix arn build logic to support different aws partitions
  pkg/actions/karpenter/create.go
  pkg/cfn/builder/fargate.go
  pkg/connector/connector.go
Labels: kind/bug

#7707 Fix reusing instanceRoleARN for nodegroups authorized with access entry
  .mockery.yaml
  integration/tests/accessentries/accessentries_test.go
  integration/tests/accessentries/testdata/node-role.yaml
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/nodegroup.go
  pkg/apis/eksctl.io/v1alpha5/access_entry.go
  pkg/cfn/builder/iam.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_access_entry_test.go
  pkg/cfn/builder/nodegroup_test.go
  pkg/cfn/builder/testdata/nodegroup_access_entry/3.json
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/delete_tasks.go
  pkg/cfn/manager/mocks/NodeGroupResourceSet.go
  pkg/cfn/manager/mocks/NodeGroupStackManager.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks.go
  pkg/cfn/manager/tasks_test.go
  pkg/cfn/manager/unmanaged_nodegroup_test.go
  pkg/ctl/create/cluster_test.go
  pkg/ctl/delete/nodegroup.go
  userdocs/src/usage/access-entries.md
Labels: kind/bug, area/nodegroup

#7722 Disable IMDSv1 in unowned integration tests
  integration/tests/unowned_cluster/unowned_cluster_test.go
Labels: kind/improvement, area/tech-debt

#7723 [Release drafter] Treat RCs as full releases when drafting notes
  .github/release-drafter.yml
Labels: kind/improvement

#7727 Fix creating pod identities
  pkg/actions/podidentityassociation/creator.go
  pkg/actions/podidentityassociation/deleter.go
Labels: skip-release-notes
