Repository eksctl-io/eksctl, pull requests merged in 2024-12, with the labels that each got.

#8040 Reword IRSA warning message
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
Labels: area/tech-debt

#8036 userdocs: fix comment for custom managed nodegroup
  userdocs/src/usage/nodegroup-managed.md
Labels: kind/docs

#8070 add readme note for auto mode and hybrid nodes
  README.md
Labels: skip-release-notes

#8071 Add IAM capability if a custom IAM role is provided for Auto Mode
  pkg/cfn/builder/cluster.go
Labels: kind/bug

#8041 Add support for C8g and R8g instance types
  pkg/utils/instance/instance.go
  userdocs/src/usage/arm-support.md
Labels: kind/feature, area/nodegroup

#8087 Support EKS managed nodegroup node repair config
  examples/44-node-repair.yaml
  go.mod
  go.sum
  goformation/cloudformation/eks/aws-eks-nodegroup.go
  goformation/cloudformation/eks/aws-eks-nodegroup_noderepairconfig.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/testdata/launch_template/node-repair-enabled.json
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/create_cluster.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/nodegroup_test.go
  userdocs/mkdocs.yml
  userdocs/src/usage/nodegroup-node-repair-config.md
Labels: kind/feature, area/managed-nodegroup

#8092 Update excluded contributors from release notes
  .github/release-drafter.yml
Labels: skip-release-notes
