Repository eksctl-io/eksctl, pull requests merged in 2024-10, with the labels that each got.

#6870 cleanup efa installer archive before install
  pkg/nodebootstrap/assets/scripts/efa.al2.sh
  pkg/nodebootstrap/assets/scripts/efa.al2023.sh
  pkg/nodebootstrap/assets/scripts/efa.managed.al2023.boothook
  pkg/nodebootstrap/assets/scripts/efa.managed.boothook
  pkg/nodebootstrap/managed_al2_test.go
Labels: kind/improvement, priority/important-soon

#8001 Add support for M8g instance types
  pkg/utils/instance/instance.go
Labels: kind/feature

#7994 Documentation: correct version drift limits in cluster-upgrade.md
  userdocs/src/usage/cluster-upgrade.md
Labels: kind/docs

#7988 Fix missing ELB listener attribute actions required for AWS Load Balancer Controller v2.9.0
  pkg/cfn/builder/iam_test.go
  pkg/cfn/builder/statement.go
Labels: kind/improvement

#8005 Support EKS zonal shift config
  examples/41-zonal-shift.yaml
  go.mod
  go.sum
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/cluster.go
  pkg/ctl/cmdutils/zonal_shift_config.go
  pkg/ctl/utils/update_zonal_shift_config.go
  pkg/ctl/utils/utils.go
  pkg/printers/testdata/jsontest_2clusters.golden
  pkg/printers/testdata/jsontest_single.golden
  pkg/printers/testdata/yamltest_2clusters.golden
  pkg/printers/testdata/yamltest_single.golden
  userdocs/src/usage/zonal-shift.md
Labels: kind/feature

#8014 Update docs
  userdocs/mkdocs.yml
Labels: kind/docs
