Repository eksctl-io/eksctl, pull requests merged in 2024-07, with the labels that each got.

#7850 Fix SDK paginator mocks
  go.mod
  go.sum
  pkg/actions/cluster/get_test.go
  pkg/actions/cluster/owned_test.go
  pkg/actions/cluster/unowned_test.go
  pkg/actions/nodegroup/create_test.go
  pkg/actions/podidentityassociation/addon_migrator_test.go
  pkg/actions/podidentityassociation/migrator_test.go
  pkg/az/az_test.go
  pkg/cfn/builder/nodegroup_subnets_test.go
  pkg/cfn/builder/vpc_endpoint_test.go
  pkg/cfn/builder/vpc_existing_test.go
  pkg/cfn/manager/api_test.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/create/cluster_test.go
  pkg/eks/api_test.go
  pkg/eks/eks_test.go
  pkg/eks/nodegroup_service_test.go
  pkg/outposts/cluster_extender_test.go
  pkg/outposts/outposts_test.go
  pkg/vpc/vpc_test.go
Labels: area/testing, kind/improvement

#7778 fixed iam permissions bug for karpenter
  pkg/cfn/builder/karpenter.go
  pkg/cfn/builder/karpenter_test.go
Labels: kind/improvement, area/karpenter

#6302 fix runAsRoot (true) efa device plugin bug
  pkg/addons/assets/efa-device-plugin.yaml
Labels: kind/improvement

#6743 Add/hpc7g node arm support
  pkg/addons/assets/efa-device-plugin.yaml
  pkg/utils/instance/instance.go
Labels: kind/improvement, priority/important-longterm

#7851 Add auto-ssm ami resolution for ubuntu
  pkg/ami/ssm_resolver.go
  pkg/ami/ssm_resolver_test.go
  pkg/eks/api_test.go
Labels: kind/improvement

#7870 Avoid creating subnets in disallowed Availability Zone IDs
  pkg/az/az.go
  pkg/az/az_test.go
Labels: kind/improvement

#7879 Refactor: move bare cluster validation to NewCreateClusterLoader
  pkg/apis/eksctl.io/v1alpha5/bare_cluster.go
  pkg/apis/eksctl.io/v1alpha5/bare_cluster_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
  pkg/ctl/cmdutils/create_cluster.go
  pkg/eks/api.go
Labels: skip-release-notes, area/tech-debt

#7878 Retry throttling errors, disable retry rate-limiting
  pkg/eks/retryer_v2.go
  pkg/eks/services_v2.go
Labels: kind/improvement

#7884 Allow limiting the number of nodegroups created in parallel
  pkg/actions/nodegroup/create.go
  pkg/actions/nodegroup/create_test.go
  pkg/cfn/manager/create_tasks.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/interface.go
  pkg/cfn/manager/nodegroup.go
  pkg/cfn/manager/tasks_test.go
  pkg/ctl/cmdutils/create_cluster.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/utils/tasks/tasks.go
Labels: kind/feature
