Repository eksctl-io/eksctl, pull requests merged in 2025-08, with the labels that each got.

#8476 Add namespace configuration support for EKS addons
  build/scripts/update-codegen.sh
  go.mod
  go.sum
  integration/tests/addons/addons_test.go
  pkg/actions/addon/create.go
  pkg/actions/addon/create_test.go
  pkg/actions/addon/get.go
  pkg/actions/addon/get_test.go
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/addon_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/create/addon.go
  pkg/ctl/create/addon_test.go
  pkg/ctl/get/addon.go
  pkg/ctl/update/addon_test.go
  pkg/printers/testdata/jsontest_2clusters.golden
  pkg/printers/testdata/jsontest_single.golden
  pkg/printers/testdata/yamltest_2clusters.golden
  pkg/printers/testdata/yamltest_single.golden
  userdocs/src/usage/addons.md
Labels: kind/feature, area/add-ons

#8479 remove namespace validation for update-addon
  go.mod
  go.sum
  integration/tests/addons/addons_test.go
  pkg/actions/addon/update.go
  pkg/actions/addon/update_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/ctl/update/addon_test.go
Labels: kind/bug

#8478 Add exact match check to use specified addon versions
  pkg/actions/addon/addon.go
  pkg/actions/addon/update_test.go
Labels: kind/bug

#8482 add notify homebrew update workflow
  .github/workflows/homebrew-update.yml
Labels: area/build-and-release, kind/improvement
