Repository eksctl-io/eksctl, pull requests merged in 2025-03, with the labels that each got.

#8267 Update zz_generated.deepcopy.go, also add new make target for the same
  Makefile
  build/scripts/update-codegen.sh
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
Labels: kind/improvement

#8268 Fix failure when VPC CNI is configured to use both iam.withOIDC and useDefaultPodIdentityAssociations
  pkg/actions/addon/tasks.go
  pkg/ctl/create/cluster.go
Labels: kind/improvement

#8288 Reduce blast radius of test that disables api server public access failing
  integration/tests/crud/creategetdelete_test.go
Labels: kind/improvement

#8293 Allow core/default networking addons on auto-mode clusters with mixed node types
  pkg/apis/eksctl.io/v1alpha5/known_addons.go
  pkg/ctl/cmdutils/configfile.go
Labels: kind/bug, area/add-ons

#8300 Default to newest k8s 1.32 version
  pkg/actions/addon/update_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/ctl/cmdutils/filter/nodegroup_filter_test.go
Labels: kind/improvement

#8303 Skip instance type support validation for custom AMI ID
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/nodebootstrap/managed_al2.go
Labels: kind/bug, area/nodegroup

#8308 Update aws-sdk-go-v2 dependencies
  go.mod
  go.sum
  pkg/awsapi/cloudwatchlogs.go
  pkg/awsapi/eks.go
  pkg/awsapi/elasticloadbalancingv2.go
  pkg/awsapi/ssm.go
  pkg/eks/mocksv2/ELBV2.go
Labels: skip-release-notes, dependencies

#8307 Allow specification of IAM permission boundary for Auto Mode's Node Role
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/auto_mode.go
  pkg/apis/eksctl.io/v1alpha5/auto_mode_validation_test.go
  pkg/cfn/builder/auto_mode.go
  pkg/cfn/builder/cluster.go
Labels: kind/feature

#8311 Remove deprecated "set-public-access-cidrs" integration tests
  integration/tests/crud/creategetdelete_test.go
Labels: area/testing, skip-release-notes

#8312 Fix auto mode creation when no permissions boundary is set
  pkg/cfn/builder/auto_mode.go
  pkg/cfn/builder/cluster.go
Labels: kind/bug, skip-release-notes

#8319 Add support for new force parameter when upgrading cluster version
  go.mod
  go.sum
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/awsapi/cloudformation.go
  pkg/ctl/upgrade/cluster.go
  pkg/ctl/upgrade/cluster_test.go
  pkg/eks/update.go
Labels: kind/feature, area/upgrades

#8298 Remove redundant 'typecheck' linter
  .golangci.yml
Labels: area/tech-debt

#8316 Add latest changes to AWS Load Balancer Controller IAM Policy
  pkg/cfn/builder/iam_test.go
  pkg/cfn/builder/statement.go
Labels: kind/improvement
