Repository eksctl-io/eksctl, pull requests merged in 2025-01, with the labels that each got.

#8117 Support for Mexico region (mx-central-1)
  pkg/apis/eksctl.io/v1alpha5/types.go
Labels: kind/feature

#8118 Support create cluster default addon metrics-server
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/known_addons.go
Labels: kind/feature

#8135 Remove SSM install script from AL2; SSM is pre-installed on EKS AL based AMIs
  pkg/nodebootstrap/README.md
  pkg/nodebootstrap/al2_test.go
  pkg/nodebootstrap/assets/assets.go
  pkg/nodebootstrap/assets/scripts/install-ssm.al2.sh
Labels: area/nodegroup, kind/improvement, skip-release-notes

#8140 Enable default addon creation for auto mode clusters
  pkg/actions/addon/tasks.go
  pkg/apis/eksctl.io/v1alpha5/known_addons.go
  pkg/ctl/create/cluster.go
Labels: kind/feature

#8146 Disable metrics-server default addon creation for unsupported regions
  pkg/actions/addon/tasks.go
  pkg/apis/eksctl.io/v1alpha5/known_addons.go
  pkg/ctl/create/cluster.go
Labels: kind/bug

#8149 Fix e2e integration tests
  integration/tests/accessentries/accessentries_test.go
  integration/tests/auto_mode/auto_mode_test.go
Labels: skip-release-notes

#8134 Remove `xtables.lock` which should be managed by the VPC CNI
  pkg/addons/default/assets/aws-node.yaml
  pkg/nodebootstrap/al2023.go
  pkg/nodebootstrap/al2023_test.go
  pkg/nodebootstrap/assets/assets.go
  pkg/nodebootstrap/assets/scripts/al2023-xtables.lock.sh
Labels: area/nodegroup, kind/improvement, skip-release-notes

#8125 Upgrade to go 1.22
  .dockerignore
  .github/actions/setup-build/action.yaml
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/cache-dependencies.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/test-and-build.yaml
  .golangci.yml
  .requirements
  CONTRIBUTING.md
  Dockerfile
  Makefile
  Makefile.common
  Makefile.docker
  build/build_image_manifest
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  build/scripts/build-image-manifest.sh
  build/scripts/install-build-deps.sh
  go.mod
  go.sum
  goformation/go.mod
  goformation/go.sum
Labels: skip-release-notes, dependencies, area/tech-debt

#8166 Bump golang.org/x/crypto from v0.22.0 to v0.32.0
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  pkg/awsapi/cloudtrail.go
  pkg/awsapi/cloudwatchlogs.go
  pkg/awsapi/eks.go
  pkg/awsapi/ssm.go
  pkg/eks/mocksv2/CloudTrail.go
Labels: kind/improvement, dependencies

#8165 Allow disabling default addons with Auto Mode
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/configfile_test.go
Labels: kind/bug
