Repository eksctl-io/eksctl, pull requests merged in 2025-04, with the labels that each got.

#8323 Add AutoModeNodeRole to Beta lambda ExecutionRole
  pkg/cfn/builder/templates/beta-resources.yaml
Labels: kind/bug, skip-release-notes

#8322 Enable creating IPV6 clusters with pod identities in addition to IRSA
  .gitignore
  pkg/apis/eksctl.io/v1alpha5/addon.go
  pkg/apis/eksctl.io/v1alpha5/addon_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/improvement

#8340 Fix eks beta SP for ServiceRole
  pkg/cfn/builder/beta.go
Labels: kind/bug, skip-release-notes

#8341 Fully remove intermediate eksctl build image
  .dockerignore
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/test-and-build.yaml
  .requirements
  Dockerfile
  Makefile.docker
  build/build_image_manifest
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  build/scripts/build-image-manifest.sh
  go.mod
  go.sum
  pkg/awsapi/eks.go
Labels: area/build-and-release, dependencies, area/tech-debt

#8344 Drop support for Ubuntu 18.04 images
  pkg/ami/auto_resolver.go
  pkg/ami/auto_resolver_test.go
  pkg/ami/ssm_resolver.go
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/outposts_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/eks/api_test.go
  pkg/nodebootstrap/userdata.go
  userdocs/src/usage/custom-ami-support.md
Labels: area/nodegroup, area/tech-debt

#8347 Update aws-sdk-go-v2 dependencies and mockery comments
  go.mod
  go.sum
  pkg/actions/addon/mocks/IAMRoleCreator.go
  pkg/actions/addon/mocks/IAMRoleUpdater.go
  pkg/actions/addon/mocks/PodIdentityIAMUpdater.go
  pkg/actions/automode/mocks/cluster_role_manager.go
  pkg/actions/automode/mocks/node_group_drainer.go
  pkg/actions/automode/mocks/role_manager.go
  pkg/actions/cluster/mocks/auto_mode_deleter.go
  pkg/actions/podidentityassociation/mocks/RoleMigrator.go
  pkg/actions/podidentityassociation/mocks/StackDeleter.go
  pkg/automode/mocks/stack_creator.go
  pkg/automode/mocks/stack_deleter.go
  pkg/cfn/manager/mocks/NodeGroupResourceSet.go
  pkg/cfn/manager/mocks/NodeGroupStackManager.go
  pkg/ctl/utils/mocks/VPCConfigUpdater.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: skip-release-notes, dependencies

#8351 Add support for AL2023 arm64 nvidia amiType
  go.mod
  go.sum
  pkg/ami/ssm_resolver.go
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/amitype.go
  pkg/apis/eksctl.io/v1alpha5/defaults.go
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/utils/instance/instance.go
Labels: kind/feature, area/nodegroup

#8349 Enable enclave options in EC2 Launch Template
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/nodegroup_test.go
Labels: kind/feature, area/nodegroup

#8353 Remove ubuntu 2004 pro integration tests
  integration/tests/custom_ami/custom_ami_test.go
Labels: skip-release-notes

#8354 Fix support for non-current-generation ec2 instance types
  cmd/ec2geninfo/main.go
  pkg/utils/instance/instance_types.go
Labels: kind/bug, area/nodegroup

#8357 Fix CoreDNS scheduling on Fargate failing when component label in selector
  go.mod
  go.sum
  pkg/fargate/coredns/coredns.go
  pkg/fargate/coredns/coredns_test.go
Labels: kind/bug, area/fargate

#8359 Update binary install for best practices
  README.md
  userdocs/src/installation.md
Labels: kind/docs

#8358 Fix for `create podidentityassociation` bug in auto-mode clusters
  pkg/actions/podidentityassociation/migrator.go
  pkg/actions/podidentityassociation/migrator_test.go
  pkg/apis/eksctl.io/v1alpha5/zz_generated.deepcopy.go
  pkg/goformation/cloudformation/types/types.go
  userdocs/src/usage/pod-identity-associations.md
Labels: kind/bug, area/podidentity
