Repository eksctl-io/eksctl, pull requests merged in 2025-02, with the labels that each got.

#8173 Enable Bottlerocket on Neuron Instance types (Inferentia and Trainium)
  pkg/addons/assets/neuron-device-plugin.yaml
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/managed_nodegroup_ami_type_test.go
  pkg/utils/instance/instance.go
Labels: kind/feature, area/nodegroup

#8199 Enable NVIDIA Plugin automatically for AL2023 GPU AMIs
  pkg/eks/tasks.go
Labels: kind/feature, area/add-ons

#8200 Add addon name to some logging lines
  pkg/actions/addon/create.go
Labels: area/add-ons, kind/improvement

#8201 New EFA plugin images need a new volume for EFA plugin to mount - `/dev/infiniband`
  pkg/addons/assets/efa-device-plugin.yaml
Labels: area/add-ons, kind/improvement

#8195 Replace `golang.org/x/exp/slices` with `slices`
  go.mod
  integration/utilities/cluster/cluster.go
  pkg/actions/podidentityassociation/iam_role_updater.go
  pkg/ctl/cmdutils/access_entry.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/utils/describe_stacks.go
  pkg/ctl/utils/vpc_helper.go
Labels: skip-release-notes, dependencies

#8206 pre-Generate EC2 instance type details out of band
  cmd/ec2geninfo/main.go
  pkg/ami/ssm_resolver_test.go
  pkg/apis/eksctl.io/v1alpha5/gpu_validation_test.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/managed_nodegroup_ami_type_test.go
  pkg/ctl/create/cluster_test.go
  pkg/eks/instance_selection_test.go
  pkg/utils/instance/instance.go
  pkg/utils/instance/instance_types.go
Labels: kind/improvement, area/tech-debt

#8210 Update building with golang 1.24
  .github/actions/setup-build/action.yaml
  .github/workflows/build-all-distros-nightly.yaml
  .github/workflows/docker-publish.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/ecr-publish.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/publish-release.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/update-generated.yaml
  .golangci.yml
  .requirements
  Dockerfile
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  integration/tests/accessentries/accessentries_test.go
  integration/tests/inferentia/inferentia_test.go
  integration/tests/trainium/trainium_test.go
  pkg/actions/addon/mocks/IAMRoleCreator.go
  pkg/actions/addon/mocks/IAMRoleUpdater.go
  pkg/actions/addon/mocks/PodIdentityIAMUpdater.go
  pkg/actions/automode/mocks/cluster_role_manager.go
  pkg/actions/automode/mocks/node_group_drainer.go
  pkg/actions/automode/mocks/role_manager.go
  pkg/actions/cluster/mocks/auto_mode_deleter.go
  pkg/actions/podidentityassociation/fakes/fake_stack_updater.go
  pkg/actions/podidentityassociation/mocks/RoleMigrator.go
  pkg/actions/podidentityassociation/mocks/StackDeleter.go
  pkg/automode/mocks/stack_creator.go
  pkg/automode/mocks/stack_deleter.go
  pkg/awsapi/cloudformation.go
  pkg/awsapi/eks.go
  pkg/awsapi/iam.go
  pkg/cfn/builder/fakes/fake_cfn_template.go
  pkg/cfn/manager/fakes/fake_stack_manager.go
  pkg/cfn/manager/mocks/NodeGroupResourceSet.go
  pkg/cfn/manager/mocks/NodeGroupStackManager.go
  pkg/ctl/utils/mocks/VPCConfigUpdater.go
  pkg/eks/mocks/ConfigProvider.go
  pkg/eks/mocks/KubeNodeGroup.go
  pkg/eks/mocksv2/ASG.go
  pkg/eks/mocksv2/CloudFormation.go
  pkg/eks/mocksv2/CloudTrail.go
  pkg/eks/mocksv2/CloudWatchLogs.go
  pkg/eks/mocksv2/CredentialsProvider.go
  pkg/eks/mocksv2/EC2.go
  pkg/eks/mocksv2/EKS.go
  pkg/eks/mocksv2/ELB.go
  pkg/eks/mocksv2/ELBV2.go
  pkg/eks/mocksv2/IAM.go
  pkg/eks/mocksv2/Outposts.go
  pkg/eks/mocksv2/SSM.go
  pkg/eks/mocksv2/STS.go
Labels: area/tech-debt

#8213 Fix broken karpenter doc links
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/docs, skip-release-notes

#8212 Fix broken link to "Creating and Managing Clusters"
  userdocs/src/getting-started.md
Labels: kind/docs, skip-release-notes

#8217 Update GPU ec2 instance types in integration tests
  integration/tests/crud/creategetdelete_test.go
Labels: area/testing, skip-release-notes

#8207 Support for setting MarketType/InstanceMarketOptions for use with "capacity-block"
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
  pkg/cfn/builder/managed_launch_template.go
  pkg/cfn/builder/managed_launch_template_test.go
  pkg/cfn/builder/managed_nodegroup.go
  pkg/cfn/builder/nodegroup.go
  pkg/cfn/builder/testdata/launch_template/capacity_block.json
Labels: kind/feature, area/nodegroup

#8220 Placement group should not be created when using a reservation
  pkg/cfn/builder/managed_launch_template.go
Labels: kind/bug, area/nodegroup

#8226 Remove support for p2 instances which require NVIDIA driver <= 470
  cmd/ec2geninfo/main.go
  examples/23-kubeflow-spot-instance.yaml
  pkg/ami/auto_resolver_test.go
  pkg/ami/ssm_resolver_test.go
  pkg/cfn/builder/managed_nodegroup_ami_type_test.go
  pkg/eks/api_test.go
  pkg/eks/instance_selection_test.go
  pkg/eks/tasks_test.go
  pkg/utils/instance/instance_types.go
  userdocs/src/usage/custom-ami-support.md
  userdocs/src/usage/gpu-support.md
  userdocs/src/usage/spot-instances.md
Labels: kind/bug, area/nodegroup

#8228 Add support for creating access entries of type `EC2` for EKS Auto Mode
  pkg/apis/eksctl.io/v1alpha5/access_entry.go
  pkg/apis/eksctl.io/v1alpha5/access_entry_validation_test.go
Labels: kind/feature, area/access-entry

#8231 Re-add support for env var keys from AWS SDK
  pkg/eks/api.go
  pkg/eks/services_v2.go
Labels: area/general-cli, kind/improvement

#8232 Print the computed upgrade version correctly
  pkg/actions/cluster/upgrade.go
Labels: kind/bug, area/upgrades

#8233 Add missing coredns-1.32 json file
  pkg/addons/default/assets/coredns-1.32.json
Labels: kind/bug, area/add-ons

#8240 Re-allow use of the `cnn1-az4` availability zone
  pkg/az/az.go
  pkg/az/az_test.go
Labels: kind/bug, area/regions

#8239 Enable auto-update of ec2 info
  .github/workflows/update-generated.yaml
  Makefile
  cmd/ec2geninfo/main.go
  pkg/utils/instance/instance_types.go
Labels: area/nodegroup, kind/improvement

#8234 Remove intermediate build image from add-on auto-update CI workflow
  .github/workflows/update-generated.yaml
Labels: kind/bug, area/add-ons, skip-release-notes

#8211 Remove unused stringer dependency
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .requirements
  Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  tools.go
Labels: skip-release-notes, dependencies, area/ci

#8241 Remove build container image use from CI workflows
  .github/actions/setup-build/action.yaml
  .github/workflows/cache-dependencies.yaml
  .github/workflows/ecr-publish-build.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release.yaml
  .github/workflows/test-and-build.yaml
  Dockerfile
Labels: skip-release-notes, area/ci

#8242 Remove un-used build dependencies
  .requirements
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  tools.go
Labels: skip-release-notes, dependencies, area/ci

#8246 Do not run ci jobs in forks
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yml
  .github/workflows/update-generated.yaml
Labels: kind/improvement

#8247 Add support for allow/deny regexp(s) in instanceSelector
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/eks/instance_selector_test.go
  pkg/eks/nodegroup_service.go
Labels: area/nodegroup, kind/improvement

#8243 GPUs != Neuron Devices (when it comes to instance selector)
  go.mod
  go.sum
  integration/tests/instance_selector/instance_selector_test.go
  pkg/apis/eksctl.io/v1alpha5/types.go
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/ctl/cmdutils/configfile.go
  pkg/ctl/cmdutils/nodegroup_flags.go
  pkg/ctl/create/cluster.go
  pkg/ctl/create/nodegroup.go
  pkg/ctl/get/nodegroup.go
  pkg/ctl/scale/nodegroup.go
  pkg/ctl/update/nodegroup.go
  pkg/ctl/upgrade/nodegroup.go
  pkg/eks/fakes/fake_instance_selector.go
  pkg/eks/nodegroup_service.go
  userdocs/src/usage/instance-selector.md
Labels: area/nodegroup, kind/improvement

#8249 Fix failure when VPC CNI is configured to use both iam.withOIDC and useDefaultPodIdentityAssociations
  pkg/actions/addon/tasks.go
  pkg/ctl/create/cluster.go
Labels: kind/bug, area/add-ons

#8244 Bump github.com/blang/semver to v4.0.0
  ATTRIBUTIONS.md
  go.mod
  go.sum
  pkg/actions/addon/get.go
  pkg/actions/nodegroup/ami.go
  pkg/actions/nodegroup/upgrade.go
  pkg/addons/default/aws_node.go
  pkg/addons/default/scripts/update_coredns_assets.go
  pkg/cfn/manager/nodegroup.go
  pkg/kubernetes/client.go
  pkg/utils/kubectl/kubectl.go
  pkg/utils/utils.go
  pkg/version/generate/release_generate.go
  pkg/version/parse.go
  pkg/version/parse_test.go
Labels: skip-release-notes, dependencies

#8250 Update Karpenter usage documentation to reflect latest supported version(s)
  userdocs/src/usage/eksctl-karpenter.md
Labels: kind/docs, area/karpenter

#8253 Update GH CLI and aws-iam-authenticator versions in docker image
  build/docker/Dockerfile
  build/docker/build_image_manifest
  build/docker/image_tag
Labels: kind/improvement, skip-release-notes, area/ci

#8252 Switch default for ExecConfig api version from v1alpha1->v1beta1
  pkg/utils/kubeconfig/kubeconfig.go
  pkg/utils/kubeconfig/kubeconfig_test.go
Labels: area/general-cli, kind/improvement

#8254 Fix go.sum; check go.mod and go.sum on CI
  .github/workflows/test-and-build.yaml
  Makefile
  go.sum
Labels: kind/improvement

#8255 generate/verify schema .. had forgotten to update schema.json for neuron devices
  .github/workflows/test-and-build.yaml
  Makefile
  pkg/apis/eksctl.io/v1alpha5/assets/schema.json
Labels: kind/improvement

#8257 Revert: Remove un-used build dependencies #8242
  .requirements
  build/docker/build_image_manifest
  build/docker/image_tag
  go.mod
  go.sum
  tools.go
Labels: skip-release-notes, dependencies, area/ci

#8260 Upgrade library: github.com/cenkalti/backoff/v5
  go.mod
  go.sum
  pkg/connector/connector.go
Labels: area/general-cli, skip-release-notes, dependencies

#8261 Allow adding remote network config to private clusters
  pkg/apis/eksctl.io/v1alpha5/validation.go
  pkg/apis/eksctl.io/v1alpha5/validation_test.go
Labels: kind/bug

#8264 Revert "Fix failure when VPC CNI is configured to use both iam.withOIDC and useDefaultPodIdentityAssociations
  pkg/actions/addon/tasks.go
  pkg/ctl/create/cluster.go
Labels: kind/bug
